// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/botartifact"
	"itsm-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BotArtifactUpdate is the builder for updating BotArtifact entities.
type BotArtifactUpdate struct {
	config
	hooks    []Hook
	mutation *BotArtifactMutation
}

// Where appends a list predicates to the BotArtifactUpdate builder.
func (_u *BotArtifactUpdate) Where(ps ...predicate.BotArtifact) *BotArtifactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *BotArtifactUpdate) SetTenantID(v int) *BotArtifactUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *BotArtifactUpdate) SetNillableTenantID(v *int) *BotArtifactUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *BotArtifactUpdate) AddTenantID(v int) *BotArtifactUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *BotArtifactUpdate) SetOwnerUserID(v int) *BotArtifactUpdate {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *BotArtifactUpdate) SetNillableOwnerUserID(v *int) *BotArtifactUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *BotArtifactUpdate) AddOwnerUserID(v int) *BotArtifactUpdate {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *BotArtifactUpdate) SetConversationID(v int) *BotArtifactUpdate {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *BotArtifactUpdate) SetNillableConversationID(v *int) *BotArtifactUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *BotArtifactUpdate) AddConversationID(v int) *BotArtifactUpdate {
	_u.mutation.AddConversationID(v)
	return _u
}

// ClearConversationID clears the value of the "conversation_id" field.
func (_u *BotArtifactUpdate) ClearConversationID() *BotArtifactUpdate {
	_u.mutation.ClearConversationID()
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *BotArtifactUpdate) SetRunID(v int) *BotArtifactUpdate {
	_u.mutation.ResetRunID()
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *BotArtifactUpdate) SetNillableRunID(v *int) *BotArtifactUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// AddRunID adds value to the "run_id" field.
func (_u *BotArtifactUpdate) AddRunID(v int) *BotArtifactUpdate {
	_u.mutation.AddRunID(v)
	return _u
}

// ClearRunID clears the value of the "run_id" field.
func (_u *BotArtifactUpdate) ClearRunID() *BotArtifactUpdate {
	_u.mutation.ClearRunID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *BotArtifactUpdate) SetKind(v string) *BotArtifactUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *BotArtifactUpdate) SetNillableKind(v *string) *BotArtifactUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetToolName sets the "tool_name" field.
func (_u *BotArtifactUpdate) SetToolName(v string) *BotArtifactUpdate {
	_u.mutation.SetToolName(v)
	return _u
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (_u *BotArtifactUpdate) SetNillableToolName(v *string) *BotArtifactUpdate {
	if v != nil {
		_u.SetToolName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BotArtifactUpdate) SetTitle(v string) *BotArtifactUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BotArtifactUpdate) SetNillableTitle(v *string) *BotArtifactUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContentJSON sets the "content_json" field.
func (_u *BotArtifactUpdate) SetContentJSON(v string) *BotArtifactUpdate {
	_u.mutation.SetContentJSON(v)
	return _u
}

// SetNillableContentJSON sets the "content_json" field if the given value is not nil.
func (_u *BotArtifactUpdate) SetNillableContentJSON(v *string) *BotArtifactUpdate {
	if v != nil {
		_u.SetContentJSON(*v)
	}
	return _u
}

// SetEvidenceJSON sets the "evidence_json" field.
func (_u *BotArtifactUpdate) SetEvidenceJSON(v string) *BotArtifactUpdate {
	_u.mutation.SetEvidenceJSON(v)
	return _u
}

// SetNillableEvidenceJSON sets the "evidence_json" field if the given value is not nil.
func (_u *BotArtifactUpdate) SetNillableEvidenceJSON(v *string) *BotArtifactUpdate {
	if v != nil {
		_u.SetEvidenceJSON(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BotArtifactUpdate) SetCreatedAt(v time.Time) *BotArtifactUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BotArtifactUpdate) SetNillableCreatedAt(v *time.Time) *BotArtifactUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the BotArtifactMutation object of the builder.
func (_u *BotArtifactUpdate) Mutation() *BotArtifactMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BotArtifactUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BotArtifactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BotArtifactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BotArtifactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BotArtifactUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := botartifact.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "BotArtifact.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerUserID(); ok {
		if err := botartifact.OwnerUserIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_user_id", err: fmt.Errorf(`ent: validator failed for field "BotArtifact.owner_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := botartifact.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "BotArtifact.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToolName(); ok {
		if err := botartifact.ToolNameValidator(v); err != nil {
			return &ValidationError{Name: "tool_name", err: fmt.Errorf(`ent: validator failed for field "BotArtifact.tool_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := botartifact.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BotArtifact.title": %w`, err)}
		}
	}
	return nil
}

func (_u *BotArtifactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(botartifact.Table, botartifact.Columns, sqlgraph.NewFieldSpec(botartifact.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(botartifact.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(botartifact.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(botartifact.FieldOwnerUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(botartifact.FieldOwnerUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(botartifact.FieldConversationID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(botartifact.FieldConversationID, field.TypeInt, value)
	}
	if _u.mutation.ConversationIDCleared() {
		_spec.ClearField(botartifact.FieldConversationID, field.TypeInt)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(botartifact.FieldRunID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRunID(); ok {
		_spec.AddField(botartifact.FieldRunID, field.TypeInt, value)
	}
	if _u.mutation.RunIDCleared() {
		_spec.ClearField(botartifact.FieldRunID, field.TypeInt)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(botartifact.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToolName(); ok {
		_spec.SetField(botartifact.FieldToolName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(botartifact.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentJSON(); ok {
		_spec.SetField(botartifact.FieldContentJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.EvidenceJSON(); ok {
		_spec.SetField(botartifact.FieldEvidenceJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(botartifact.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{botartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BotArtifactUpdateOne is the builder for updating a single BotArtifact entity.
type BotArtifactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BotArtifactMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *BotArtifactUpdateOne) SetTenantID(v int) *BotArtifactUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *BotArtifactUpdateOne) SetNillableTenantID(v *int) *BotArtifactUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *BotArtifactUpdateOne) AddTenantID(v int) *BotArtifactUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *BotArtifactUpdateOne) SetOwnerUserID(v int) *BotArtifactUpdateOne {
	_u.mutation.ResetOwnerUserID()
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *BotArtifactUpdateOne) SetNillableOwnerUserID(v *int) *BotArtifactUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// AddOwnerUserID adds value to the "owner_user_id" field.
func (_u *BotArtifactUpdateOne) AddOwnerUserID(v int) *BotArtifactUpdateOne {
	_u.mutation.AddOwnerUserID(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *BotArtifactUpdateOne) SetConversationID(v int) *BotArtifactUpdateOne {
	_u.mutation.ResetConversationID()
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *BotArtifactUpdateOne) SetNillableConversationID(v *int) *BotArtifactUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// AddConversationID adds value to the "conversation_id" field.
func (_u *BotArtifactUpdateOne) AddConversationID(v int) *BotArtifactUpdateOne {
	_u.mutation.AddConversationID(v)
	return _u
}

// ClearConversationID clears the value of the "conversation_id" field.
func (_u *BotArtifactUpdateOne) ClearConversationID() *BotArtifactUpdateOne {
	_u.mutation.ClearConversationID()
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *BotArtifactUpdateOne) SetRunID(v int) *BotArtifactUpdateOne {
	_u.mutation.ResetRunID()
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *BotArtifactUpdateOne) SetNillableRunID(v *int) *BotArtifactUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// AddRunID adds value to the "run_id" field.
func (_u *BotArtifactUpdateOne) AddRunID(v int) *BotArtifactUpdateOne {
	_u.mutation.AddRunID(v)
	return _u
}

// ClearRunID clears the value of the "run_id" field.
func (_u *BotArtifactUpdateOne) ClearRunID() *BotArtifactUpdateOne {
	_u.mutation.ClearRunID()
	return _u
}

// SetKind sets the "kind" field.
func (_u *BotArtifactUpdateOne) SetKind(v string) *BotArtifactUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *BotArtifactUpdateOne) SetNillableKind(v *string) *BotArtifactUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetToolName sets the "tool_name" field.
func (_u *BotArtifactUpdateOne) SetToolName(v string) *BotArtifactUpdateOne {
	_u.mutation.SetToolName(v)
	return _u
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (_u *BotArtifactUpdateOne) SetNillableToolName(v *string) *BotArtifactUpdateOne {
	if v != nil {
		_u.SetToolName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BotArtifactUpdateOne) SetTitle(v string) *BotArtifactUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BotArtifactUpdateOne) SetNillableTitle(v *string) *BotArtifactUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContentJSON sets the "content_json" field.
func (_u *BotArtifactUpdateOne) SetContentJSON(v string) *BotArtifactUpdateOne {
	_u.mutation.SetContentJSON(v)
	return _u
}

// SetNillableContentJSON sets the "content_json" field if the given value is not nil.
func (_u *BotArtifactUpdateOne) SetNillableContentJSON(v *string) *BotArtifactUpdateOne {
	if v != nil {
		_u.SetContentJSON(*v)
	}
	return _u
}

// SetEvidenceJSON sets the "evidence_json" field.
func (_u *BotArtifactUpdateOne) SetEvidenceJSON(v string) *BotArtifactUpdateOne {
	_u.mutation.SetEvidenceJSON(v)
	return _u
}

// SetNillableEvidenceJSON sets the "evidence_json" field if the given value is not nil.
func (_u *BotArtifactUpdateOne) SetNillableEvidenceJSON(v *string) *BotArtifactUpdateOne {
	if v != nil {
		_u.SetEvidenceJSON(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *BotArtifactUpdateOne) SetCreatedAt(v time.Time) *BotArtifactUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *BotArtifactUpdateOne) SetNillableCreatedAt(v *time.Time) *BotArtifactUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the BotArtifactMutation object of the builder.
func (_u *BotArtifactUpdateOne) Mutation() *BotArtifactMutation {
	return _u.mutation
}

// Where appends a list predicates to the BotArtifactUpdate builder.
func (_u *BotArtifactUpdateOne) Where(ps ...predicate.BotArtifact) *BotArtifactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BotArtifactUpdateOne) Select(field string, fields ...string) *BotArtifactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BotArtifact entity.
func (_u *BotArtifactUpdateOne) Save(ctx context.Context) (*BotArtifact, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BotArtifactUpdateOne) SaveX(ctx context.Context) *BotArtifact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BotArtifactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BotArtifactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BotArtifactUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := botartifact.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "BotArtifact.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OwnerUserID(); ok {
		if err := botartifact.OwnerUserIDValidator(v); err != nil {
			return &ValidationError{Name: "owner_user_id", err: fmt.Errorf(`ent: validator failed for field "BotArtifact.owner_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := botartifact.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "BotArtifact.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToolName(); ok {
		if err := botartifact.ToolNameValidator(v); err != nil {
			return &ValidationError{Name: "tool_name", err: fmt.Errorf(`ent: validator failed for field "BotArtifact.tool_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := botartifact.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BotArtifact.title": %w`, err)}
		}
	}
	return nil
}

func (_u *BotArtifactUpdateOne) sqlSave(ctx context.Context) (_node *BotArtifact, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(botartifact.Table, botartifact.Columns, sqlgraph.NewFieldSpec(botartifact.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BotArtifact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, botartifact.FieldID)
		for _, f := range fields {
			if !botartifact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != botartifact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(botartifact.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(botartifact.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OwnerUserID(); ok {
		_spec.SetField(botartifact.FieldOwnerUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOwnerUserID(); ok {
		_spec.AddField(botartifact.FieldOwnerUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConversationID(); ok {
		_spec.SetField(botartifact.FieldConversationID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConversationID(); ok {
		_spec.AddField(botartifact.FieldConversationID, field.TypeInt, value)
	}
	if _u.mutation.ConversationIDCleared() {
		_spec.ClearField(botartifact.FieldConversationID, field.TypeInt)
	}
	if value, ok := _u.mutation.RunID(); ok {
		_spec.SetField(botartifact.FieldRunID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRunID(); ok {
		_spec.AddField(botartifact.FieldRunID, field.TypeInt, value)
	}
	if _u.mutation.RunIDCleared() {
		_spec.ClearField(botartifact.FieldRunID, field.TypeInt)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(botartifact.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToolName(); ok {
		_spec.SetField(botartifact.FieldToolName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(botartifact.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentJSON(); ok {
		_spec.SetField(botartifact.FieldContentJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.EvidenceJSON(); ok {
		_spec.SetField(botartifact.FieldEvidenceJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(botartifact.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &BotArtifact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{botartifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
