// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/botrun"
	"itsm-backend/ent/botstep"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BotStepCreate is the builder for creating a BotStep entity.
type BotStepCreate struct {
	config
	mutation *BotStepMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *BotStepCreate) SetTenantID(v int) *BotStepCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *BotStepCreate) SetRunID(v int) *BotStepCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetStepIndex sets the "step_index" field.
func (_c *BotStepCreate) SetStepIndex(v int) *BotStepCreate {
	_c.mutation.SetStepIndex(v)
	return _c
}

// SetType sets the "type" field.
func (_c *BotStepCreate) SetType(v string) *BotStepCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetPayloadRef sets the "payload_ref" field.
func (_c *BotStepCreate) SetPayloadRef(v string) *BotStepCreate {
	_c.mutation.SetPayloadRef(v)
	return _c
}

// SetNillablePayloadRef sets the "payload_ref" field if the given value is not nil.
func (_c *BotStepCreate) SetNillablePayloadRef(v *string) *BotStepCreate {
	if v != nil {
		_c.SetPayloadRef(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *BotStepCreate) SetDurationMs(v int) *BotStepCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *BotStepCreate) SetNillableDurationMs(v *int) *BotStepCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *BotStepCreate) SetErrorCode(v string) *BotStepCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *BotStepCreate) SetNillableErrorCode(v *string) *BotStepCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BotStepCreate) SetCreatedAt(v time.Time) *BotStepCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BotStepCreate) SetNillableCreatedAt(v *time.Time) *BotStepCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRun sets the "run" edge to the BotRun entity.
func (_c *BotStepCreate) SetRun(v *BotRun) *BotStepCreate {
	return _c.SetRunID(v.ID)
}

// Mutation returns the BotStepMutation object of the builder.
func (_c *BotStepCreate) Mutation() *BotStepMutation {
	return _c.mutation
}

// Save creates the BotStep in the database.
func (_c *BotStepCreate) Save(ctx context.Context) (*BotStep, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BotStepCreate) SaveX(ctx context.Context) *BotStep {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BotStepCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BotStepCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BotStepCreate) defaults() {
	if _, ok := _c.mutation.PayloadRef(); !ok {
		v := botstep.DefaultPayloadRef
		_c.mutation.SetPayloadRef(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := botstep.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		v := botstep.DefaultErrorCode
		_c.mutation.SetErrorCode(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := botstep.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BotStepCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "BotStep.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := botstep.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "BotStep.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "BotStep.run_id"`)}
	}
	if _, ok := _c.mutation.StepIndex(); !ok {
		return &ValidationError{Name: "step_index", err: errors.New(`ent: missing required field "BotStep.step_index"`)}
	}
	if v, ok := _c.mutation.StepIndex(); ok {
		if err := botstep.StepIndexValidator(v); err != nil {
			return &ValidationError{Name: "step_index", err: fmt.Errorf(`ent: validator failed for field "BotStep.step_index": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "BotStep.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := botstep.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "BotStep.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PayloadRef(); !ok {
		return &ValidationError{Name: "payload_ref", err: errors.New(`ent: missing required field "BotStep.payload_ref"`)}
	}
	if v, ok := _c.mutation.PayloadRef(); ok {
		if err := botstep.PayloadRefValidator(v); err != nil {
			return &ValidationError{Name: "payload_ref", err: fmt.Errorf(`ent: validator failed for field "BotStep.payload_ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "BotStep.duration_ms"`)}
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "BotStep.error_code"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := botstep.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "BotStep.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BotStep.created_at"`)}
	}
	if len(_c.mutation.RunIDs()) == 0 {
		return &ValidationError{Name: "run", err: errors.New(`ent: missing required edge "BotStep.run"`)}
	}
	return nil
}

func (_c *BotStepCreate) sqlSave(ctx context.Context) (*BotStep, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BotStepCreate) createSpec() (*BotStep, *sqlgraph.CreateSpec) {
	var (
		_node = &BotStep{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(botstep.Table, sqlgraph.NewFieldSpec(botstep.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(botstep.FieldTenantID, field.TypeInt, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.StepIndex(); ok {
		_spec.SetField(botstep.FieldStepIndex, field.TypeInt, value)
		_node.StepIndex = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(botstep.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.PayloadRef(); ok {
		_spec.SetField(botstep.FieldPayloadRef, field.TypeString, value)
		_node.PayloadRef = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(botstep.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(botstep.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(botstep.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   botstep.RunTable,
			Columns: []string{botstep.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(botrun.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RunID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BotStepCreateBulk is the builder for creating many BotStep entities in bulk.
type BotStepCreateBulk struct {
	config
	err      error
	builders []*BotStepCreate
}

// Save creates the BotStep entities in the database.
func (_c *BotStepCreateBulk) Save(ctx context.Context) ([]*BotStep, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BotStep, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BotStepMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BotStepCreateBulk) SaveX(ctx context.Context) []*BotStep {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BotStepCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BotStepCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
