// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/bottemplate"
	"itsm-backend/ent/bottoolgrant"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BotTemplateCreate is the builder for creating a BotTemplate entity.
type BotTemplateCreate struct {
	config
	mutation *BotTemplateMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *BotTemplateCreate) SetTenantID(v int) *BotTemplateCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *BotTemplateCreate) SetSlug(v string) *BotTemplateCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *BotTemplateCreate) SetName(v string) *BotTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAudience sets the "audience" field.
func (_c *BotTemplateCreate) SetAudience(v string) *BotTemplateCreate {
	_c.mutation.SetAudience(v)
	return _c
}

// SetNillableAudience sets the "audience" field if the given value is not nil.
func (_c *BotTemplateCreate) SetNillableAudience(v *string) *BotTemplateCreate {
	if v != nil {
		_c.SetAudience(*v)
	}
	return _c
}

// SetRiskLimit sets the "risk_limit" field.
func (_c *BotTemplateCreate) SetRiskLimit(v string) *BotTemplateCreate {
	_c.mutation.SetRiskLimit(v)
	return _c
}

// SetNillableRiskLimit sets the "risk_limit" field if the given value is not nil.
func (_c *BotTemplateCreate) SetNillableRiskLimit(v *string) *BotTemplateCreate {
	if v != nil {
		_c.SetRiskLimit(*v)
	}
	return _c
}

// SetEntrypointsJSON sets the "entrypoints_json" field.
func (_c *BotTemplateCreate) SetEntrypointsJSON(v string) *BotTemplateCreate {
	_c.mutation.SetEntrypointsJSON(v)
	return _c
}

// SetNillableEntrypointsJSON sets the "entrypoints_json" field if the given value is not nil.
func (_c *BotTemplateCreate) SetNillableEntrypointsJSON(v *string) *BotTemplateCreate {
	if v != nil {
		_c.SetEntrypointsJSON(*v)
	}
	return _c
}

// SetSystemPromptRef sets the "system_prompt_ref" field.
func (_c *BotTemplateCreate) SetSystemPromptRef(v string) *BotTemplateCreate {
	_c.mutation.SetSystemPromptRef(v)
	return _c
}

// SetNillableSystemPromptRef sets the "system_prompt_ref" field if the given value is not nil.
func (_c *BotTemplateCreate) SetNillableSystemPromptRef(v *string) *BotTemplateCreate {
	if v != nil {
		_c.SetSystemPromptRef(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *BotTemplateCreate) SetStatus(v string) *BotTemplateCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BotTemplateCreate) SetNillableStatus(v *string) *BotTemplateCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BotTemplateCreate) SetCreatedAt(v time.Time) *BotTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BotTemplateCreate) SetNillableCreatedAt(v *time.Time) *BotTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BotTemplateCreate) SetUpdatedAt(v time.Time) *BotTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BotTemplateCreate) SetNillableUpdatedAt(v *time.Time) *BotTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddGrantIDs adds the "grants" edge to the BotToolGrant entity by IDs.
func (_c *BotTemplateCreate) AddGrantIDs(ids ...int) *BotTemplateCreate {
	_c.mutation.AddGrantIDs(ids...)
	return _c
}

// AddGrants adds the "grants" edges to the BotToolGrant entity.
func (_c *BotTemplateCreate) AddGrants(v ...*BotToolGrant) *BotTemplateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGrantIDs(ids...)
}

// Mutation returns the BotTemplateMutation object of the builder.
func (_c *BotTemplateCreate) Mutation() *BotTemplateMutation {
	return _c.mutation
}

// Save creates the BotTemplate in the database.
func (_c *BotTemplateCreate) Save(ctx context.Context) (*BotTemplate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BotTemplateCreate) SaveX(ctx context.Context) *BotTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BotTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BotTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BotTemplateCreate) defaults() {
	if _, ok := _c.mutation.Audience(); !ok {
		v := bottemplate.DefaultAudience
		_c.mutation.SetAudience(v)
	}
	if _, ok := _c.mutation.RiskLimit(); !ok {
		v := bottemplate.DefaultRiskLimit
		_c.mutation.SetRiskLimit(v)
	}
	if _, ok := _c.mutation.EntrypointsJSON(); !ok {
		v := bottemplate.DefaultEntrypointsJSON
		_c.mutation.SetEntrypointsJSON(v)
	}
	if _, ok := _c.mutation.SystemPromptRef(); !ok {
		v := bottemplate.DefaultSystemPromptRef
		_c.mutation.SetSystemPromptRef(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := bottemplate.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := bottemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := bottemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BotTemplateCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "BotTemplate.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := bottemplate.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "BotTemplate.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "BotTemplate.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := bottemplate.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "BotTemplate.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BotTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := bottemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BotTemplate.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Audience(); !ok {
		return &ValidationError{Name: "audience", err: errors.New(`ent: missing required field "BotTemplate.audience"`)}
	}
	if v, ok := _c.mutation.Audience(); ok {
		if err := bottemplate.AudienceValidator(v); err != nil {
			return &ValidationError{Name: "audience", err: fmt.Errorf(`ent: validator failed for field "BotTemplate.audience": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RiskLimit(); !ok {
		return &ValidationError{Name: "risk_limit", err: errors.New(`ent: missing required field "BotTemplate.risk_limit"`)}
	}
	if v, ok := _c.mutation.RiskLimit(); ok {
		if err := bottemplate.RiskLimitValidator(v); err != nil {
			return &ValidationError{Name: "risk_limit", err: fmt.Errorf(`ent: validator failed for field "BotTemplate.risk_limit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntrypointsJSON(); !ok {
		return &ValidationError{Name: "entrypoints_json", err: errors.New(`ent: missing required field "BotTemplate.entrypoints_json"`)}
	}
	if _, ok := _c.mutation.SystemPromptRef(); !ok {
		return &ValidationError{Name: "system_prompt_ref", err: errors.New(`ent: missing required field "BotTemplate.system_prompt_ref"`)}
	}
	if v, ok := _c.mutation.SystemPromptRef(); ok {
		if err := bottemplate.SystemPromptRefValidator(v); err != nil {
			return &ValidationError{Name: "system_prompt_ref", err: fmt.Errorf(`ent: validator failed for field "BotTemplate.system_prompt_ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BotTemplate.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := bottemplate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BotTemplate.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BotTemplate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BotTemplate.updated_at"`)}
	}
	return nil
}

func (_c *BotTemplateCreate) sqlSave(ctx context.Context) (*BotTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BotTemplateCreate) createSpec() (*BotTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &BotTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bottemplate.Table, sqlgraph.NewFieldSpec(bottemplate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(bottemplate.FieldTenantID, field.TypeInt, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(bottemplate.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(bottemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Audience(); ok {
		_spec.SetField(bottemplate.FieldAudience, field.TypeString, value)
		_node.Audience = value
	}
	if value, ok := _c.mutation.RiskLimit(); ok {
		_spec.SetField(bottemplate.FieldRiskLimit, field.TypeString, value)
		_node.RiskLimit = value
	}
	if value, ok := _c.mutation.EntrypointsJSON(); ok {
		_spec.SetField(bottemplate.FieldEntrypointsJSON, field.TypeString, value)
		_node.EntrypointsJSON = value
	}
	if value, ok := _c.mutation.SystemPromptRef(); ok {
		_spec.SetField(bottemplate.FieldSystemPromptRef, field.TypeString, value)
		_node.SystemPromptRef = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(bottemplate.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(bottemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(bottemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bottemplate.GrantsTable,
			Columns: []string{bottemplate.GrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bottoolgrant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BotTemplateCreateBulk is the builder for creating many BotTemplate entities in bulk.
type BotTemplateCreateBulk struct {
	config
	err      error
	builders []*BotTemplateCreate
}

// Save creates the BotTemplate entities in the database.
func (_c *BotTemplateCreateBulk) Save(ctx context.Context) ([]*BotTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BotTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BotTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BotTemplateCreateBulk) SaveX(ctx context.Context) []*BotTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BotTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BotTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
