// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"itsm-backend/ent/bottemplate"
	"itsm-backend/ent/bottoolgrant"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BotToolGrant is the model entity for the BotToolGrant schema.
type BotToolGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int `json:"tenant_id,omitempty"`
	// 所属模板（bot_templates.id）
	BotID int `json:"bot_id,omitempty"`
	// 工具唯一名（含 mcp__<server>__<tool> 投影名）
	ToolName string `json:"tool_name,omitempty"`
	// 该工具的风险上限（不超过模板上限）
	RiskLimit string `json:"risk_limit,omitempty"`
	// 参数策略 JSON（预留，B2-02 起用）
	ArgsPolicyJSON string `json:"args_policy_json,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BotToolGrantQuery when eager-loading is set.
	Edges        BotToolGrantEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BotToolGrantEdges holds the relations/edges for other nodes in the graph.
type BotToolGrantEdges struct {
	// Bot holds the value of the bot edge.
	Bot *BotTemplate `json:"bot,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BotOrErr returns the Bot value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BotToolGrantEdges) BotOrErr() (*BotTemplate, error) {
	if e.Bot != nil {
		return e.Bot, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: bottemplate.Label}
	}
	return nil, &NotLoadedError{edge: "bot"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BotToolGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bottoolgrant.FieldID, bottoolgrant.FieldTenantID, bottoolgrant.FieldBotID:
			values[i] = new(sql.NullInt64)
		case bottoolgrant.FieldToolName, bottoolgrant.FieldRiskLimit, bottoolgrant.FieldArgsPolicyJSON:
			values[i] = new(sql.NullString)
		case bottoolgrant.FieldCreatedAt, bottoolgrant.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BotToolGrant fields.
func (_m *BotToolGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bottoolgrant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case bottoolgrant.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case bottoolgrant.FieldBotID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bot_id", values[i])
			} else if value.Valid {
				_m.BotID = int(value.Int64)
			}
		case bottoolgrant.FieldToolName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tool_name", values[i])
			} else if value.Valid {
				_m.ToolName = value.String
			}
		case bottoolgrant.FieldRiskLimit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field risk_limit", values[i])
			} else if value.Valid {
				_m.RiskLimit = value.String
			}
		case bottoolgrant.FieldArgsPolicyJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field args_policy_json", values[i])
			} else if value.Valid {
				_m.ArgsPolicyJSON = value.String
			}
		case bottoolgrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case bottoolgrant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BotToolGrant.
// This includes values selected through modifiers, order, etc.
func (_m *BotToolGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBot queries the "bot" edge of the BotToolGrant entity.
func (_m *BotToolGrant) QueryBot() *BotTemplateQuery {
	return NewBotToolGrantClient(_m.config).QueryBot(_m)
}

// Update returns a builder for updating this BotToolGrant.
// Note that you need to call BotToolGrant.Unwrap() before calling this method if this BotToolGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BotToolGrant) Update() *BotToolGrantUpdateOne {
	return NewBotToolGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BotToolGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BotToolGrant) Unwrap() *BotToolGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BotToolGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BotToolGrant) String() string {
	var builder strings.Builder
	builder.WriteString("BotToolGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("bot_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BotID))
	builder.WriteString(", ")
	builder.WriteString("tool_name=")
	builder.WriteString(_m.ToolName)
	builder.WriteString(", ")
	builder.WriteString("risk_limit=")
	builder.WriteString(_m.RiskLimit)
	builder.WriteString(", ")
	builder.WriteString("args_policy_json=")
	builder.WriteString(_m.ArgsPolicyJSON)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BotToolGrants is a parsable slice of BotToolGrant.
type BotToolGrants []*BotToolGrant
