// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/knowledgearticle"
	"itsm-backend/ent/knowledgearticlelike"
	"itsm-backend/ent/knowledgearticlesession"
	"itsm-backend/ent/knowledgearticleversion"
	"itsm-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// KnowledgeArticleUpdate is the builder for updating KnowledgeArticle entities.
type KnowledgeArticleUpdate struct {
	config
	hooks    []Hook
	mutation *KnowledgeArticleMutation
}

// Where appends a list predicates to the KnowledgeArticleUpdate builder.
func (_u *KnowledgeArticleUpdate) Where(ps ...predicate.KnowledgeArticle) *KnowledgeArticleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *KnowledgeArticleUpdate) SetTitle(v string) *KnowledgeArticleUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableTitle(v *string) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *KnowledgeArticleUpdate) SetContent(v string) *KnowledgeArticleUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableContent(v *string) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *KnowledgeArticleUpdate) ClearContent() *KnowledgeArticleUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *KnowledgeArticleUpdate) SetContentType(v string) *KnowledgeArticleUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableContentType(v *string) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *KnowledgeArticleUpdate) SetCategory(v string) *KnowledgeArticleUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableCategory(v *string) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *KnowledgeArticleUpdate) ClearCategory() *KnowledgeArticleUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetTags sets the "tags" field.
func (_u *KnowledgeArticleUpdate) SetTags(v string) *KnowledgeArticleUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableTags(v *string) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *KnowledgeArticleUpdate) ClearTags() *KnowledgeArticleUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *KnowledgeArticleUpdate) SetAuthorID(v int) *KnowledgeArticleUpdate {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableAuthorID(v *int) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *KnowledgeArticleUpdate) AddAuthorID(v int) *KnowledgeArticleUpdate {
	_u.mutation.AddAuthorID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *KnowledgeArticleUpdate) SetTenantID(v int) *KnowledgeArticleUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableTenantID(v *int) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *KnowledgeArticleUpdate) AddTenantID(v int) *KnowledgeArticleUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetIsPublished sets the "is_published" field.
func (_u *KnowledgeArticleUpdate) SetIsPublished(v bool) *KnowledgeArticleUpdate {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableIsPublished(v *bool) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *KnowledgeArticleUpdate) SetViewCount(v int) *KnowledgeArticleUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableViewCount(v *int) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *KnowledgeArticleUpdate) AddViewCount(v int) *KnowledgeArticleUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *KnowledgeArticleUpdate) SetLikeCount(v int) *KnowledgeArticleUpdate {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableLikeCount(v *int) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *KnowledgeArticleUpdate) AddLikeCount(v int) *KnowledgeArticleUpdate {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetValidFrom sets the "valid_from" field.
func (_u *KnowledgeArticleUpdate) SetValidFrom(v time.Time) *KnowledgeArticleUpdate {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableValidFrom(v *time.Time) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// ClearValidFrom clears the value of the "valid_from" field.
func (_u *KnowledgeArticleUpdate) ClearValidFrom() *KnowledgeArticleUpdate {
	_u.mutation.ClearValidFrom()
	return _u
}

// SetValidUntil sets the "valid_until" field.
func (_u *KnowledgeArticleUpdate) SetValidUntil(v time.Time) *KnowledgeArticleUpdate {
	_u.mutation.SetValidUntil(v)
	return _u
}

// SetNillableValidUntil sets the "valid_until" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableValidUntil(v *time.Time) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetValidUntil(*v)
	}
	return _u
}

// ClearValidUntil clears the value of the "valid_until" field.
func (_u *KnowledgeArticleUpdate) ClearValidUntil() *KnowledgeArticleUpdate {
	_u.mutation.ClearValidUntil()
	return _u
}

// SetLastReviewedAt sets the "last_reviewed_at" field.
func (_u *KnowledgeArticleUpdate) SetLastReviewedAt(v time.Time) *KnowledgeArticleUpdate {
	_u.mutation.SetLastReviewedAt(v)
	return _u
}

// SetNillableLastReviewedAt sets the "last_reviewed_at" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableLastReviewedAt(v *time.Time) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetLastReviewedAt(*v)
	}
	return _u
}

// ClearLastReviewedAt clears the value of the "last_reviewed_at" field.
func (_u *KnowledgeArticleUpdate) ClearLastReviewedAt() *KnowledgeArticleUpdate {
	_u.mutation.ClearLastReviewedAt()
	return _u
}

// SetReviewIntervalDays sets the "review_interval_days" field.
func (_u *KnowledgeArticleUpdate) SetReviewIntervalDays(v int) *KnowledgeArticleUpdate {
	_u.mutation.ResetReviewIntervalDays()
	_u.mutation.SetReviewIntervalDays(v)
	return _u
}

// SetNillableReviewIntervalDays sets the "review_interval_days" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableReviewIntervalDays(v *int) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetReviewIntervalDays(*v)
	}
	return _u
}

// AddReviewIntervalDays adds value to the "review_interval_days" field.
func (_u *KnowledgeArticleUpdate) AddReviewIntervalDays(v int) *KnowledgeArticleUpdate {
	_u.mutation.AddReviewIntervalDays(v)
	return _u
}

// SetAuthorityLevel sets the "authority_level" field.
func (_u *KnowledgeArticleUpdate) SetAuthorityLevel(v int) *KnowledgeArticleUpdate {
	_u.mutation.ResetAuthorityLevel()
	_u.mutation.SetAuthorityLevel(v)
	return _u
}

// SetNillableAuthorityLevel sets the "authority_level" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableAuthorityLevel(v *int) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetAuthorityLevel(*v)
	}
	return _u
}

// AddAuthorityLevel adds value to the "authority_level" field.
func (_u *KnowledgeArticleUpdate) AddAuthorityLevel(v int) *KnowledgeArticleUpdate {
	_u.mutation.AddAuthorityLevel(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *KnowledgeArticleUpdate) SetCreatedAt(v time.Time) *KnowledgeArticleUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableCreatedAt(v *time.Time) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KnowledgeArticleUpdate) SetUpdatedAt(v time.Time) *KnowledgeArticleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KnowledgeArticleUpdate) SetDeletedAt(v time.Time) *KnowledgeArticleUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KnowledgeArticleUpdate) SetNillableDeletedAt(v *time.Time) *KnowledgeArticleUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KnowledgeArticleUpdate) ClearDeletedAt() *KnowledgeArticleUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddUserLikeIDs adds the "user_likes" edge to the KnowledgeArticleLike entity by IDs.
func (_u *KnowledgeArticleUpdate) AddUserLikeIDs(ids ...int) *KnowledgeArticleUpdate {
	_u.mutation.AddUserLikeIDs(ids...)
	return _u
}

// AddUserLikes adds the "user_likes" edges to the KnowledgeArticleLike entity.
func (_u *KnowledgeArticleUpdate) AddUserLikes(v ...*KnowledgeArticleLike) *KnowledgeArticleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserLikeIDs(ids...)
}

// AddVersionIDs adds the "versions" edge to the KnowledgeArticleVersion entity by IDs.
func (_u *KnowledgeArticleUpdate) AddVersionIDs(ids ...int) *KnowledgeArticleUpdate {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the KnowledgeArticleVersion entity.
func (_u *KnowledgeArticleUpdate) AddVersions(v ...*KnowledgeArticleVersion) *KnowledgeArticleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// AddSessionIDs adds the "sessions" edge to the KnowledgeArticleSession entity by IDs.
func (_u *KnowledgeArticleUpdate) AddSessionIDs(ids ...int) *KnowledgeArticleUpdate {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the KnowledgeArticleSession entity.
func (_u *KnowledgeArticleUpdate) AddSessions(v ...*KnowledgeArticleSession) *KnowledgeArticleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// Mutation returns the KnowledgeArticleMutation object of the builder.
func (_u *KnowledgeArticleUpdate) Mutation() *KnowledgeArticleMutation {
	return _u.mutation
}

// ClearUserLikes clears all "user_likes" edges to the KnowledgeArticleLike entity.
func (_u *KnowledgeArticleUpdate) ClearUserLikes() *KnowledgeArticleUpdate {
	_u.mutation.ClearUserLikes()
	return _u
}

// RemoveUserLikeIDs removes the "user_likes" edge to KnowledgeArticleLike entities by IDs.
func (_u *KnowledgeArticleUpdate) RemoveUserLikeIDs(ids ...int) *KnowledgeArticleUpdate {
	_u.mutation.RemoveUserLikeIDs(ids...)
	return _u
}

// RemoveUserLikes removes "user_likes" edges to KnowledgeArticleLike entities.
func (_u *KnowledgeArticleUpdate) RemoveUserLikes(v ...*KnowledgeArticleLike) *KnowledgeArticleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserLikeIDs(ids...)
}

// ClearVersions clears all "versions" edges to the KnowledgeArticleVersion entity.
func (_u *KnowledgeArticleUpdate) ClearVersions() *KnowledgeArticleUpdate {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to KnowledgeArticleVersion entities by IDs.
func (_u *KnowledgeArticleUpdate) RemoveVersionIDs(ids ...int) *KnowledgeArticleUpdate {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to KnowledgeArticleVersion entities.
func (_u *KnowledgeArticleUpdate) RemoveVersions(v ...*KnowledgeArticleVersion) *KnowledgeArticleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearSessions clears all "sessions" edges to the KnowledgeArticleSession entity.
func (_u *KnowledgeArticleUpdate) ClearSessions() *KnowledgeArticleUpdate {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to KnowledgeArticleSession entities by IDs.
func (_u *KnowledgeArticleUpdate) RemoveSessionIDs(ids ...int) *KnowledgeArticleUpdate {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to KnowledgeArticleSession entities.
func (_u *KnowledgeArticleUpdate) RemoveSessions(v ...*KnowledgeArticleSession) *KnowledgeArticleUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KnowledgeArticleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeArticleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KnowledgeArticleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeArticleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KnowledgeArticleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := knowledgearticle.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeArticleUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := knowledgearticle.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "KnowledgeArticle.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorID(); ok {
		if err := knowledgearticle.AuthorIDValidator(v); err != nil {
			return &ValidationError{Name: "author_id", err: fmt.Errorf(`ent: validator failed for field "KnowledgeArticle.author_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := knowledgearticle.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "KnowledgeArticle.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (_u *KnowledgeArticleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgearticle.Table, knowledgearticle.Columns, sqlgraph.NewFieldSpec(knowledgearticle.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(knowledgearticle.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(knowledgearticle.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(knowledgearticle.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(knowledgearticle.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(knowledgearticle.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(knowledgearticle.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(knowledgearticle.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(knowledgearticle.FieldTags, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(knowledgearticle.FieldAuthorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(knowledgearticle.FieldAuthorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(knowledgearticle.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(knowledgearticle.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(knowledgearticle.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(knowledgearticle.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(knowledgearticle.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(knowledgearticle.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(knowledgearticle.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(knowledgearticle.FieldValidFrom, field.TypeTime, value)
	}
	if _u.mutation.ValidFromCleared() {
		_spec.ClearField(knowledgearticle.FieldValidFrom, field.TypeTime)
	}
	if value, ok := _u.mutation.ValidUntil(); ok {
		_spec.SetField(knowledgearticle.FieldValidUntil, field.TypeTime, value)
	}
	if _u.mutation.ValidUntilCleared() {
		_spec.ClearField(knowledgearticle.FieldValidUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LastReviewedAt(); ok {
		_spec.SetField(knowledgearticle.FieldLastReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.LastReviewedAtCleared() {
		_spec.ClearField(knowledgearticle.FieldLastReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewIntervalDays(); ok {
		_spec.SetField(knowledgearticle.FieldReviewIntervalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewIntervalDays(); ok {
		_spec.AddField(knowledgearticle.FieldReviewIntervalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AuthorityLevel(); ok {
		_spec.SetField(knowledgearticle.FieldAuthorityLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAuthorityLevel(); ok {
		_spec.AddField(knowledgearticle.FieldAuthorityLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(knowledgearticle.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgearticle.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(knowledgearticle.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(knowledgearticle.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.UserLikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.UserLikesTable,
			Columns: []string{knowledgearticle.UserLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlelike.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserLikesIDs(); len(nodes) > 0 && !_u.mutation.UserLikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.UserLikesTable,
			Columns: []string{knowledgearticle.UserLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlelike.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserLikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.UserLikesTable,
			Columns: []string{knowledgearticle.UserLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlelike.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.VersionsTable,
			Columns: []string{knowledgearticle.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticleversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.VersionsTable,
			Columns: []string{knowledgearticle.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticleversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.VersionsTable,
			Columns: []string{knowledgearticle.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticleversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.SessionsTable,
			Columns: []string{knowledgearticle.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlesession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.SessionsTable,
			Columns: []string{knowledgearticle.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.SessionsTable,
			Columns: []string{knowledgearticle.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgearticle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KnowledgeArticleUpdateOne is the builder for updating a single KnowledgeArticle entity.
type KnowledgeArticleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KnowledgeArticleMutation
}

// SetTitle sets the "title" field.
func (_u *KnowledgeArticleUpdateOne) SetTitle(v string) *KnowledgeArticleUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableTitle(v *string) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *KnowledgeArticleUpdateOne) SetContent(v string) *KnowledgeArticleUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableContent(v *string) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *KnowledgeArticleUpdateOne) ClearContent() *KnowledgeArticleUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *KnowledgeArticleUpdateOne) SetContentType(v string) *KnowledgeArticleUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableContentType(v *string) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *KnowledgeArticleUpdateOne) SetCategory(v string) *KnowledgeArticleUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableCategory(v *string) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *KnowledgeArticleUpdateOne) ClearCategory() *KnowledgeArticleUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetTags sets the "tags" field.
func (_u *KnowledgeArticleUpdateOne) SetTags(v string) *KnowledgeArticleUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableTags(v *string) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *KnowledgeArticleUpdateOne) ClearTags() *KnowledgeArticleUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *KnowledgeArticleUpdateOne) SetAuthorID(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableAuthorID(v *int) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *KnowledgeArticleUpdateOne) AddAuthorID(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.AddAuthorID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *KnowledgeArticleUpdateOne) SetTenantID(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableTenantID(v *int) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *KnowledgeArticleUpdateOne) AddTenantID(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetIsPublished sets the "is_published" field.
func (_u *KnowledgeArticleUpdateOne) SetIsPublished(v bool) *KnowledgeArticleUpdateOne {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableIsPublished(v *bool) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *KnowledgeArticleUpdateOne) SetViewCount(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableViewCount(v *int) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *KnowledgeArticleUpdateOne) AddViewCount(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *KnowledgeArticleUpdateOne) SetLikeCount(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableLikeCount(v *int) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *KnowledgeArticleUpdateOne) AddLikeCount(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetValidFrom sets the "valid_from" field.
func (_u *KnowledgeArticleUpdateOne) SetValidFrom(v time.Time) *KnowledgeArticleUpdateOne {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableValidFrom(v *time.Time) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// ClearValidFrom clears the value of the "valid_from" field.
func (_u *KnowledgeArticleUpdateOne) ClearValidFrom() *KnowledgeArticleUpdateOne {
	_u.mutation.ClearValidFrom()
	return _u
}

// SetValidUntil sets the "valid_until" field.
func (_u *KnowledgeArticleUpdateOne) SetValidUntil(v time.Time) *KnowledgeArticleUpdateOne {
	_u.mutation.SetValidUntil(v)
	return _u
}

// SetNillableValidUntil sets the "valid_until" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableValidUntil(v *time.Time) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetValidUntil(*v)
	}
	return _u
}

// ClearValidUntil clears the value of the "valid_until" field.
func (_u *KnowledgeArticleUpdateOne) ClearValidUntil() *KnowledgeArticleUpdateOne {
	_u.mutation.ClearValidUntil()
	return _u
}

// SetLastReviewedAt sets the "last_reviewed_at" field.
func (_u *KnowledgeArticleUpdateOne) SetLastReviewedAt(v time.Time) *KnowledgeArticleUpdateOne {
	_u.mutation.SetLastReviewedAt(v)
	return _u
}

// SetNillableLastReviewedAt sets the "last_reviewed_at" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableLastReviewedAt(v *time.Time) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetLastReviewedAt(*v)
	}
	return _u
}

// ClearLastReviewedAt clears the value of the "last_reviewed_at" field.
func (_u *KnowledgeArticleUpdateOne) ClearLastReviewedAt() *KnowledgeArticleUpdateOne {
	_u.mutation.ClearLastReviewedAt()
	return _u
}

// SetReviewIntervalDays sets the "review_interval_days" field.
func (_u *KnowledgeArticleUpdateOne) SetReviewIntervalDays(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.ResetReviewIntervalDays()
	_u.mutation.SetReviewIntervalDays(v)
	return _u
}

// SetNillableReviewIntervalDays sets the "review_interval_days" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableReviewIntervalDays(v *int) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetReviewIntervalDays(*v)
	}
	return _u
}

// AddReviewIntervalDays adds value to the "review_interval_days" field.
func (_u *KnowledgeArticleUpdateOne) AddReviewIntervalDays(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.AddReviewIntervalDays(v)
	return _u
}

// SetAuthorityLevel sets the "authority_level" field.
func (_u *KnowledgeArticleUpdateOne) SetAuthorityLevel(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.ResetAuthorityLevel()
	_u.mutation.SetAuthorityLevel(v)
	return _u
}

// SetNillableAuthorityLevel sets the "authority_level" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableAuthorityLevel(v *int) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetAuthorityLevel(*v)
	}
	return _u
}

// AddAuthorityLevel adds value to the "authority_level" field.
func (_u *KnowledgeArticleUpdateOne) AddAuthorityLevel(v int) *KnowledgeArticleUpdateOne {
	_u.mutation.AddAuthorityLevel(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *KnowledgeArticleUpdateOne) SetCreatedAt(v time.Time) *KnowledgeArticleUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableCreatedAt(v *time.Time) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KnowledgeArticleUpdateOne) SetUpdatedAt(v time.Time) *KnowledgeArticleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KnowledgeArticleUpdateOne) SetDeletedAt(v time.Time) *KnowledgeArticleUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KnowledgeArticleUpdateOne) SetNillableDeletedAt(v *time.Time) *KnowledgeArticleUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KnowledgeArticleUpdateOne) ClearDeletedAt() *KnowledgeArticleUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddUserLikeIDs adds the "user_likes" edge to the KnowledgeArticleLike entity by IDs.
func (_u *KnowledgeArticleUpdateOne) AddUserLikeIDs(ids ...int) *KnowledgeArticleUpdateOne {
	_u.mutation.AddUserLikeIDs(ids...)
	return _u
}

// AddUserLikes adds the "user_likes" edges to the KnowledgeArticleLike entity.
func (_u *KnowledgeArticleUpdateOne) AddUserLikes(v ...*KnowledgeArticleLike) *KnowledgeArticleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserLikeIDs(ids...)
}

// AddVersionIDs adds the "versions" edge to the KnowledgeArticleVersion entity by IDs.
func (_u *KnowledgeArticleUpdateOne) AddVersionIDs(ids ...int) *KnowledgeArticleUpdateOne {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the KnowledgeArticleVersion entity.
func (_u *KnowledgeArticleUpdateOne) AddVersions(v ...*KnowledgeArticleVersion) *KnowledgeArticleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// AddSessionIDs adds the "sessions" edge to the KnowledgeArticleSession entity by IDs.
func (_u *KnowledgeArticleUpdateOne) AddSessionIDs(ids ...int) *KnowledgeArticleUpdateOne {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the KnowledgeArticleSession entity.
func (_u *KnowledgeArticleUpdateOne) AddSessions(v ...*KnowledgeArticleSession) *KnowledgeArticleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// Mutation returns the KnowledgeArticleMutation object of the builder.
func (_u *KnowledgeArticleUpdateOne) Mutation() *KnowledgeArticleMutation {
	return _u.mutation
}

// ClearUserLikes clears all "user_likes" edges to the KnowledgeArticleLike entity.
func (_u *KnowledgeArticleUpdateOne) ClearUserLikes() *KnowledgeArticleUpdateOne {
	_u.mutation.ClearUserLikes()
	return _u
}

// RemoveUserLikeIDs removes the "user_likes" edge to KnowledgeArticleLike entities by IDs.
func (_u *KnowledgeArticleUpdateOne) RemoveUserLikeIDs(ids ...int) *KnowledgeArticleUpdateOne {
	_u.mutation.RemoveUserLikeIDs(ids...)
	return _u
}

// RemoveUserLikes removes "user_likes" edges to KnowledgeArticleLike entities.
func (_u *KnowledgeArticleUpdateOne) RemoveUserLikes(v ...*KnowledgeArticleLike) *KnowledgeArticleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserLikeIDs(ids...)
}

// ClearVersions clears all "versions" edges to the KnowledgeArticleVersion entity.
func (_u *KnowledgeArticleUpdateOne) ClearVersions() *KnowledgeArticleUpdateOne {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to KnowledgeArticleVersion entities by IDs.
func (_u *KnowledgeArticleUpdateOne) RemoveVersionIDs(ids ...int) *KnowledgeArticleUpdateOne {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to KnowledgeArticleVersion entities.
func (_u *KnowledgeArticleUpdateOne) RemoveVersions(v ...*KnowledgeArticleVersion) *KnowledgeArticleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// ClearSessions clears all "sessions" edges to the KnowledgeArticleSession entity.
func (_u *KnowledgeArticleUpdateOne) ClearSessions() *KnowledgeArticleUpdateOne {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to KnowledgeArticleSession entities by IDs.
func (_u *KnowledgeArticleUpdateOne) RemoveSessionIDs(ids ...int) *KnowledgeArticleUpdateOne {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to KnowledgeArticleSession entities.
func (_u *KnowledgeArticleUpdateOne) RemoveSessions(v ...*KnowledgeArticleSession) *KnowledgeArticleUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// Where appends a list predicates to the KnowledgeArticleUpdate builder.
func (_u *KnowledgeArticleUpdateOne) Where(ps ...predicate.KnowledgeArticle) *KnowledgeArticleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KnowledgeArticleUpdateOne) Select(field string, fields ...string) *KnowledgeArticleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KnowledgeArticle entity.
func (_u *KnowledgeArticleUpdateOne) Save(ctx context.Context) (*KnowledgeArticle, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeArticleUpdateOne) SaveX(ctx context.Context) *KnowledgeArticle {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KnowledgeArticleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeArticleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KnowledgeArticleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := knowledgearticle.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeArticleUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := knowledgearticle.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "KnowledgeArticle.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthorID(); ok {
		if err := knowledgearticle.AuthorIDValidator(v); err != nil {
			return &ValidationError{Name: "author_id", err: fmt.Errorf(`ent: validator failed for field "KnowledgeArticle.author_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TenantID(); ok {
		if err := knowledgearticle.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "KnowledgeArticle.tenant_id": %w`, err)}
		}
	}
	return nil
}

func (_u *KnowledgeArticleUpdateOne) sqlSave(ctx context.Context) (_node *KnowledgeArticle, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgearticle.Table, knowledgearticle.Columns, sqlgraph.NewFieldSpec(knowledgearticle.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KnowledgeArticle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, knowledgearticle.FieldID)
		for _, f := range fields {
			if !knowledgearticle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != knowledgearticle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(knowledgearticle.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(knowledgearticle.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(knowledgearticle.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(knowledgearticle.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(knowledgearticle.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(knowledgearticle.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(knowledgearticle.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(knowledgearticle.FieldTags, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(knowledgearticle.FieldAuthorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(knowledgearticle.FieldAuthorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(knowledgearticle.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(knowledgearticle.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(knowledgearticle.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(knowledgearticle.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(knowledgearticle.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(knowledgearticle.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(knowledgearticle.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(knowledgearticle.FieldValidFrom, field.TypeTime, value)
	}
	if _u.mutation.ValidFromCleared() {
		_spec.ClearField(knowledgearticle.FieldValidFrom, field.TypeTime)
	}
	if value, ok := _u.mutation.ValidUntil(); ok {
		_spec.SetField(knowledgearticle.FieldValidUntil, field.TypeTime, value)
	}
	if _u.mutation.ValidUntilCleared() {
		_spec.ClearField(knowledgearticle.FieldValidUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.LastReviewedAt(); ok {
		_spec.SetField(knowledgearticle.FieldLastReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.LastReviewedAtCleared() {
		_spec.ClearField(knowledgearticle.FieldLastReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewIntervalDays(); ok {
		_spec.SetField(knowledgearticle.FieldReviewIntervalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewIntervalDays(); ok {
		_spec.AddField(knowledgearticle.FieldReviewIntervalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AuthorityLevel(); ok {
		_spec.SetField(knowledgearticle.FieldAuthorityLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAuthorityLevel(); ok {
		_spec.AddField(knowledgearticle.FieldAuthorityLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(knowledgearticle.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgearticle.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(knowledgearticle.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(knowledgearticle.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.UserLikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.UserLikesTable,
			Columns: []string{knowledgearticle.UserLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlelike.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserLikesIDs(); len(nodes) > 0 && !_u.mutation.UserLikesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.UserLikesTable,
			Columns: []string{knowledgearticle.UserLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlelike.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserLikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.UserLikesTable,
			Columns: []string{knowledgearticle.UserLikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlelike.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.VersionsTable,
			Columns: []string{knowledgearticle.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticleversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.VersionsTable,
			Columns: []string{knowledgearticle.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticleversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.VersionsTable,
			Columns: []string{knowledgearticle.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticleversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.SessionsTable,
			Columns: []string{knowledgearticle.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlesession.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.SessionsTable,
			Columns: []string{knowledgearticle.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   knowledgearticle.SessionsTable,
			Columns: []string{knowledgearticle.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(knowledgearticlesession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &KnowledgeArticle{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgearticle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
