// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"itsm-backend/ent/llmuserpreference"
	"itsm-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LLMUserPreferenceDelete is the builder for deleting a LLMUserPreference entity.
type LLMUserPreferenceDelete struct {
	config
	hooks    []Hook
	mutation *LLMUserPreferenceMutation
}

// Where appends a list predicates to the LLMUserPreferenceDelete builder.
func (_d *LLMUserPreferenceDelete) Where(ps ...predicate.LLMUserPreference) *LLMUserPreferenceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LLMUserPreferenceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LLMUserPreferenceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LLMUserPreferenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(llmuserpreference.Table, sqlgraph.NewFieldSpec(llmuserpreference.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LLMUserPreferenceDeleteOne is the builder for deleting a single LLMUserPreference entity.
type LLMUserPreferenceDeleteOne struct {
	_d *LLMUserPreferenceDelete
}

// Where appends a list predicates to the LLMUserPreferenceDelete builder.
func (_d *LLMUserPreferenceDeleteOne) Where(ps ...predicate.LLMUserPreference) *LLMUserPreferenceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LLMUserPreferenceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{llmuserpreference.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LLMUserPreferenceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
