// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/mcpserver"
	"itsm-backend/ent/mcpservertool"
	"itsm-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// MCPServerUpdate is the builder for updating MCPServer entities.
type MCPServerUpdate struct {
	config
	hooks    []Hook
	mutation *MCPServerMutation
}

// Where appends a list predicates to the MCPServerUpdate builder.
func (_u *MCPServerUpdate) Where(ps ...predicate.MCPServer) *MCPServerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *MCPServerUpdate) SetTenantID(v int) *MCPServerUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableTenantID(v *int) *MCPServerUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *MCPServerUpdate) AddTenantID(v int) *MCPServerUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *MCPServerUpdate) SetName(v string) *MCPServerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableName(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *MCPServerUpdate) SetDisplayName(v string) *MCPServerUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableDisplayName(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetTransport sets the "transport" field.
func (_u *MCPServerUpdate) SetTransport(v string) *MCPServerUpdate {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableTransport(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *MCPServerUpdate) SetURL(v string) *MCPServerUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableURL(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *MCPServerUpdate) ClearURL() *MCPServerUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetCommand sets the "command" field.
func (_u *MCPServerUpdate) SetCommand(v string) *MCPServerUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableCommand(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *MCPServerUpdate) ClearCommand() *MCPServerUpdate {
	_u.mutation.ClearCommand()
	return _u
}

// SetArgs sets the "args" field.
func (_u *MCPServerUpdate) SetArgs(v []string) *MCPServerUpdate {
	_u.mutation.SetArgs(v)
	return _u
}

// AppendArgs appends value to the "args" field.
func (_u *MCPServerUpdate) AppendArgs(v []string) *MCPServerUpdate {
	_u.mutation.AppendArgs(v)
	return _u
}

// ClearArgs clears the value of the "args" field.
func (_u *MCPServerUpdate) ClearArgs() *MCPServerUpdate {
	_u.mutation.ClearArgs()
	return _u
}

// SetEnv sets the "env" field.
func (_u *MCPServerUpdate) SetEnv(v map[string]string) *MCPServerUpdate {
	_u.mutation.SetEnv(v)
	return _u
}

// ClearEnv clears the value of the "env" field.
func (_u *MCPServerUpdate) ClearEnv() *MCPServerUpdate {
	_u.mutation.ClearEnv()
	return _u
}

// SetWorkingDir sets the "working_dir" field.
func (_u *MCPServerUpdate) SetWorkingDir(v string) *MCPServerUpdate {
	_u.mutation.SetWorkingDir(v)
	return _u
}

// SetNillableWorkingDir sets the "working_dir" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableWorkingDir(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetWorkingDir(*v)
	}
	return _u
}

// ClearWorkingDir clears the value of the "working_dir" field.
func (_u *MCPServerUpdate) ClearWorkingDir() *MCPServerUpdate {
	_u.mutation.ClearWorkingDir()
	return _u
}

// SetHeadersEncrypted sets the "headers_encrypted" field.
func (_u *MCPServerUpdate) SetHeadersEncrypted(v string) *MCPServerUpdate {
	_u.mutation.SetHeadersEncrypted(v)
	return _u
}

// SetNillableHeadersEncrypted sets the "headers_encrypted" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableHeadersEncrypted(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetHeadersEncrypted(*v)
	}
	return _u
}

// ClearHeadersEncrypted clears the value of the "headers_encrypted" field.
func (_u *MCPServerUpdate) ClearHeadersEncrypted() *MCPServerUpdate {
	_u.mutation.ClearHeadersEncrypted()
	return _u
}

// SetCredentialType sets the "credential_type" field.
func (_u *MCPServerUpdate) SetCredentialType(v string) *MCPServerUpdate {
	_u.mutation.SetCredentialType(v)
	return _u
}

// SetNillableCredentialType sets the "credential_type" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableCredentialType(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetCredentialType(*v)
	}
	return _u
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (_u *MCPServerUpdate) SetCredentialEncrypted(v string) *MCPServerUpdate {
	_u.mutation.SetCredentialEncrypted(v)
	return _u
}

// SetNillableCredentialEncrypted sets the "credential_encrypted" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableCredentialEncrypted(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetCredentialEncrypted(*v)
	}
	return _u
}

// ClearCredentialEncrypted clears the value of the "credential_encrypted" field.
func (_u *MCPServerUpdate) ClearCredentialEncrypted() *MCPServerUpdate {
	_u.mutation.ClearCredentialEncrypted()
	return _u
}

// SetTrustLevel sets the "trust_level" field.
func (_u *MCPServerUpdate) SetTrustLevel(v string) *MCPServerUpdate {
	_u.mutation.SetTrustLevel(v)
	return _u
}

// SetNillableTrustLevel sets the "trust_level" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableTrustLevel(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetTrustLevel(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MCPServerUpdate) SetEnabled(v bool) *MCPServerUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableEnabled(v *bool) *MCPServerUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MCPServerUpdate) SetStatus(v string) *MCPServerUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableStatus(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *MCPServerUpdate) SetLastError(v string) *MCPServerUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableLastError(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetLastConnectedAt sets the "last_connected_at" field.
func (_u *MCPServerUpdate) SetLastConnectedAt(v time.Time) *MCPServerUpdate {
	_u.mutation.SetLastConnectedAt(v)
	return _u
}

// SetNillableLastConnectedAt sets the "last_connected_at" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableLastConnectedAt(v *time.Time) *MCPServerUpdate {
	if v != nil {
		_u.SetLastConnectedAt(*v)
	}
	return _u
}

// ClearLastConnectedAt clears the value of the "last_connected_at" field.
func (_u *MCPServerUpdate) ClearLastConnectedAt() *MCPServerUpdate {
	_u.mutation.ClearLastConnectedAt()
	return _u
}

// SetProtocolVersion sets the "protocol_version" field.
func (_u *MCPServerUpdate) SetProtocolVersion(v string) *MCPServerUpdate {
	_u.mutation.SetProtocolVersion(v)
	return _u
}

// SetNillableProtocolVersion sets the "protocol_version" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableProtocolVersion(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetProtocolVersion(*v)
	}
	return _u
}

// SetServerInfo sets the "server_info" field.
func (_u *MCPServerUpdate) SetServerInfo(v string) *MCPServerUpdate {
	_u.mutation.SetServerInfo(v)
	return _u
}

// SetNillableServerInfo sets the "server_info" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableServerInfo(v *string) *MCPServerUpdate {
	if v != nil {
		_u.SetServerInfo(*v)
	}
	return _u
}

// ClearServerInfo clears the value of the "server_info" field.
func (_u *MCPServerUpdate) ClearServerInfo() *MCPServerUpdate {
	_u.mutation.ClearServerInfo()
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *MCPServerUpdate) SetTimeoutMs(v int) *MCPServerUpdate {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableTimeoutMs(v *int) *MCPServerUpdate {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *MCPServerUpdate) AddTimeoutMs(v int) *MCPServerUpdate {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetMaxParallelCalls sets the "max_parallel_calls" field.
func (_u *MCPServerUpdate) SetMaxParallelCalls(v int) *MCPServerUpdate {
	_u.mutation.ResetMaxParallelCalls()
	_u.mutation.SetMaxParallelCalls(v)
	return _u
}

// SetNillableMaxParallelCalls sets the "max_parallel_calls" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableMaxParallelCalls(v *int) *MCPServerUpdate {
	if v != nil {
		_u.SetMaxParallelCalls(*v)
	}
	return _u
}

// AddMaxParallelCalls adds value to the "max_parallel_calls" field.
func (_u *MCPServerUpdate) AddMaxParallelCalls(v int) *MCPServerUpdate {
	_u.mutation.AddMaxParallelCalls(v)
	return _u
}

// SetMaxRetry sets the "max_retry" field.
func (_u *MCPServerUpdate) SetMaxRetry(v int) *MCPServerUpdate {
	_u.mutation.ResetMaxRetry()
	_u.mutation.SetMaxRetry(v)
	return _u
}

// SetNillableMaxRetry sets the "max_retry" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableMaxRetry(v *int) *MCPServerUpdate {
	if v != nil {
		_u.SetMaxRetry(*v)
	}
	return _u
}

// AddMaxRetry adds value to the "max_retry" field.
func (_u *MCPServerUpdate) AddMaxRetry(v int) *MCPServerUpdate {
	_u.mutation.AddMaxRetry(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *MCPServerUpdate) SetVersion(v int) *MCPServerUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableVersion(v *int) *MCPServerUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *MCPServerUpdate) AddVersion(v int) *MCPServerUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MCPServerUpdate) SetCreatedAt(v time.Time) *MCPServerUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MCPServerUpdate) SetNillableCreatedAt(v *time.Time) *MCPServerUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MCPServerUpdate) SetUpdatedAt(v time.Time) *MCPServerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddToolIDs adds the "tools" edge to the MCPServerTool entity by IDs.
func (_u *MCPServerUpdate) AddToolIDs(ids ...int) *MCPServerUpdate {
	_u.mutation.AddToolIDs(ids...)
	return _u
}

// AddTools adds the "tools" edges to the MCPServerTool entity.
func (_u *MCPServerUpdate) AddTools(v ...*MCPServerTool) *MCPServerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddToolIDs(ids...)
}

// Mutation returns the MCPServerMutation object of the builder.
func (_u *MCPServerUpdate) Mutation() *MCPServerMutation {
	return _u.mutation
}

// ClearTools clears all "tools" edges to the MCPServerTool entity.
func (_u *MCPServerUpdate) ClearTools() *MCPServerUpdate {
	_u.mutation.ClearTools()
	return _u
}

// RemoveToolIDs removes the "tools" edge to MCPServerTool entities by IDs.
func (_u *MCPServerUpdate) RemoveToolIDs(ids ...int) *MCPServerUpdate {
	_u.mutation.RemoveToolIDs(ids...)
	return _u
}

// RemoveTools removes "tools" edges to MCPServerTool entities.
func (_u *MCPServerUpdate) RemoveTools(v ...*MCPServerTool) *MCPServerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveToolIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MCPServerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPServerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MCPServerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPServerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MCPServerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mcpserver.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPServerUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := mcpserver.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "MCPServer.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := mcpserver.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MCPServer.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := mcpserver.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "MCPServer.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Transport(); ok {
		if err := mcpserver.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "MCPServer.transport": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := mcpserver.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "MCPServer.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkingDir(); ok {
		if err := mcpserver.WorkingDirValidator(v); err != nil {
			return &ValidationError{Name: "working_dir", err: fmt.Errorf(`ent: validator failed for field "MCPServer.working_dir": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialType(); ok {
		if err := mcpserver.CredentialTypeValidator(v); err != nil {
			return &ValidationError{Name: "credential_type", err: fmt.Errorf(`ent: validator failed for field "MCPServer.credential_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TrustLevel(); ok {
		if err := mcpserver.TrustLevelValidator(v); err != nil {
			return &ValidationError{Name: "trust_level", err: fmt.Errorf(`ent: validator failed for field "MCPServer.trust_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mcpserver.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MCPServer.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastError(); ok {
		if err := mcpserver.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "MCPServer.last_error": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProtocolVersion(); ok {
		if err := mcpserver.ProtocolVersionValidator(v); err != nil {
			return &ValidationError{Name: "protocol_version", err: fmt.Errorf(`ent: validator failed for field "MCPServer.protocol_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TimeoutMs(); ok {
		if err := mcpserver.TimeoutMsValidator(v); err != nil {
			return &ValidationError{Name: "timeout_ms", err: fmt.Errorf(`ent: validator failed for field "MCPServer.timeout_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxParallelCalls(); ok {
		if err := mcpserver.MaxParallelCallsValidator(v); err != nil {
			return &ValidationError{Name: "max_parallel_calls", err: fmt.Errorf(`ent: validator failed for field "MCPServer.max_parallel_calls": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxRetry(); ok {
		if err := mcpserver.MaxRetryValidator(v); err != nil {
			return &ValidationError{Name: "max_retry", err: fmt.Errorf(`ent: validator failed for field "MCPServer.max_retry": %w`, err)}
		}
	}
	return nil
}

func (_u *MCPServerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcpserver.Table, mcpserver.Columns, sqlgraph.NewFieldSpec(mcpserver.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(mcpserver.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(mcpserver.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mcpserver.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(mcpserver.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(mcpserver.FieldTransport, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(mcpserver.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(mcpserver.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(mcpserver.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(mcpserver.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(mcpserver.FieldArgs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedArgs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mcpserver.FieldArgs, value)
		})
	}
	if _u.mutation.ArgsCleared() {
		_spec.ClearField(mcpserver.FieldArgs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(mcpserver.FieldEnv, field.TypeJSON, value)
	}
	if _u.mutation.EnvCleared() {
		_spec.ClearField(mcpserver.FieldEnv, field.TypeJSON)
	}
	if value, ok := _u.mutation.WorkingDir(); ok {
		_spec.SetField(mcpserver.FieldWorkingDir, field.TypeString, value)
	}
	if _u.mutation.WorkingDirCleared() {
		_spec.ClearField(mcpserver.FieldWorkingDir, field.TypeString)
	}
	if value, ok := _u.mutation.HeadersEncrypted(); ok {
		_spec.SetField(mcpserver.FieldHeadersEncrypted, field.TypeString, value)
	}
	if _u.mutation.HeadersEncryptedCleared() {
		_spec.ClearField(mcpserver.FieldHeadersEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.CredentialType(); ok {
		_spec.SetField(mcpserver.FieldCredentialType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialEncrypted(); ok {
		_spec.SetField(mcpserver.FieldCredentialEncrypted, field.TypeString, value)
	}
	if _u.mutation.CredentialEncryptedCleared() {
		_spec.ClearField(mcpserver.FieldCredentialEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TrustLevel(); ok {
		_spec.SetField(mcpserver.FieldTrustLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mcpserver.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mcpserver.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(mcpserver.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastConnectedAt(); ok {
		_spec.SetField(mcpserver.FieldLastConnectedAt, field.TypeTime, value)
	}
	if _u.mutation.LastConnectedAtCleared() {
		_spec.ClearField(mcpserver.FieldLastConnectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ProtocolVersion(); ok {
		_spec.SetField(mcpserver.FieldProtocolVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServerInfo(); ok {
		_spec.SetField(mcpserver.FieldServerInfo, field.TypeString, value)
	}
	if _u.mutation.ServerInfoCleared() {
		_spec.ClearField(mcpserver.FieldServerInfo, field.TypeString)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(mcpserver.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(mcpserver.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxParallelCalls(); ok {
		_spec.SetField(mcpserver.FieldMaxParallelCalls, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxParallelCalls(); ok {
		_spec.AddField(mcpserver.FieldMaxParallelCalls, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxRetry(); ok {
		_spec.SetField(mcpserver.FieldMaxRetry, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRetry(); ok {
		_spec.AddField(mcpserver.FieldMaxRetry, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(mcpserver.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(mcpserver.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(mcpserver.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mcpserver.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ToolsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpserver.ToolsTable,
			Columns: []string{mcpserver.ToolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpservertool.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedToolsIDs(); len(nodes) > 0 && !_u.mutation.ToolsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpserver.ToolsTable,
			Columns: []string{mcpserver.ToolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpservertool.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ToolsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpserver.ToolsTable,
			Columns: []string{mcpserver.ToolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpservertool.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpserver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MCPServerUpdateOne is the builder for updating a single MCPServer entity.
type MCPServerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MCPServerMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *MCPServerUpdateOne) SetTenantID(v int) *MCPServerUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableTenantID(v *int) *MCPServerUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *MCPServerUpdateOne) AddTenantID(v int) *MCPServerUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *MCPServerUpdateOne) SetName(v string) *MCPServerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableName(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *MCPServerUpdateOne) SetDisplayName(v string) *MCPServerUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableDisplayName(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetTransport sets the "transport" field.
func (_u *MCPServerUpdateOne) SetTransport(v string) *MCPServerUpdateOne {
	_u.mutation.SetTransport(v)
	return _u
}

// SetNillableTransport sets the "transport" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableTransport(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetTransport(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *MCPServerUpdateOne) SetURL(v string) *MCPServerUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableURL(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *MCPServerUpdateOne) ClearURL() *MCPServerUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetCommand sets the "command" field.
func (_u *MCPServerUpdateOne) SetCommand(v string) *MCPServerUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableCommand(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *MCPServerUpdateOne) ClearCommand() *MCPServerUpdateOne {
	_u.mutation.ClearCommand()
	return _u
}

// SetArgs sets the "args" field.
func (_u *MCPServerUpdateOne) SetArgs(v []string) *MCPServerUpdateOne {
	_u.mutation.SetArgs(v)
	return _u
}

// AppendArgs appends value to the "args" field.
func (_u *MCPServerUpdateOne) AppendArgs(v []string) *MCPServerUpdateOne {
	_u.mutation.AppendArgs(v)
	return _u
}

// ClearArgs clears the value of the "args" field.
func (_u *MCPServerUpdateOne) ClearArgs() *MCPServerUpdateOne {
	_u.mutation.ClearArgs()
	return _u
}

// SetEnv sets the "env" field.
func (_u *MCPServerUpdateOne) SetEnv(v map[string]string) *MCPServerUpdateOne {
	_u.mutation.SetEnv(v)
	return _u
}

// ClearEnv clears the value of the "env" field.
func (_u *MCPServerUpdateOne) ClearEnv() *MCPServerUpdateOne {
	_u.mutation.ClearEnv()
	return _u
}

// SetWorkingDir sets the "working_dir" field.
func (_u *MCPServerUpdateOne) SetWorkingDir(v string) *MCPServerUpdateOne {
	_u.mutation.SetWorkingDir(v)
	return _u
}

// SetNillableWorkingDir sets the "working_dir" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableWorkingDir(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetWorkingDir(*v)
	}
	return _u
}

// ClearWorkingDir clears the value of the "working_dir" field.
func (_u *MCPServerUpdateOne) ClearWorkingDir() *MCPServerUpdateOne {
	_u.mutation.ClearWorkingDir()
	return _u
}

// SetHeadersEncrypted sets the "headers_encrypted" field.
func (_u *MCPServerUpdateOne) SetHeadersEncrypted(v string) *MCPServerUpdateOne {
	_u.mutation.SetHeadersEncrypted(v)
	return _u
}

// SetNillableHeadersEncrypted sets the "headers_encrypted" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableHeadersEncrypted(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetHeadersEncrypted(*v)
	}
	return _u
}

// ClearHeadersEncrypted clears the value of the "headers_encrypted" field.
func (_u *MCPServerUpdateOne) ClearHeadersEncrypted() *MCPServerUpdateOne {
	_u.mutation.ClearHeadersEncrypted()
	return _u
}

// SetCredentialType sets the "credential_type" field.
func (_u *MCPServerUpdateOne) SetCredentialType(v string) *MCPServerUpdateOne {
	_u.mutation.SetCredentialType(v)
	return _u
}

// SetNillableCredentialType sets the "credential_type" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableCredentialType(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetCredentialType(*v)
	}
	return _u
}

// SetCredentialEncrypted sets the "credential_encrypted" field.
func (_u *MCPServerUpdateOne) SetCredentialEncrypted(v string) *MCPServerUpdateOne {
	_u.mutation.SetCredentialEncrypted(v)
	return _u
}

// SetNillableCredentialEncrypted sets the "credential_encrypted" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableCredentialEncrypted(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetCredentialEncrypted(*v)
	}
	return _u
}

// ClearCredentialEncrypted clears the value of the "credential_encrypted" field.
func (_u *MCPServerUpdateOne) ClearCredentialEncrypted() *MCPServerUpdateOne {
	_u.mutation.ClearCredentialEncrypted()
	return _u
}

// SetTrustLevel sets the "trust_level" field.
func (_u *MCPServerUpdateOne) SetTrustLevel(v string) *MCPServerUpdateOne {
	_u.mutation.SetTrustLevel(v)
	return _u
}

// SetNillableTrustLevel sets the "trust_level" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableTrustLevel(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetTrustLevel(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *MCPServerUpdateOne) SetEnabled(v bool) *MCPServerUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableEnabled(v *bool) *MCPServerUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MCPServerUpdateOne) SetStatus(v string) *MCPServerUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableStatus(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *MCPServerUpdateOne) SetLastError(v string) *MCPServerUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableLastError(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetLastConnectedAt sets the "last_connected_at" field.
func (_u *MCPServerUpdateOne) SetLastConnectedAt(v time.Time) *MCPServerUpdateOne {
	_u.mutation.SetLastConnectedAt(v)
	return _u
}

// SetNillableLastConnectedAt sets the "last_connected_at" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableLastConnectedAt(v *time.Time) *MCPServerUpdateOne {
	if v != nil {
		_u.SetLastConnectedAt(*v)
	}
	return _u
}

// ClearLastConnectedAt clears the value of the "last_connected_at" field.
func (_u *MCPServerUpdateOne) ClearLastConnectedAt() *MCPServerUpdateOne {
	_u.mutation.ClearLastConnectedAt()
	return _u
}

// SetProtocolVersion sets the "protocol_version" field.
func (_u *MCPServerUpdateOne) SetProtocolVersion(v string) *MCPServerUpdateOne {
	_u.mutation.SetProtocolVersion(v)
	return _u
}

// SetNillableProtocolVersion sets the "protocol_version" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableProtocolVersion(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetProtocolVersion(*v)
	}
	return _u
}

// SetServerInfo sets the "server_info" field.
func (_u *MCPServerUpdateOne) SetServerInfo(v string) *MCPServerUpdateOne {
	_u.mutation.SetServerInfo(v)
	return _u
}

// SetNillableServerInfo sets the "server_info" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableServerInfo(v *string) *MCPServerUpdateOne {
	if v != nil {
		_u.SetServerInfo(*v)
	}
	return _u
}

// ClearServerInfo clears the value of the "server_info" field.
func (_u *MCPServerUpdateOne) ClearServerInfo() *MCPServerUpdateOne {
	_u.mutation.ClearServerInfo()
	return _u
}

// SetTimeoutMs sets the "timeout_ms" field.
func (_u *MCPServerUpdateOne) SetTimeoutMs(v int) *MCPServerUpdateOne {
	_u.mutation.ResetTimeoutMs()
	_u.mutation.SetTimeoutMs(v)
	return _u
}

// SetNillableTimeoutMs sets the "timeout_ms" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableTimeoutMs(v *int) *MCPServerUpdateOne {
	if v != nil {
		_u.SetTimeoutMs(*v)
	}
	return _u
}

// AddTimeoutMs adds value to the "timeout_ms" field.
func (_u *MCPServerUpdateOne) AddTimeoutMs(v int) *MCPServerUpdateOne {
	_u.mutation.AddTimeoutMs(v)
	return _u
}

// SetMaxParallelCalls sets the "max_parallel_calls" field.
func (_u *MCPServerUpdateOne) SetMaxParallelCalls(v int) *MCPServerUpdateOne {
	_u.mutation.ResetMaxParallelCalls()
	_u.mutation.SetMaxParallelCalls(v)
	return _u
}

// SetNillableMaxParallelCalls sets the "max_parallel_calls" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableMaxParallelCalls(v *int) *MCPServerUpdateOne {
	if v != nil {
		_u.SetMaxParallelCalls(*v)
	}
	return _u
}

// AddMaxParallelCalls adds value to the "max_parallel_calls" field.
func (_u *MCPServerUpdateOne) AddMaxParallelCalls(v int) *MCPServerUpdateOne {
	_u.mutation.AddMaxParallelCalls(v)
	return _u
}

// SetMaxRetry sets the "max_retry" field.
func (_u *MCPServerUpdateOne) SetMaxRetry(v int) *MCPServerUpdateOne {
	_u.mutation.ResetMaxRetry()
	_u.mutation.SetMaxRetry(v)
	return _u
}

// SetNillableMaxRetry sets the "max_retry" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableMaxRetry(v *int) *MCPServerUpdateOne {
	if v != nil {
		_u.SetMaxRetry(*v)
	}
	return _u
}

// AddMaxRetry adds value to the "max_retry" field.
func (_u *MCPServerUpdateOne) AddMaxRetry(v int) *MCPServerUpdateOne {
	_u.mutation.AddMaxRetry(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *MCPServerUpdateOne) SetVersion(v int) *MCPServerUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableVersion(v *int) *MCPServerUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *MCPServerUpdateOne) AddVersion(v int) *MCPServerUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MCPServerUpdateOne) SetCreatedAt(v time.Time) *MCPServerUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MCPServerUpdateOne) SetNillableCreatedAt(v *time.Time) *MCPServerUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MCPServerUpdateOne) SetUpdatedAt(v time.Time) *MCPServerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddToolIDs adds the "tools" edge to the MCPServerTool entity by IDs.
func (_u *MCPServerUpdateOne) AddToolIDs(ids ...int) *MCPServerUpdateOne {
	_u.mutation.AddToolIDs(ids...)
	return _u
}

// AddTools adds the "tools" edges to the MCPServerTool entity.
func (_u *MCPServerUpdateOne) AddTools(v ...*MCPServerTool) *MCPServerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddToolIDs(ids...)
}

// Mutation returns the MCPServerMutation object of the builder.
func (_u *MCPServerUpdateOne) Mutation() *MCPServerMutation {
	return _u.mutation
}

// ClearTools clears all "tools" edges to the MCPServerTool entity.
func (_u *MCPServerUpdateOne) ClearTools() *MCPServerUpdateOne {
	_u.mutation.ClearTools()
	return _u
}

// RemoveToolIDs removes the "tools" edge to MCPServerTool entities by IDs.
func (_u *MCPServerUpdateOne) RemoveToolIDs(ids ...int) *MCPServerUpdateOne {
	_u.mutation.RemoveToolIDs(ids...)
	return _u
}

// RemoveTools removes "tools" edges to MCPServerTool entities.
func (_u *MCPServerUpdateOne) RemoveTools(v ...*MCPServerTool) *MCPServerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveToolIDs(ids...)
}

// Where appends a list predicates to the MCPServerUpdate builder.
func (_u *MCPServerUpdateOne) Where(ps ...predicate.MCPServer) *MCPServerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MCPServerUpdateOne) Select(field string, fields ...string) *MCPServerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MCPServer entity.
func (_u *MCPServerUpdateOne) Save(ctx context.Context) (*MCPServer, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPServerUpdateOne) SaveX(ctx context.Context) *MCPServer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MCPServerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPServerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MCPServerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mcpserver.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPServerUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := mcpserver.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "MCPServer.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := mcpserver.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MCPServer.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := mcpserver.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "MCPServer.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Transport(); ok {
		if err := mcpserver.TransportValidator(v); err != nil {
			return &ValidationError{Name: "transport", err: fmt.Errorf(`ent: validator failed for field "MCPServer.transport": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := mcpserver.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "MCPServer.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WorkingDir(); ok {
		if err := mcpserver.WorkingDirValidator(v); err != nil {
			return &ValidationError{Name: "working_dir", err: fmt.Errorf(`ent: validator failed for field "MCPServer.working_dir": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CredentialType(); ok {
		if err := mcpserver.CredentialTypeValidator(v); err != nil {
			return &ValidationError{Name: "credential_type", err: fmt.Errorf(`ent: validator failed for field "MCPServer.credential_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TrustLevel(); ok {
		if err := mcpserver.TrustLevelValidator(v); err != nil {
			return &ValidationError{Name: "trust_level", err: fmt.Errorf(`ent: validator failed for field "MCPServer.trust_level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mcpserver.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MCPServer.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastError(); ok {
		if err := mcpserver.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "MCPServer.last_error": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProtocolVersion(); ok {
		if err := mcpserver.ProtocolVersionValidator(v); err != nil {
			return &ValidationError{Name: "protocol_version", err: fmt.Errorf(`ent: validator failed for field "MCPServer.protocol_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TimeoutMs(); ok {
		if err := mcpserver.TimeoutMsValidator(v); err != nil {
			return &ValidationError{Name: "timeout_ms", err: fmt.Errorf(`ent: validator failed for field "MCPServer.timeout_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxParallelCalls(); ok {
		if err := mcpserver.MaxParallelCallsValidator(v); err != nil {
			return &ValidationError{Name: "max_parallel_calls", err: fmt.Errorf(`ent: validator failed for field "MCPServer.max_parallel_calls": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxRetry(); ok {
		if err := mcpserver.MaxRetryValidator(v); err != nil {
			return &ValidationError{Name: "max_retry", err: fmt.Errorf(`ent: validator failed for field "MCPServer.max_retry": %w`, err)}
		}
	}
	return nil
}

func (_u *MCPServerUpdateOne) sqlSave(ctx context.Context) (_node *MCPServer, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcpserver.Table, mcpserver.Columns, sqlgraph.NewFieldSpec(mcpserver.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MCPServer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mcpserver.FieldID)
		for _, f := range fields {
			if !mcpserver.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mcpserver.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(mcpserver.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(mcpserver.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mcpserver.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(mcpserver.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Transport(); ok {
		_spec.SetField(mcpserver.FieldTransport, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(mcpserver.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(mcpserver.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(mcpserver.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(mcpserver.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(mcpserver.FieldArgs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedArgs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mcpserver.FieldArgs, value)
		})
	}
	if _u.mutation.ArgsCleared() {
		_spec.ClearField(mcpserver.FieldArgs, field.TypeJSON)
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(mcpserver.FieldEnv, field.TypeJSON, value)
	}
	if _u.mutation.EnvCleared() {
		_spec.ClearField(mcpserver.FieldEnv, field.TypeJSON)
	}
	if value, ok := _u.mutation.WorkingDir(); ok {
		_spec.SetField(mcpserver.FieldWorkingDir, field.TypeString, value)
	}
	if _u.mutation.WorkingDirCleared() {
		_spec.ClearField(mcpserver.FieldWorkingDir, field.TypeString)
	}
	if value, ok := _u.mutation.HeadersEncrypted(); ok {
		_spec.SetField(mcpserver.FieldHeadersEncrypted, field.TypeString, value)
	}
	if _u.mutation.HeadersEncryptedCleared() {
		_spec.ClearField(mcpserver.FieldHeadersEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.CredentialType(); ok {
		_spec.SetField(mcpserver.FieldCredentialType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CredentialEncrypted(); ok {
		_spec.SetField(mcpserver.FieldCredentialEncrypted, field.TypeString, value)
	}
	if _u.mutation.CredentialEncryptedCleared() {
		_spec.ClearField(mcpserver.FieldCredentialEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TrustLevel(); ok {
		_spec.SetField(mcpserver.FieldTrustLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(mcpserver.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mcpserver.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(mcpserver.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastConnectedAt(); ok {
		_spec.SetField(mcpserver.FieldLastConnectedAt, field.TypeTime, value)
	}
	if _u.mutation.LastConnectedAtCleared() {
		_spec.ClearField(mcpserver.FieldLastConnectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ProtocolVersion(); ok {
		_spec.SetField(mcpserver.FieldProtocolVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServerInfo(); ok {
		_spec.SetField(mcpserver.FieldServerInfo, field.TypeString, value)
	}
	if _u.mutation.ServerInfoCleared() {
		_spec.ClearField(mcpserver.FieldServerInfo, field.TypeString)
	}
	if value, ok := _u.mutation.TimeoutMs(); ok {
		_spec.SetField(mcpserver.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMs(); ok {
		_spec.AddField(mcpserver.FieldTimeoutMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxParallelCalls(); ok {
		_spec.SetField(mcpserver.FieldMaxParallelCalls, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxParallelCalls(); ok {
		_spec.AddField(mcpserver.FieldMaxParallelCalls, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxRetry(); ok {
		_spec.SetField(mcpserver.FieldMaxRetry, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxRetry(); ok {
		_spec.AddField(mcpserver.FieldMaxRetry, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(mcpserver.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(mcpserver.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(mcpserver.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mcpserver.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ToolsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpserver.ToolsTable,
			Columns: []string{mcpserver.ToolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpservertool.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedToolsIDs(); len(nodes) > 0 && !_u.mutation.ToolsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpserver.ToolsTable,
			Columns: []string{mcpserver.ToolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpservertool.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ToolsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpserver.ToolsTable,
			Columns: []string{mcpserver.ToolsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpservertool.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MCPServer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpserver.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
