// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/mspallocation"
	"itsm-backend/ent/tenant"
	"itsm-backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MSPAllocationCreate is the builder for creating a MSPAllocation entity.
type MSPAllocationCreate struct {
	config
	mutation *MSPAllocationMutation
	hooks    []Hook
}

// SetMspUserID sets the "msp_user_id" field.
func (_c *MSPAllocationCreate) SetMspUserID(v int) *MSPAllocationCreate {
	_c.mutation.SetMspUserID(v)
	return _c
}

// SetCustomerTenantID sets the "customer_tenant_id" field.
func (_c *MSPAllocationCreate) SetCustomerTenantID(v int) *MSPAllocationCreate {
	_c.mutation.SetCustomerTenantID(v)
	return _c
}

// SetProviderTenantID sets the "provider_tenant_id" field.
func (_c *MSPAllocationCreate) SetProviderTenantID(v int) *MSPAllocationCreate {
	_c.mutation.SetProviderTenantID(v)
	return _c
}

// SetNillableProviderTenantID sets the "provider_tenant_id" field if the given value is not nil.
func (_c *MSPAllocationCreate) SetNillableProviderTenantID(v *int) *MSPAllocationCreate {
	if v != nil {
		_c.SetProviderTenantID(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *MSPAllocationCreate) SetRole(v string) *MSPAllocationCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *MSPAllocationCreate) SetNillableRole(v *string) *MSPAllocationCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *MSPAllocationCreate) SetAssignedAt(v time.Time) *MSPAllocationCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *MSPAllocationCreate) SetNillableAssignedAt(v *time.Time) *MSPAllocationCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetDeassignedAt sets the "deassigned_at" field.
func (_c *MSPAllocationCreate) SetDeassignedAt(v time.Time) *MSPAllocationCreate {
	_c.mutation.SetDeassignedAt(v)
	return _c
}

// SetNillableDeassignedAt sets the "deassigned_at" field if the given value is not nil.
func (_c *MSPAllocationCreate) SetNillableDeassignedAt(v *time.Time) *MSPAllocationCreate {
	if v != nil {
		_c.SetDeassignedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MSPAllocationCreate) SetCreatedAt(v time.Time) *MSPAllocationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MSPAllocationCreate) SetNillableCreatedAt(v *time.Time) *MSPAllocationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetMspUser sets the "msp_user" edge to the User entity.
func (_c *MSPAllocationCreate) SetMspUser(v *User) *MSPAllocationCreate {
	return _c.SetMspUserID(v.ID)
}

// SetCustomerTenant sets the "customer_tenant" edge to the Tenant entity.
func (_c *MSPAllocationCreate) SetCustomerTenant(v *Tenant) *MSPAllocationCreate {
	return _c.SetCustomerTenantID(v.ID)
}

// SetProviderTenant sets the "provider_tenant" edge to the Tenant entity.
func (_c *MSPAllocationCreate) SetProviderTenant(v *Tenant) *MSPAllocationCreate {
	return _c.SetProviderTenantID(v.ID)
}

// Mutation returns the MSPAllocationMutation object of the builder.
func (_c *MSPAllocationCreate) Mutation() *MSPAllocationMutation {
	return _c.mutation
}

// Save creates the MSPAllocation in the database.
func (_c *MSPAllocationCreate) Save(ctx context.Context) (*MSPAllocation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MSPAllocationCreate) SaveX(ctx context.Context) *MSPAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MSPAllocationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MSPAllocationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MSPAllocationCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := mspallocation.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		v := mspallocation.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mspallocation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MSPAllocationCreate) check() error {
	if _, ok := _c.mutation.MspUserID(); !ok {
		return &ValidationError{Name: "msp_user_id", err: errors.New(`ent: missing required field "MSPAllocation.msp_user_id"`)}
	}
	if _, ok := _c.mutation.CustomerTenantID(); !ok {
		return &ValidationError{Name: "customer_tenant_id", err: errors.New(`ent: missing required field "MSPAllocation.customer_tenant_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "MSPAllocation.role"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "MSPAllocation.assigned_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MSPAllocation.created_at"`)}
	}
	if len(_c.mutation.MspUserIDs()) == 0 {
		return &ValidationError{Name: "msp_user", err: errors.New(`ent: missing required edge "MSPAllocation.msp_user"`)}
	}
	if len(_c.mutation.CustomerTenantIDs()) == 0 {
		return &ValidationError{Name: "customer_tenant", err: errors.New(`ent: missing required edge "MSPAllocation.customer_tenant"`)}
	}
	return nil
}

func (_c *MSPAllocationCreate) sqlSave(ctx context.Context) (*MSPAllocation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MSPAllocationCreate) createSpec() (*MSPAllocation, *sqlgraph.CreateSpec) {
	var (
		_node = &MSPAllocation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mspallocation.Table, sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(mspallocation.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(mspallocation.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if value, ok := _c.mutation.DeassignedAt(); ok {
		_spec.SetField(mspallocation.FieldDeassignedAt, field.TypeTime, value)
		_node.DeassignedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mspallocation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.MspUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mspallocation.MspUserTable,
			Columns: []string{mspallocation.MspUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MspUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CustomerTenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mspallocation.CustomerTenantTable,
			Columns: []string{mspallocation.CustomerTenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CustomerTenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProviderTenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mspallocation.ProviderTenantTable,
			Columns: []string{mspallocation.ProviderTenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProviderTenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MSPAllocationCreateBulk is the builder for creating many MSPAllocation entities in bulk.
type MSPAllocationCreateBulk struct {
	config
	err      error
	builders []*MSPAllocationCreate
}

// Save creates the MSPAllocation entities in the database.
func (_c *MSPAllocationCreateBulk) Save(ctx context.Context) ([]*MSPAllocation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MSPAllocation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MSPAllocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MSPAllocationCreateBulk) SaveX(ctx context.Context) []*MSPAllocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MSPAllocationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MSPAllocationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
