// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/bootstraptoken"
	"itsm-backend/ent/mspallocation"
	"itsm-backend/ent/predicate"
	"itsm-backend/ent/tenant"
	"itsm-backend/ent/user"
	"itsm-backend/ent/usertenantmembership"
	"itsm-backend/ent/usertenantmembershiporg"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdate) SetName(v string) *TenantUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TenantUpdate) SetCode(v string) *TenantUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableCode(v *string) *TenantUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdate) SetDomain(v string) *TenantUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableDomain(v *string) *TenantUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *TenantUpdate) ClearDomain() *TenantUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// SetType sets the "type" field.
func (_u *TenantUpdate) SetType(v tenant.Type) *TenantUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableType(v *tenant.Type) *TenantUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdate) SetStatus(v string) *TenantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableStatus(v *string) *TenantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetParentTenantID sets the "parent_tenant_id" field.
func (_u *TenantUpdate) SetParentTenantID(v int) *TenantUpdate {
	_u.mutation.ResetParentTenantID()
	_u.mutation.SetParentTenantID(v)
	return _u
}

// SetNillableParentTenantID sets the "parent_tenant_id" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableParentTenantID(v *int) *TenantUpdate {
	if v != nil {
		_u.SetParentTenantID(*v)
	}
	return _u
}

// AddParentTenantID adds value to the "parent_tenant_id" field.
func (_u *TenantUpdate) AddParentTenantID(v int) *TenantUpdate {
	_u.mutation.AddParentTenantID(v)
	return _u
}

// ClearParentTenantID clears the value of the "parent_tenant_id" field.
func (_u *TenantUpdate) ClearParentTenantID() *TenantUpdate {
	_u.mutation.ClearParentTenantID()
	return _u
}

// SetMspProviderID sets the "msp_provider_id" field.
func (_u *TenantUpdate) SetMspProviderID(v int) *TenantUpdate {
	_u.mutation.ResetMspProviderID()
	_u.mutation.SetMspProviderID(v)
	return _u
}

// SetNillableMspProviderID sets the "msp_provider_id" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableMspProviderID(v *int) *TenantUpdate {
	if v != nil {
		_u.SetMspProviderID(*v)
	}
	return _u
}

// AddMspProviderID adds value to the "msp_provider_id" field.
func (_u *TenantUpdate) AddMspProviderID(v int) *TenantUpdate {
	_u.mutation.AddMspProviderID(v)
	return _u
}

// ClearMspProviderID clears the value of the "msp_provider_id" field.
func (_u *TenantUpdate) ClearMspProviderID() *TenantUpdate {
	_u.mutation.ClearMspProviderID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TenantUpdate) SetExpiresAt(v time.Time) *TenantUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableExpiresAt(v *time.Time) *TenantUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *TenantUpdate) ClearExpiresAt() *TenantUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetPlanCode sets the "plan_code" field.
func (_u *TenantUpdate) SetPlanCode(v string) *TenantUpdate {
	_u.mutation.SetPlanCode(v)
	return _u
}

// SetNillablePlanCode sets the "plan_code" field if the given value is not nil.
func (_u *TenantUpdate) SetNillablePlanCode(v *string) *TenantUpdate {
	if v != nil {
		_u.SetPlanCode(*v)
	}
	return _u
}

// ClearPlanCode clears the value of the "plan_code" field.
func (_u *TenantUpdate) ClearPlanCode() *TenantUpdate {
	_u.mutation.ClearPlanCode()
	return _u
}

// SetBillingEnabled sets the "billing_enabled" field.
func (_u *TenantUpdate) SetBillingEnabled(v bool) *TenantUpdate {
	_u.mutation.SetBillingEnabled(v)
	return _u
}

// SetNillableBillingEnabled sets the "billing_enabled" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableBillingEnabled(v *bool) *TenantUpdate {
	if v != nil {
		_u.SetBillingEnabled(*v)
	}
	return _u
}

// SetCostCenterCode sets the "cost_center_code" field.
func (_u *TenantUpdate) SetCostCenterCode(v string) *TenantUpdate {
	_u.mutation.SetCostCenterCode(v)
	return _u
}

// SetNillableCostCenterCode sets the "cost_center_code" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableCostCenterCode(v *string) *TenantUpdate {
	if v != nil {
		_u.SetCostCenterCode(*v)
	}
	return _u
}

// ClearCostCenterCode clears the value of the "cost_center_code" field.
func (_u *TenantUpdate) ClearCostCenterCode() *TenantUpdate {
	_u.mutation.ClearCostCenterCode()
	return _u
}

// SetLegalEntityCode sets the "legal_entity_code" field.
func (_u *TenantUpdate) SetLegalEntityCode(v string) *TenantUpdate {
	_u.mutation.SetLegalEntityCode(v)
	return _u
}

// SetNillableLegalEntityCode sets the "legal_entity_code" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableLegalEntityCode(v *string) *TenantUpdate {
	if v != nil {
		_u.SetLegalEntityCode(*v)
	}
	return _u
}

// ClearLegalEntityCode clears the value of the "legal_entity_code" field.
func (_u *TenantUpdate) ClearLegalEntityCode() *TenantUpdate {
	_u.mutation.ClearLegalEntityCode()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *TenantUpdate) SetCurrency(v string) *TenantUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableCurrency(v *string) *TenantUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// ClearCurrency clears the value of the "currency" field.
func (_u *TenantUpdate) ClearCurrency() *TenantUpdate {
	_u.mutation.ClearCurrency()
	return _u
}

// SetServiceTier sets the "service_tier" field.
func (_u *TenantUpdate) SetServiceTier(v string) *TenantUpdate {
	_u.mutation.SetServiceTier(v)
	return _u
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableServiceTier(v *string) *TenantUpdate {
	if v != nil {
		_u.SetServiceTier(*v)
	}
	return _u
}

// ClearServiceTier clears the value of the "service_tier" field.
func (_u *TenantUpdate) ClearServiceTier() *TenantUpdate {
	_u.mutation.ClearServiceTier()
	return _u
}

// SetOwnerContact sets the "owner_contact" field.
func (_u *TenantUpdate) SetOwnerContact(v string) *TenantUpdate {
	_u.mutation.SetOwnerContact(v)
	return _u
}

// SetNillableOwnerContact sets the "owner_contact" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableOwnerContact(v *string) *TenantUpdate {
	if v != nil {
		_u.SetOwnerContact(*v)
	}
	return _u
}

// ClearOwnerContact clears the value of the "owner_contact" field.
func (_u *TenantUpdate) ClearOwnerContact() *TenantUpdate {
	_u.mutation.ClearOwnerContact()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TenantUpdate) SetTimezone(v string) *TenantUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableTimezone(v *string) *TenantUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TenantUpdate) SetCreatedAt(v time.Time) *TenantUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableCreatedAt(v *time.Time) *TenantUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdate) SetUpdatedAt(v time.Time) *TenantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *TenantUpdate) AddUserIDs(ids ...int) *TenantUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *TenantUpdate) AddUsers(v ...*User) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddMspCustomerAllocationIDs adds the "msp_customer_allocations" edge to the MSPAllocation entity by IDs.
func (_u *TenantUpdate) AddMspCustomerAllocationIDs(ids ...int) *TenantUpdate {
	_u.mutation.AddMspCustomerAllocationIDs(ids...)
	return _u
}

// AddMspCustomerAllocations adds the "msp_customer_allocations" edges to the MSPAllocation entity.
func (_u *TenantUpdate) AddMspCustomerAllocations(v ...*MSPAllocation) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMspCustomerAllocationIDs(ids...)
}

// AddMspProviderAllocationIDs adds the "msp_provider_allocations" edge to the MSPAllocation entity by IDs.
func (_u *TenantUpdate) AddMspProviderAllocationIDs(ids ...int) *TenantUpdate {
	_u.mutation.AddMspProviderAllocationIDs(ids...)
	return _u
}

// AddMspProviderAllocations adds the "msp_provider_allocations" edges to the MSPAllocation entity.
func (_u *TenantUpdate) AddMspProviderAllocations(v ...*MSPAllocation) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMspProviderAllocationIDs(ids...)
}

// AddMembershipIDs adds the "memberships" edge to the UserTenantMembership entity by IDs.
func (_u *TenantUpdate) AddMembershipIDs(ids ...int) *TenantUpdate {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the UserTenantMembership entity.
func (_u *TenantUpdate) AddMemberships(v ...*UserTenantMembership) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddMembershipOrgIDs adds the "membership_orgs" edge to the UserTenantMembershipOrg entity by IDs.
func (_u *TenantUpdate) AddMembershipOrgIDs(ids ...int) *TenantUpdate {
	_u.mutation.AddMembershipOrgIDs(ids...)
	return _u
}

// AddMembershipOrgs adds the "membership_orgs" edges to the UserTenantMembershipOrg entity.
func (_u *TenantUpdate) AddMembershipOrgs(v ...*UserTenantMembershipOrg) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipOrgIDs(ids...)
}

// AddBootstrapTokenIDs adds the "bootstrap_tokens" edge to the BootstrapToken entity by IDs.
func (_u *TenantUpdate) AddBootstrapTokenIDs(ids ...int) *TenantUpdate {
	_u.mutation.AddBootstrapTokenIDs(ids...)
	return _u
}

// AddBootstrapTokens adds the "bootstrap_tokens" edges to the BootstrapToken entity.
func (_u *TenantUpdate) AddBootstrapTokens(v ...*BootstrapToken) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBootstrapTokenIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdate) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *TenantUpdate) ClearUsers() *TenantUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *TenantUpdate) RemoveUserIDs(ids ...int) *TenantUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *TenantUpdate) RemoveUsers(v ...*User) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearMspCustomerAllocations clears all "msp_customer_allocations" edges to the MSPAllocation entity.
func (_u *TenantUpdate) ClearMspCustomerAllocations() *TenantUpdate {
	_u.mutation.ClearMspCustomerAllocations()
	return _u
}

// RemoveMspCustomerAllocationIDs removes the "msp_customer_allocations" edge to MSPAllocation entities by IDs.
func (_u *TenantUpdate) RemoveMspCustomerAllocationIDs(ids ...int) *TenantUpdate {
	_u.mutation.RemoveMspCustomerAllocationIDs(ids...)
	return _u
}

// RemoveMspCustomerAllocations removes "msp_customer_allocations" edges to MSPAllocation entities.
func (_u *TenantUpdate) RemoveMspCustomerAllocations(v ...*MSPAllocation) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMspCustomerAllocationIDs(ids...)
}

// ClearMspProviderAllocations clears all "msp_provider_allocations" edges to the MSPAllocation entity.
func (_u *TenantUpdate) ClearMspProviderAllocations() *TenantUpdate {
	_u.mutation.ClearMspProviderAllocations()
	return _u
}

// RemoveMspProviderAllocationIDs removes the "msp_provider_allocations" edge to MSPAllocation entities by IDs.
func (_u *TenantUpdate) RemoveMspProviderAllocationIDs(ids ...int) *TenantUpdate {
	_u.mutation.RemoveMspProviderAllocationIDs(ids...)
	return _u
}

// RemoveMspProviderAllocations removes "msp_provider_allocations" edges to MSPAllocation entities.
func (_u *TenantUpdate) RemoveMspProviderAllocations(v ...*MSPAllocation) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMspProviderAllocationIDs(ids...)
}

// ClearMemberships clears all "memberships" edges to the UserTenantMembership entity.
func (_u *TenantUpdate) ClearMemberships() *TenantUpdate {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to UserTenantMembership entities by IDs.
func (_u *TenantUpdate) RemoveMembershipIDs(ids ...int) *TenantUpdate {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to UserTenantMembership entities.
func (_u *TenantUpdate) RemoveMemberships(v ...*UserTenantMembership) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearMembershipOrgs clears all "membership_orgs" edges to the UserTenantMembershipOrg entity.
func (_u *TenantUpdate) ClearMembershipOrgs() *TenantUpdate {
	_u.mutation.ClearMembershipOrgs()
	return _u
}

// RemoveMembershipOrgIDs removes the "membership_orgs" edge to UserTenantMembershipOrg entities by IDs.
func (_u *TenantUpdate) RemoveMembershipOrgIDs(ids ...int) *TenantUpdate {
	_u.mutation.RemoveMembershipOrgIDs(ids...)
	return _u
}

// RemoveMembershipOrgs removes "membership_orgs" edges to UserTenantMembershipOrg entities.
func (_u *TenantUpdate) RemoveMembershipOrgs(v ...*UserTenantMembershipOrg) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipOrgIDs(ids...)
}

// ClearBootstrapTokens clears all "bootstrap_tokens" edges to the BootstrapToken entity.
func (_u *TenantUpdate) ClearBootstrapTokens() *TenantUpdate {
	_u.mutation.ClearBootstrapTokens()
	return _u
}

// RemoveBootstrapTokenIDs removes the "bootstrap_tokens" edge to BootstrapToken entities by IDs.
func (_u *TenantUpdate) RemoveBootstrapTokenIDs(ids ...int) *TenantUpdate {
	_u.mutation.RemoveBootstrapTokenIDs(ids...)
	return _u
}

// RemoveBootstrapTokens removes "bootstrap_tokens" edges to BootstrapToken entities.
func (_u *TenantUpdate) RemoveBootstrapTokens(v ...*BootstrapToken) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBootstrapTokenIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := tenant.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Tenant.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := tenant.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Tenant.type": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tenant.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(tenant.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(tenant.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentTenantID(); ok {
		_spec.SetField(tenant.FieldParentTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentTenantID(); ok {
		_spec.AddField(tenant.FieldParentTenantID, field.TypeInt, value)
	}
	if _u.mutation.ParentTenantIDCleared() {
		_spec.ClearField(tenant.FieldParentTenantID, field.TypeInt)
	}
	if value, ok := _u.mutation.MspProviderID(); ok {
		_spec.SetField(tenant.FieldMspProviderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMspProviderID(); ok {
		_spec.AddField(tenant.FieldMspProviderID, field.TypeInt, value)
	}
	if _u.mutation.MspProviderIDCleared() {
		_spec.ClearField(tenant.FieldMspProviderID, field.TypeInt)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(tenant.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(tenant.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PlanCode(); ok {
		_spec.SetField(tenant.FieldPlanCode, field.TypeString, value)
	}
	if _u.mutation.PlanCodeCleared() {
		_spec.ClearField(tenant.FieldPlanCode, field.TypeString)
	}
	if value, ok := _u.mutation.BillingEnabled(); ok {
		_spec.SetField(tenant.FieldBillingEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CostCenterCode(); ok {
		_spec.SetField(tenant.FieldCostCenterCode, field.TypeString, value)
	}
	if _u.mutation.CostCenterCodeCleared() {
		_spec.ClearField(tenant.FieldCostCenterCode, field.TypeString)
	}
	if value, ok := _u.mutation.LegalEntityCode(); ok {
		_spec.SetField(tenant.FieldLegalEntityCode, field.TypeString, value)
	}
	if _u.mutation.LegalEntityCodeCleared() {
		_spec.ClearField(tenant.FieldLegalEntityCode, field.TypeString)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(tenant.FieldCurrency, field.TypeString, value)
	}
	if _u.mutation.CurrencyCleared() {
		_spec.ClearField(tenant.FieldCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.ServiceTier(); ok {
		_spec.SetField(tenant.FieldServiceTier, field.TypeString, value)
	}
	if _u.mutation.ServiceTierCleared() {
		_spec.ClearField(tenant.FieldServiceTier, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerContact(); ok {
		_spec.SetField(tenant.FieldOwnerContact, field.TypeString, value)
	}
	if _u.mutation.OwnerContactCleared() {
		_spec.ClearField(tenant.FieldOwnerContact, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(tenant.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tenant.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MspCustomerAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspCustomerAllocationsTable,
			Columns: []string{tenant.MspCustomerAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMspCustomerAllocationsIDs(); len(nodes) > 0 && !_u.mutation.MspCustomerAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspCustomerAllocationsTable,
			Columns: []string{tenant.MspCustomerAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MspCustomerAllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspCustomerAllocationsTable,
			Columns: []string{tenant.MspCustomerAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MspProviderAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspProviderAllocationsTable,
			Columns: []string{tenant.MspProviderAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMspProviderAllocationsIDs(); len(nodes) > 0 && !_u.mutation.MspProviderAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspProviderAllocationsTable,
			Columns: []string{tenant.MspProviderAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MspProviderAllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspProviderAllocationsTable,
			Columns: []string{tenant.MspProviderAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembership.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembership.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembership.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipOrgsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipOrgsTable,
			Columns: []string{tenant.MembershipOrgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembershiporg.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipOrgsIDs(); len(nodes) > 0 && !_u.mutation.MembershipOrgsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipOrgsTable,
			Columns: []string{tenant.MembershipOrgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembershiporg.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipOrgsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipOrgsTable,
			Columns: []string{tenant.MembershipOrgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembershiporg.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BootstrapTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BootstrapTokensTable,
			Columns: []string{tenant.BootstrapTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bootstraptoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBootstrapTokensIDs(); len(nodes) > 0 && !_u.mutation.BootstrapTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BootstrapTokensTable,
			Columns: []string{tenant.BootstrapTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bootstraptoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BootstrapTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BootstrapTokensTable,
			Columns: []string{tenant.BootstrapTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bootstraptoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetName sets the "name" field.
func (_u *TenantUpdateOne) SetName(v string) *TenantUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *TenantUpdateOne) SetCode(v string) *TenantUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableCode(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdateOne) SetDomain(v string) *TenantUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableDomain(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *TenantUpdateOne) ClearDomain() *TenantUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// SetType sets the "type" field.
func (_u *TenantUpdateOne) SetType(v tenant.Type) *TenantUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableType(v *tenant.Type) *TenantUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdateOne) SetStatus(v string) *TenantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableStatus(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetParentTenantID sets the "parent_tenant_id" field.
func (_u *TenantUpdateOne) SetParentTenantID(v int) *TenantUpdateOne {
	_u.mutation.ResetParentTenantID()
	_u.mutation.SetParentTenantID(v)
	return _u
}

// SetNillableParentTenantID sets the "parent_tenant_id" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableParentTenantID(v *int) *TenantUpdateOne {
	if v != nil {
		_u.SetParentTenantID(*v)
	}
	return _u
}

// AddParentTenantID adds value to the "parent_tenant_id" field.
func (_u *TenantUpdateOne) AddParentTenantID(v int) *TenantUpdateOne {
	_u.mutation.AddParentTenantID(v)
	return _u
}

// ClearParentTenantID clears the value of the "parent_tenant_id" field.
func (_u *TenantUpdateOne) ClearParentTenantID() *TenantUpdateOne {
	_u.mutation.ClearParentTenantID()
	return _u
}

// SetMspProviderID sets the "msp_provider_id" field.
func (_u *TenantUpdateOne) SetMspProviderID(v int) *TenantUpdateOne {
	_u.mutation.ResetMspProviderID()
	_u.mutation.SetMspProviderID(v)
	return _u
}

// SetNillableMspProviderID sets the "msp_provider_id" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableMspProviderID(v *int) *TenantUpdateOne {
	if v != nil {
		_u.SetMspProviderID(*v)
	}
	return _u
}

// AddMspProviderID adds value to the "msp_provider_id" field.
func (_u *TenantUpdateOne) AddMspProviderID(v int) *TenantUpdateOne {
	_u.mutation.AddMspProviderID(v)
	return _u
}

// ClearMspProviderID clears the value of the "msp_provider_id" field.
func (_u *TenantUpdateOne) ClearMspProviderID() *TenantUpdateOne {
	_u.mutation.ClearMspProviderID()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TenantUpdateOne) SetExpiresAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableExpiresAt(v *time.Time) *TenantUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *TenantUpdateOne) ClearExpiresAt() *TenantUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetPlanCode sets the "plan_code" field.
func (_u *TenantUpdateOne) SetPlanCode(v string) *TenantUpdateOne {
	_u.mutation.SetPlanCode(v)
	return _u
}

// SetNillablePlanCode sets the "plan_code" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillablePlanCode(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetPlanCode(*v)
	}
	return _u
}

// ClearPlanCode clears the value of the "plan_code" field.
func (_u *TenantUpdateOne) ClearPlanCode() *TenantUpdateOne {
	_u.mutation.ClearPlanCode()
	return _u
}

// SetBillingEnabled sets the "billing_enabled" field.
func (_u *TenantUpdateOne) SetBillingEnabled(v bool) *TenantUpdateOne {
	_u.mutation.SetBillingEnabled(v)
	return _u
}

// SetNillableBillingEnabled sets the "billing_enabled" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableBillingEnabled(v *bool) *TenantUpdateOne {
	if v != nil {
		_u.SetBillingEnabled(*v)
	}
	return _u
}

// SetCostCenterCode sets the "cost_center_code" field.
func (_u *TenantUpdateOne) SetCostCenterCode(v string) *TenantUpdateOne {
	_u.mutation.SetCostCenterCode(v)
	return _u
}

// SetNillableCostCenterCode sets the "cost_center_code" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableCostCenterCode(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetCostCenterCode(*v)
	}
	return _u
}

// ClearCostCenterCode clears the value of the "cost_center_code" field.
func (_u *TenantUpdateOne) ClearCostCenterCode() *TenantUpdateOne {
	_u.mutation.ClearCostCenterCode()
	return _u
}

// SetLegalEntityCode sets the "legal_entity_code" field.
func (_u *TenantUpdateOne) SetLegalEntityCode(v string) *TenantUpdateOne {
	_u.mutation.SetLegalEntityCode(v)
	return _u
}

// SetNillableLegalEntityCode sets the "legal_entity_code" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableLegalEntityCode(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetLegalEntityCode(*v)
	}
	return _u
}

// ClearLegalEntityCode clears the value of the "legal_entity_code" field.
func (_u *TenantUpdateOne) ClearLegalEntityCode() *TenantUpdateOne {
	_u.mutation.ClearLegalEntityCode()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *TenantUpdateOne) SetCurrency(v string) *TenantUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableCurrency(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// ClearCurrency clears the value of the "currency" field.
func (_u *TenantUpdateOne) ClearCurrency() *TenantUpdateOne {
	_u.mutation.ClearCurrency()
	return _u
}

// SetServiceTier sets the "service_tier" field.
func (_u *TenantUpdateOne) SetServiceTier(v string) *TenantUpdateOne {
	_u.mutation.SetServiceTier(v)
	return _u
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableServiceTier(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetServiceTier(*v)
	}
	return _u
}

// ClearServiceTier clears the value of the "service_tier" field.
func (_u *TenantUpdateOne) ClearServiceTier() *TenantUpdateOne {
	_u.mutation.ClearServiceTier()
	return _u
}

// SetOwnerContact sets the "owner_contact" field.
func (_u *TenantUpdateOne) SetOwnerContact(v string) *TenantUpdateOne {
	_u.mutation.SetOwnerContact(v)
	return _u
}

// SetNillableOwnerContact sets the "owner_contact" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableOwnerContact(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetOwnerContact(*v)
	}
	return _u
}

// ClearOwnerContact clears the value of the "owner_contact" field.
func (_u *TenantUpdateOne) ClearOwnerContact() *TenantUpdateOne {
	_u.mutation.ClearOwnerContact()
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TenantUpdateOne) SetTimezone(v string) *TenantUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableTimezone(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TenantUpdateOne) SetCreatedAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableCreatedAt(v *time.Time) *TenantUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdateOne) SetUpdatedAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *TenantUpdateOne) AddUserIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *TenantUpdateOne) AddUsers(v ...*User) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddMspCustomerAllocationIDs adds the "msp_customer_allocations" edge to the MSPAllocation entity by IDs.
func (_u *TenantUpdateOne) AddMspCustomerAllocationIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.AddMspCustomerAllocationIDs(ids...)
	return _u
}

// AddMspCustomerAllocations adds the "msp_customer_allocations" edges to the MSPAllocation entity.
func (_u *TenantUpdateOne) AddMspCustomerAllocations(v ...*MSPAllocation) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMspCustomerAllocationIDs(ids...)
}

// AddMspProviderAllocationIDs adds the "msp_provider_allocations" edge to the MSPAllocation entity by IDs.
func (_u *TenantUpdateOne) AddMspProviderAllocationIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.AddMspProviderAllocationIDs(ids...)
	return _u
}

// AddMspProviderAllocations adds the "msp_provider_allocations" edges to the MSPAllocation entity.
func (_u *TenantUpdateOne) AddMspProviderAllocations(v ...*MSPAllocation) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMspProviderAllocationIDs(ids...)
}

// AddMembershipIDs adds the "memberships" edge to the UserTenantMembership entity by IDs.
func (_u *TenantUpdateOne) AddMembershipIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the UserTenantMembership entity.
func (_u *TenantUpdateOne) AddMemberships(v ...*UserTenantMembership) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// AddMembershipOrgIDs adds the "membership_orgs" edge to the UserTenantMembershipOrg entity by IDs.
func (_u *TenantUpdateOne) AddMembershipOrgIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.AddMembershipOrgIDs(ids...)
	return _u
}

// AddMembershipOrgs adds the "membership_orgs" edges to the UserTenantMembershipOrg entity.
func (_u *TenantUpdateOne) AddMembershipOrgs(v ...*UserTenantMembershipOrg) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipOrgIDs(ids...)
}

// AddBootstrapTokenIDs adds the "bootstrap_tokens" edge to the BootstrapToken entity by IDs.
func (_u *TenantUpdateOne) AddBootstrapTokenIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.AddBootstrapTokenIDs(ids...)
	return _u
}

// AddBootstrapTokens adds the "bootstrap_tokens" edges to the BootstrapToken entity.
func (_u *TenantUpdateOne) AddBootstrapTokens(v ...*BootstrapToken) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBootstrapTokenIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdateOne) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *TenantUpdateOne) ClearUsers() *TenantUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *TenantUpdateOne) RemoveUserIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *TenantUpdateOne) RemoveUsers(v ...*User) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearMspCustomerAllocations clears all "msp_customer_allocations" edges to the MSPAllocation entity.
func (_u *TenantUpdateOne) ClearMspCustomerAllocations() *TenantUpdateOne {
	_u.mutation.ClearMspCustomerAllocations()
	return _u
}

// RemoveMspCustomerAllocationIDs removes the "msp_customer_allocations" edge to MSPAllocation entities by IDs.
func (_u *TenantUpdateOne) RemoveMspCustomerAllocationIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.RemoveMspCustomerAllocationIDs(ids...)
	return _u
}

// RemoveMspCustomerAllocations removes "msp_customer_allocations" edges to MSPAllocation entities.
func (_u *TenantUpdateOne) RemoveMspCustomerAllocations(v ...*MSPAllocation) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMspCustomerAllocationIDs(ids...)
}

// ClearMspProviderAllocations clears all "msp_provider_allocations" edges to the MSPAllocation entity.
func (_u *TenantUpdateOne) ClearMspProviderAllocations() *TenantUpdateOne {
	_u.mutation.ClearMspProviderAllocations()
	return _u
}

// RemoveMspProviderAllocationIDs removes the "msp_provider_allocations" edge to MSPAllocation entities by IDs.
func (_u *TenantUpdateOne) RemoveMspProviderAllocationIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.RemoveMspProviderAllocationIDs(ids...)
	return _u
}

// RemoveMspProviderAllocations removes "msp_provider_allocations" edges to MSPAllocation entities.
func (_u *TenantUpdateOne) RemoveMspProviderAllocations(v ...*MSPAllocation) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMspProviderAllocationIDs(ids...)
}

// ClearMemberships clears all "memberships" edges to the UserTenantMembership entity.
func (_u *TenantUpdateOne) ClearMemberships() *TenantUpdateOne {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to UserTenantMembership entities by IDs.
func (_u *TenantUpdateOne) RemoveMembershipIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to UserTenantMembership entities.
func (_u *TenantUpdateOne) RemoveMemberships(v ...*UserTenantMembership) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// ClearMembershipOrgs clears all "membership_orgs" edges to the UserTenantMembershipOrg entity.
func (_u *TenantUpdateOne) ClearMembershipOrgs() *TenantUpdateOne {
	_u.mutation.ClearMembershipOrgs()
	return _u
}

// RemoveMembershipOrgIDs removes the "membership_orgs" edge to UserTenantMembershipOrg entities by IDs.
func (_u *TenantUpdateOne) RemoveMembershipOrgIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.RemoveMembershipOrgIDs(ids...)
	return _u
}

// RemoveMembershipOrgs removes "membership_orgs" edges to UserTenantMembershipOrg entities.
func (_u *TenantUpdateOne) RemoveMembershipOrgs(v ...*UserTenantMembershipOrg) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipOrgIDs(ids...)
}

// ClearBootstrapTokens clears all "bootstrap_tokens" edges to the BootstrapToken entity.
func (_u *TenantUpdateOne) ClearBootstrapTokens() *TenantUpdateOne {
	_u.mutation.ClearBootstrapTokens()
	return _u
}

// RemoveBootstrapTokenIDs removes the "bootstrap_tokens" edge to BootstrapToken entities by IDs.
func (_u *TenantUpdateOne) RemoveBootstrapTokenIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.RemoveBootstrapTokenIDs(ids...)
	return _u
}

// RemoveBootstrapTokens removes "bootstrap_tokens" edges to BootstrapToken entities.
func (_u *TenantUpdateOne) RemoveBootstrapTokens(v ...*BootstrapToken) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBootstrapTokenIDs(ids...)
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tenant entity.
func (_u *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := tenant.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Tenant.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := tenant.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Tenant.type": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(tenant.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(tenant.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(tenant.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ParentTenantID(); ok {
		_spec.SetField(tenant.FieldParentTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentTenantID(); ok {
		_spec.AddField(tenant.FieldParentTenantID, field.TypeInt, value)
	}
	if _u.mutation.ParentTenantIDCleared() {
		_spec.ClearField(tenant.FieldParentTenantID, field.TypeInt)
	}
	if value, ok := _u.mutation.MspProviderID(); ok {
		_spec.SetField(tenant.FieldMspProviderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMspProviderID(); ok {
		_spec.AddField(tenant.FieldMspProviderID, field.TypeInt, value)
	}
	if _u.mutation.MspProviderIDCleared() {
		_spec.ClearField(tenant.FieldMspProviderID, field.TypeInt)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(tenant.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(tenant.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PlanCode(); ok {
		_spec.SetField(tenant.FieldPlanCode, field.TypeString, value)
	}
	if _u.mutation.PlanCodeCleared() {
		_spec.ClearField(tenant.FieldPlanCode, field.TypeString)
	}
	if value, ok := _u.mutation.BillingEnabled(); ok {
		_spec.SetField(tenant.FieldBillingEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CostCenterCode(); ok {
		_spec.SetField(tenant.FieldCostCenterCode, field.TypeString, value)
	}
	if _u.mutation.CostCenterCodeCleared() {
		_spec.ClearField(tenant.FieldCostCenterCode, field.TypeString)
	}
	if value, ok := _u.mutation.LegalEntityCode(); ok {
		_spec.SetField(tenant.FieldLegalEntityCode, field.TypeString, value)
	}
	if _u.mutation.LegalEntityCodeCleared() {
		_spec.ClearField(tenant.FieldLegalEntityCode, field.TypeString)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(tenant.FieldCurrency, field.TypeString, value)
	}
	if _u.mutation.CurrencyCleared() {
		_spec.ClearField(tenant.FieldCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.ServiceTier(); ok {
		_spec.SetField(tenant.FieldServiceTier, field.TypeString, value)
	}
	if _u.mutation.ServiceTierCleared() {
		_spec.ClearField(tenant.FieldServiceTier, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerContact(); ok {
		_spec.SetField(tenant.FieldOwnerContact, field.TypeString, value)
	}
	if _u.mutation.OwnerContactCleared() {
		_spec.ClearField(tenant.FieldOwnerContact, field.TypeString)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(tenant.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tenant.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MspCustomerAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspCustomerAllocationsTable,
			Columns: []string{tenant.MspCustomerAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMspCustomerAllocationsIDs(); len(nodes) > 0 && !_u.mutation.MspCustomerAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspCustomerAllocationsTable,
			Columns: []string{tenant.MspCustomerAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MspCustomerAllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspCustomerAllocationsTable,
			Columns: []string{tenant.MspCustomerAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MspProviderAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspProviderAllocationsTable,
			Columns: []string{tenant.MspProviderAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMspProviderAllocationsIDs(); len(nodes) > 0 && !_u.mutation.MspProviderAllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspProviderAllocationsTable,
			Columns: []string{tenant.MspProviderAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MspProviderAllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspProviderAllocationsTable,
			Columns: []string{tenant.MspProviderAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembership.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembership.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembership.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipOrgsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipOrgsTable,
			Columns: []string{tenant.MembershipOrgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembershiporg.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipOrgsIDs(); len(nodes) > 0 && !_u.mutation.MembershipOrgsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipOrgsTable,
			Columns: []string{tenant.MembershipOrgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembershiporg.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipOrgsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipOrgsTable,
			Columns: []string{tenant.MembershipOrgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembershiporg.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BootstrapTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BootstrapTokensTable,
			Columns: []string{tenant.BootstrapTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bootstraptoken.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBootstrapTokensIDs(); len(nodes) > 0 && !_u.mutation.BootstrapTokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BootstrapTokensTable,
			Columns: []string{tenant.BootstrapTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bootstraptoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BootstrapTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BootstrapTokensTable,
			Columns: []string{tenant.BootstrapTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bootstraptoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tenant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
