// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/bootstraptoken"
	"itsm-backend/ent/mspallocation"
	"itsm-backend/ent/tenant"
	"itsm-backend/ent/user"
	"itsm-backend/ent/usertenantmembership"
	"itsm-backend/ent/usertenantmembershiporg"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantCreate is the builder for creating a Tenant entity.
type TenantCreate struct {
	config
	mutation *TenantMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TenantCreate) SetName(v string) *TenantCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *TenantCreate) SetCode(v string) *TenantCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetDomain sets the "domain" field.
func (_c *TenantCreate) SetDomain(v string) *TenantCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_c *TenantCreate) SetNillableDomain(v *string) *TenantCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *TenantCreate) SetType(v tenant.Type) *TenantCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *TenantCreate) SetNillableType(v *tenant.Type) *TenantCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TenantCreate) SetStatus(v string) *TenantCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TenantCreate) SetNillableStatus(v *string) *TenantCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetParentTenantID sets the "parent_tenant_id" field.
func (_c *TenantCreate) SetParentTenantID(v int) *TenantCreate {
	_c.mutation.SetParentTenantID(v)
	return _c
}

// SetNillableParentTenantID sets the "parent_tenant_id" field if the given value is not nil.
func (_c *TenantCreate) SetNillableParentTenantID(v *int) *TenantCreate {
	if v != nil {
		_c.SetParentTenantID(*v)
	}
	return _c
}

// SetMspProviderID sets the "msp_provider_id" field.
func (_c *TenantCreate) SetMspProviderID(v int) *TenantCreate {
	_c.mutation.SetMspProviderID(v)
	return _c
}

// SetNillableMspProviderID sets the "msp_provider_id" field if the given value is not nil.
func (_c *TenantCreate) SetNillableMspProviderID(v *int) *TenantCreate {
	if v != nil {
		_c.SetMspProviderID(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *TenantCreate) SetExpiresAt(v time.Time) *TenantCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *TenantCreate) SetNillableExpiresAt(v *time.Time) *TenantCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetPlanCode sets the "plan_code" field.
func (_c *TenantCreate) SetPlanCode(v string) *TenantCreate {
	_c.mutation.SetPlanCode(v)
	return _c
}

// SetNillablePlanCode sets the "plan_code" field if the given value is not nil.
func (_c *TenantCreate) SetNillablePlanCode(v *string) *TenantCreate {
	if v != nil {
		_c.SetPlanCode(*v)
	}
	return _c
}

// SetBillingEnabled sets the "billing_enabled" field.
func (_c *TenantCreate) SetBillingEnabled(v bool) *TenantCreate {
	_c.mutation.SetBillingEnabled(v)
	return _c
}

// SetNillableBillingEnabled sets the "billing_enabled" field if the given value is not nil.
func (_c *TenantCreate) SetNillableBillingEnabled(v *bool) *TenantCreate {
	if v != nil {
		_c.SetBillingEnabled(*v)
	}
	return _c
}

// SetCostCenterCode sets the "cost_center_code" field.
func (_c *TenantCreate) SetCostCenterCode(v string) *TenantCreate {
	_c.mutation.SetCostCenterCode(v)
	return _c
}

// SetNillableCostCenterCode sets the "cost_center_code" field if the given value is not nil.
func (_c *TenantCreate) SetNillableCostCenterCode(v *string) *TenantCreate {
	if v != nil {
		_c.SetCostCenterCode(*v)
	}
	return _c
}

// SetLegalEntityCode sets the "legal_entity_code" field.
func (_c *TenantCreate) SetLegalEntityCode(v string) *TenantCreate {
	_c.mutation.SetLegalEntityCode(v)
	return _c
}

// SetNillableLegalEntityCode sets the "legal_entity_code" field if the given value is not nil.
func (_c *TenantCreate) SetNillableLegalEntityCode(v *string) *TenantCreate {
	if v != nil {
		_c.SetLegalEntityCode(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *TenantCreate) SetCurrency(v string) *TenantCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *TenantCreate) SetNillableCurrency(v *string) *TenantCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetServiceTier sets the "service_tier" field.
func (_c *TenantCreate) SetServiceTier(v string) *TenantCreate {
	_c.mutation.SetServiceTier(v)
	return _c
}

// SetNillableServiceTier sets the "service_tier" field if the given value is not nil.
func (_c *TenantCreate) SetNillableServiceTier(v *string) *TenantCreate {
	if v != nil {
		_c.SetServiceTier(*v)
	}
	return _c
}

// SetOwnerContact sets the "owner_contact" field.
func (_c *TenantCreate) SetOwnerContact(v string) *TenantCreate {
	_c.mutation.SetOwnerContact(v)
	return _c
}

// SetNillableOwnerContact sets the "owner_contact" field if the given value is not nil.
func (_c *TenantCreate) SetNillableOwnerContact(v *string) *TenantCreate {
	if v != nil {
		_c.SetOwnerContact(*v)
	}
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *TenantCreate) SetTimezone(v string) *TenantCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *TenantCreate) SetNillableTimezone(v *string) *TenantCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantCreate) SetCreatedAt(v time.Time) *TenantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantCreate) SetNillableCreatedAt(v *time.Time) *TenantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TenantCreate) SetUpdatedAt(v time.Time) *TenantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TenantCreate) SetNillableUpdatedAt(v *time.Time) *TenantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_c *TenantCreate) AddUserIDs(ids ...int) *TenantCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUsers adds the "users" edges to the User entity.
func (_c *TenantCreate) AddUsers(v ...*User) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// AddMspCustomerAllocationIDs adds the "msp_customer_allocations" edge to the MSPAllocation entity by IDs.
func (_c *TenantCreate) AddMspCustomerAllocationIDs(ids ...int) *TenantCreate {
	_c.mutation.AddMspCustomerAllocationIDs(ids...)
	return _c
}

// AddMspCustomerAllocations adds the "msp_customer_allocations" edges to the MSPAllocation entity.
func (_c *TenantCreate) AddMspCustomerAllocations(v ...*MSPAllocation) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMspCustomerAllocationIDs(ids...)
}

// AddMembershipIDs adds the "memberships" edge to the UserTenantMembership entity by IDs.
func (_c *TenantCreate) AddMembershipIDs(ids ...int) *TenantCreate {
	_c.mutation.AddMembershipIDs(ids...)
	return _c
}

// AddMemberships adds the "memberships" edges to the UserTenantMembership entity.
func (_c *TenantCreate) AddMemberships(v ...*UserTenantMembership) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMembershipIDs(ids...)
}

// AddMembershipOrgIDs adds the "membership_orgs" edge to the UserTenantMembershipOrg entity by IDs.
func (_c *TenantCreate) AddMembershipOrgIDs(ids ...int) *TenantCreate {
	_c.mutation.AddMembershipOrgIDs(ids...)
	return _c
}

// AddMembershipOrgs adds the "membership_orgs" edges to the UserTenantMembershipOrg entity.
func (_c *TenantCreate) AddMembershipOrgs(v ...*UserTenantMembershipOrg) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMembershipOrgIDs(ids...)
}

// AddBootstrapTokenIDs adds the "bootstrap_tokens" edge to the BootstrapToken entity by IDs.
func (_c *TenantCreate) AddBootstrapTokenIDs(ids ...int) *TenantCreate {
	_c.mutation.AddBootstrapTokenIDs(ids...)
	return _c
}

// AddBootstrapTokens adds the "bootstrap_tokens" edges to the BootstrapToken entity.
func (_c *TenantCreate) AddBootstrapTokens(v ...*BootstrapToken) *TenantCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBootstrapTokenIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_c *TenantCreate) Mutation() *TenantMutation {
	return _c.mutation
}

// Save creates the Tenant in the database.
func (_c *TenantCreate) Save(ctx context.Context) (*Tenant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantCreate) SaveX(ctx context.Context) *Tenant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := tenant.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := tenant.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.BillingEnabled(); !ok {
		v := tenant.DefaultBillingEnabled
		_c.mutation.SetBillingEnabled(v)
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		v := tenant.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tenant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tenant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tenant.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Tenant.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := tenant.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Tenant.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Tenant.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := tenant.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Tenant.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Tenant.status"`)}
	}
	if _, ok := _c.mutation.BillingEnabled(); !ok {
		return &ValidationError{Name: "billing_enabled", err: errors.New(`ent: missing required field "Tenant.billing_enabled"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "Tenant.timezone"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Tenant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Tenant.updated_at"`)}
	}
	return nil
}

func (_c *TenantCreate) sqlSave(ctx context.Context) (*Tenant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantCreate) createSpec() (*Tenant, *sqlgraph.CreateSpec) {
	var (
		_node = &Tenant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenant.Table, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(tenant.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(tenant.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ParentTenantID(); ok {
		_spec.SetField(tenant.FieldParentTenantID, field.TypeInt, value)
		_node.ParentTenantID = value
	}
	if value, ok := _c.mutation.MspProviderID(); ok {
		_spec.SetField(tenant.FieldMspProviderID, field.TypeInt, value)
		_node.MspProviderID = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(tenant.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.PlanCode(); ok {
		_spec.SetField(tenant.FieldPlanCode, field.TypeString, value)
		_node.PlanCode = value
	}
	if value, ok := _c.mutation.BillingEnabled(); ok {
		_spec.SetField(tenant.FieldBillingEnabled, field.TypeBool, value)
		_node.BillingEnabled = value
	}
	if value, ok := _c.mutation.CostCenterCode(); ok {
		_spec.SetField(tenant.FieldCostCenterCode, field.TypeString, value)
		_node.CostCenterCode = value
	}
	if value, ok := _c.mutation.LegalEntityCode(); ok {
		_spec.SetField(tenant.FieldLegalEntityCode, field.TypeString, value)
		_node.LegalEntityCode = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(tenant.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.ServiceTier(); ok {
		_spec.SetField(tenant.FieldServiceTier, field.TypeString, value)
		_node.ServiceTier = value
	}
	if value, ok := _c.mutation.OwnerContact(); ok {
		_spec.SetField(tenant.FieldOwnerContact, field.TypeString, value)
		_node.OwnerContact = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(tenant.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.UsersTable,
			Columns: []string{tenant.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MspCustomerAllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MspCustomerAllocationsTable,
			Columns: []string{tenant.MspCustomerAllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mspallocation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembership.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembershipOrgsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipOrgsTable,
			Columns: []string{tenant.MembershipOrgsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usertenantmembershiporg.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BootstrapTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BootstrapTokensTable,
			Columns: []string{tenant.BootstrapTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bootstraptoken.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TenantCreateBulk is the builder for creating many Tenant entities in bulk.
type TenantCreateBulk struct {
	config
	err      error
	builders []*TenantCreate
}

// Save creates the Tenant entities in the database.
func (_c *TenantCreateBulk) Save(ctx context.Context) ([]*Tenant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Tenant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantCreateBulk) SaveX(ctx context.Context) []*Tenant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
