// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"itsm-backend/ent/ticket"
	"itsm-backend/ent/tickettype"
	"itsm-backend/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Ticket is the model entity for the Ticket schema.
type Ticket struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 工单标题
	Title string `json:"title,omitempty"`
	// 工单描述
	Description string `json:"description,omitempty"`
	// 工单描述富文本 HTML（服务端净化后）
	DescriptionHTML string `json:"description_html,omitempty"`
	// 描述格式：plain/html，用于灰度与兼容旧数据
	DescriptionFormat string `json:"description_format,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
	// 工单类型
	Type string `json:"type,omitempty"`
	// 租户配置工单类型ID
	TicketTypeID int `json:"ticket_type_id,omitempty"`
	// 创建时工单类型编码快照
	TicketTypeCodeSnapshot string `json:"ticket_type_code_snapshot,omitempty"`
	// 创建时工单类型名称快照
	TicketTypeNameSnapshot string `json:"ticket_type_name_snapshot,omitempty"`
	// 动态表单值
	FormFields map[string]interface{} `json:"form_fields,omitempty"`
	// 优先级
	Priority string `json:"priority,omitempty"`
	// 工单编号
	TicketNumber string `json:"ticket_number,omitempty"`
	// 申请人ID
	RequesterID int `json:"requester_id,omitempty"`
	// 处理人ID
	AssigneeID int `json:"assignee_id,omitempty"`
	// 租户ID
	TenantID int `json:"tenant_id,omitempty"`
	// 模板ID
	TemplateID int `json:"template_id,omitempty"`
	// 分类ID
	CategoryID int `json:"category_id,omitempty"`
	// 部门ID
	DepartmentID int `json:"department_id,omitempty"`
	// 父工单ID
	ParentTicketID int `json:"parent_ticket_id,omitempty"`
	// SLA定义ID
	SLADefinitionID int `json:"sla_definition_id,omitempty"`
	// SLA响应截止时间
	SLAResponseDeadline time.Time `json:"sla_response_deadline,omitempty"`
	// SLA解决截止时间
	SLAResolutionDeadline time.Time `json:"sla_resolution_deadline,omitempty"`
	// SLA状态：active/paused
	SLAStatus string `json:"sla_status,omitempty"`
	// SLA暂停时间
	SLAPausedAt time.Time `json:"sla_paused_at,omitempty"`
	// SLA暂停原因
	SLAPauseReason string `json:"sla_pause_reason,omitempty"`
	// 首次响应时间
	FirstResponseAt time.Time `json:"first_response_at,omitempty"`
	// 解决时间
	ResolvedAt time.Time `json:"resolved_at,omitempty"`
	// 解决方案
	Resolution string `json:"resolution,omitempty"`
	// 解决方案分类
	ResolutionCategory string `json:"resolution_category,omitempty"`
	// 关闭时间
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// 评分（1-5星）
	Rating int `json:"rating,omitempty"`
	// 评分评论
	RatingComment string `json:"rating_comment,omitempty"`
	// 评分时间
	RatedAt time.Time `json:"rated_at,omitempty"`
	// 评分人ID
	RatedBy int `json:"rated_by,omitempty"`
	// 版本号（乐观锁）
	Version int `json:"version,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 是否由MSP管理
	IsManagedByMsp bool `json:"is_managed_by_msp,omitempty"`
	// MSP服务提供商ID
	MspProviderID int `json:"msp_provider_id,omitempty"`
	// MSP处理人ID
	ManagedByUserID int `json:"managed_by_user_id,omitempty"`
	// MSP工单ID(跨租户)
	MspTicketID string `json:"msp_ticket_id,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketQuery when eager-loading is set.
	Edges                      TicketEdges `json:"edges"`
	configuration_item_tickets *int
	department_tickets         *int
	problem_tickets            *int
	sla_definition_tickets     *int
	sla_policy_tickets         *int
	ticket_tag_tickets         *int
	ticket_template_tickets    *int
	selectValues               sql.SelectValues
}

// TicketEdges holds the relations/edges for other nodes in the graph.
type TicketEdges struct {
	// Comments holds the value of the comments edge.
	Comments []*TicketComment `json:"comments,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*TicketAttachment `json:"attachments,omitempty"`
	// Tags holds the value of the tags edge.
	Tags []*TicketTag `json:"tags,omitempty"`
	// 双向关联工单
	RelatedTickets []*Ticket `json:"related_tickets,omitempty"`
	// ApprovalRecords holds the value of the approval_records edge.
	ApprovalRecords []*ApprovalRecord `json:"approval_records,omitempty"`
	// Approvals holds the value of the approvals edge.
	Approvals []*TicketApproval `json:"approvals,omitempty"`
	// WorkflowRecords holds the value of the workflow_records edge.
	WorkflowRecords []*TicketWorkflowRecord `json:"workflow_records,omitempty"`
	// Notifications holds the value of the notifications edge.
	Notifications []*TicketNotification `json:"notifications,omitempty"`
	// CcUsers holds the value of the cc_users edge.
	CcUsers []*TicketCC `json:"cc_users,omitempty"`
	// SLAViolations holds the value of the sla_violations edge.
	SLAViolations []*SLAViolation `json:"sla_violations,omitempty"`
	// SLAAlertHistory holds the value of the sla_alert_history edge.
	SLAAlertHistory []*SLAAlertHistory `json:"sla_alert_history,omitempty"`
	// RootCauseAnalyses holds the value of the root_cause_analyses edge.
	RootCauseAnalyses []*RootCauseAnalysis `json:"root_cause_analyses,omitempty"`
	// FeishuSyncs holds the value of the feishu_syncs edge.
	FeishuSyncs []*FeishuTicketSync `json:"feishu_syncs,omitempty"`
	// Requester holds the value of the requester edge.
	Requester *User `json:"requester,omitempty"`
	// Assignee holds the value of the assignee edge.
	Assignee *User `json:"assignee,omitempty"`
	// Category holds the value of the category edge.
	Category []*TicketCategory `json:"category,omitempty"`
	// ConfiguredType holds the value of the configured_type edge.
	ConfiguredType *TicketType `json:"configured_type,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [17]bool
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) CommentsOrErr() ([]*TicketComment, error) {
	if e.loadedTypes[0] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) AttachmentsOrErr() ([]*TicketAttachment, error) {
	if e.loadedTypes[1] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) TagsOrErr() ([]*TicketTag, error) {
	if e.loadedTypes[2] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// RelatedTicketsOrErr returns the RelatedTickets value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) RelatedTicketsOrErr() ([]*Ticket, error) {
	if e.loadedTypes[3] {
		return e.RelatedTickets, nil
	}
	return nil, &NotLoadedError{edge: "related_tickets"}
}

// ApprovalRecordsOrErr returns the ApprovalRecords value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) ApprovalRecordsOrErr() ([]*ApprovalRecord, error) {
	if e.loadedTypes[4] {
		return e.ApprovalRecords, nil
	}
	return nil, &NotLoadedError{edge: "approval_records"}
}

// ApprovalsOrErr returns the Approvals value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) ApprovalsOrErr() ([]*TicketApproval, error) {
	if e.loadedTypes[5] {
		return e.Approvals, nil
	}
	return nil, &NotLoadedError{edge: "approvals"}
}

// WorkflowRecordsOrErr returns the WorkflowRecords value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) WorkflowRecordsOrErr() ([]*TicketWorkflowRecord, error) {
	if e.loadedTypes[6] {
		return e.WorkflowRecords, nil
	}
	return nil, &NotLoadedError{edge: "workflow_records"}
}

// NotificationsOrErr returns the Notifications value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) NotificationsOrErr() ([]*TicketNotification, error) {
	if e.loadedTypes[7] {
		return e.Notifications, nil
	}
	return nil, &NotLoadedError{edge: "notifications"}
}

// CcUsersOrErr returns the CcUsers value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) CcUsersOrErr() ([]*TicketCC, error) {
	if e.loadedTypes[8] {
		return e.CcUsers, nil
	}
	return nil, &NotLoadedError{edge: "cc_users"}
}

// SLAViolationsOrErr returns the SLAViolations value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) SLAViolationsOrErr() ([]*SLAViolation, error) {
	if e.loadedTypes[9] {
		return e.SLAViolations, nil
	}
	return nil, &NotLoadedError{edge: "sla_violations"}
}

// SLAAlertHistoryOrErr returns the SLAAlertHistory value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) SLAAlertHistoryOrErr() ([]*SLAAlertHistory, error) {
	if e.loadedTypes[10] {
		return e.SLAAlertHistory, nil
	}
	return nil, &NotLoadedError{edge: "sla_alert_history"}
}

// RootCauseAnalysesOrErr returns the RootCauseAnalyses value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) RootCauseAnalysesOrErr() ([]*RootCauseAnalysis, error) {
	if e.loadedTypes[11] {
		return e.RootCauseAnalyses, nil
	}
	return nil, &NotLoadedError{edge: "root_cause_analyses"}
}

// FeishuSyncsOrErr returns the FeishuSyncs value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) FeishuSyncsOrErr() ([]*FeishuTicketSync, error) {
	if e.loadedTypes[12] {
		return e.FeishuSyncs, nil
	}
	return nil, &NotLoadedError{edge: "feishu_syncs"}
}

// RequesterOrErr returns the Requester value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEdges) RequesterOrErr() (*User, error) {
	if e.Requester != nil {
		return e.Requester, nil
	} else if e.loadedTypes[13] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "requester"}
}

// AssigneeOrErr returns the Assignee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEdges) AssigneeOrErr() (*User, error) {
	if e.Assignee != nil {
		return e.Assignee, nil
	} else if e.loadedTypes[14] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "assignee"}
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) CategoryOrErr() ([]*TicketCategory, error) {
	if e.loadedTypes[15] {
		return e.Category, nil
	}
	return nil, &NotLoadedError{edge: "category"}
}

// ConfiguredTypeOrErr returns the ConfiguredType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketEdges) ConfiguredTypeOrErr() (*TicketType, error) {
	if e.ConfiguredType != nil {
		return e.ConfiguredType, nil
	} else if e.loadedTypes[16] {
		return nil, &NotFoundError{label: tickettype.Label}
	}
	return nil, &NotLoadedError{edge: "configured_type"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ticket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticket.FieldFormFields:
			values[i] = new([]byte)
		case ticket.FieldIsManagedByMsp:
			values[i] = new(sql.NullBool)
		case ticket.FieldID, ticket.FieldTicketTypeID, ticket.FieldRequesterID, ticket.FieldAssigneeID, ticket.FieldTenantID, ticket.FieldTemplateID, ticket.FieldCategoryID, ticket.FieldDepartmentID, ticket.FieldParentTicketID, ticket.FieldSLADefinitionID, ticket.FieldRating, ticket.FieldRatedBy, ticket.FieldVersion, ticket.FieldMspProviderID, ticket.FieldManagedByUserID:
			values[i] = new(sql.NullInt64)
		case ticket.FieldTitle, ticket.FieldDescription, ticket.FieldDescriptionHTML, ticket.FieldDescriptionFormat, ticket.FieldStatus, ticket.FieldType, ticket.FieldTicketTypeCodeSnapshot, ticket.FieldTicketTypeNameSnapshot, ticket.FieldPriority, ticket.FieldTicketNumber, ticket.FieldSLAStatus, ticket.FieldSLAPauseReason, ticket.FieldResolution, ticket.FieldResolutionCategory, ticket.FieldRatingComment, ticket.FieldMspTicketID:
			values[i] = new(sql.NullString)
		case ticket.FieldSLAResponseDeadline, ticket.FieldSLAResolutionDeadline, ticket.FieldSLAPausedAt, ticket.FieldFirstResponseAt, ticket.FieldResolvedAt, ticket.FieldClosedAt, ticket.FieldRatedAt, ticket.FieldCreatedAt, ticket.FieldUpdatedAt, ticket.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case ticket.ForeignKeys[0]: // configuration_item_tickets
			values[i] = new(sql.NullInt64)
		case ticket.ForeignKeys[1]: // department_tickets
			values[i] = new(sql.NullInt64)
		case ticket.ForeignKeys[2]: // problem_tickets
			values[i] = new(sql.NullInt64)
		case ticket.ForeignKeys[3]: // sla_definition_tickets
			values[i] = new(sql.NullInt64)
		case ticket.ForeignKeys[4]: // sla_policy_tickets
			values[i] = new(sql.NullInt64)
		case ticket.ForeignKeys[5]: // ticket_tag_tickets
			values[i] = new(sql.NullInt64)
		case ticket.ForeignKeys[6]: // ticket_template_tickets
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ticket fields.
func (_m *Ticket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticket.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ticket.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case ticket.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case ticket.FieldDescriptionHTML:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description_html", values[i])
			} else if value.Valid {
				_m.DescriptionHTML = value.String
			}
		case ticket.FieldDescriptionFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description_format", values[i])
			} else if value.Valid {
				_m.DescriptionFormat = value.String
			}
		case ticket.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case ticket.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case ticket.FieldTicketTypeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_type_id", values[i])
			} else if value.Valid {
				_m.TicketTypeID = int(value.Int64)
			}
		case ticket.FieldTicketTypeCodeSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_type_code_snapshot", values[i])
			} else if value.Valid {
				_m.TicketTypeCodeSnapshot = value.String
			}
		case ticket.FieldTicketTypeNameSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_type_name_snapshot", values[i])
			} else if value.Valid {
				_m.TicketTypeNameSnapshot = value.String
			}
		case ticket.FieldFormFields:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field form_fields", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.FormFields); err != nil {
					return fmt.Errorf("unmarshal field form_fields: %w", err)
				}
			}
		case ticket.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = value.String
			}
		case ticket.FieldTicketNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_number", values[i])
			} else if value.Valid {
				_m.TicketNumber = value.String
			}
		case ticket.FieldRequesterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field requester_id", values[i])
			} else if value.Valid {
				_m.RequesterID = int(value.Int64)
			}
		case ticket.FieldAssigneeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assignee_id", values[i])
			} else if value.Valid {
				_m.AssigneeID = int(value.Int64)
			}
		case ticket.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case ticket.FieldTemplateID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				_m.TemplateID = int(value.Int64)
			}
		case ticket.FieldCategoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value.Valid {
				_m.CategoryID = int(value.Int64)
			}
		case ticket.FieldDepartmentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field department_id", values[i])
			} else if value.Valid {
				_m.DepartmentID = int(value.Int64)
			}
		case ticket.FieldParentTicketID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_ticket_id", values[i])
			} else if value.Valid {
				_m.ParentTicketID = int(value.Int64)
			}
		case ticket.FieldSLADefinitionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sla_definition_id", values[i])
			} else if value.Valid {
				_m.SLADefinitionID = int(value.Int64)
			}
		case ticket.FieldSLAResponseDeadline:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sla_response_deadline", values[i])
			} else if value.Valid {
				_m.SLAResponseDeadline = value.Time
			}
		case ticket.FieldSLAResolutionDeadline:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sla_resolution_deadline", values[i])
			} else if value.Valid {
				_m.SLAResolutionDeadline = value.Time
			}
		case ticket.FieldSLAStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sla_status", values[i])
			} else if value.Valid {
				_m.SLAStatus = value.String
			}
		case ticket.FieldSLAPausedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sla_paused_at", values[i])
			} else if value.Valid {
				_m.SLAPausedAt = value.Time
			}
		case ticket.FieldSLAPauseReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sla_pause_reason", values[i])
			} else if value.Valid {
				_m.SLAPauseReason = value.String
			}
		case ticket.FieldFirstResponseAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_response_at", values[i])
			} else if value.Valid {
				_m.FirstResponseAt = value.Time
			}
		case ticket.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = value.Time
			}
		case ticket.FieldResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution", values[i])
			} else if value.Valid {
				_m.Resolution = value.String
			}
		case ticket.FieldResolutionCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution_category", values[i])
			} else if value.Valid {
				_m.ResolutionCategory = value.String
			}
		case ticket.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case ticket.FieldRating:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = int(value.Int64)
			}
		case ticket.FieldRatingComment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rating_comment", values[i])
			} else if value.Valid {
				_m.RatingComment = value.String
			}
		case ticket.FieldRatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field rated_at", values[i])
			} else if value.Valid {
				_m.RatedAt = value.Time
			}
		case ticket.FieldRatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rated_by", values[i])
			} else if value.Valid {
				_m.RatedBy = int(value.Int64)
			}
		case ticket.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case ticket.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ticket.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ticket.FieldIsManagedByMsp:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_managed_by_msp", values[i])
			} else if value.Valid {
				_m.IsManagedByMsp = value.Bool
			}
		case ticket.FieldMspProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field msp_provider_id", values[i])
			} else if value.Valid {
				_m.MspProviderID = int(value.Int64)
			}
		case ticket.FieldManagedByUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field managed_by_user_id", values[i])
			} else if value.Valid {
				_m.ManagedByUserID = int(value.Int64)
			}
		case ticket.FieldMspTicketID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field msp_ticket_id", values[i])
			} else if value.Valid {
				_m.MspTicketID = value.String
			}
		case ticket.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case ticket.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field configuration_item_tickets", value)
			} else if value.Valid {
				_m.configuration_item_tickets = new(int)
				*_m.configuration_item_tickets = int(value.Int64)
			}
		case ticket.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field department_tickets", value)
			} else if value.Valid {
				_m.department_tickets = new(int)
				*_m.department_tickets = int(value.Int64)
			}
		case ticket.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field problem_tickets", value)
			} else if value.Valid {
				_m.problem_tickets = new(int)
				*_m.problem_tickets = int(value.Int64)
			}
		case ticket.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field sla_definition_tickets", value)
			} else if value.Valid {
				_m.sla_definition_tickets = new(int)
				*_m.sla_definition_tickets = int(value.Int64)
			}
		case ticket.ForeignKeys[4]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field sla_policy_tickets", value)
			} else if value.Valid {
				_m.sla_policy_tickets = new(int)
				*_m.sla_policy_tickets = int(value.Int64)
			}
		case ticket.ForeignKeys[5]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field ticket_tag_tickets", value)
			} else if value.Valid {
				_m.ticket_tag_tickets = new(int)
				*_m.ticket_tag_tickets = int(value.Int64)
			}
		case ticket.ForeignKeys[6]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field ticket_template_tickets", value)
			} else if value.Valid {
				_m.ticket_template_tickets = new(int)
				*_m.ticket_template_tickets = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ticket.
// This includes values selected through modifiers, order, etc.
func (_m *Ticket) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryComments queries the "comments" edge of the Ticket entity.
func (_m *Ticket) QueryComments() *TicketCommentQuery {
	return NewTicketClient(_m.config).QueryComments(_m)
}

// QueryAttachments queries the "attachments" edge of the Ticket entity.
func (_m *Ticket) QueryAttachments() *TicketAttachmentQuery {
	return NewTicketClient(_m.config).QueryAttachments(_m)
}

// QueryTags queries the "tags" edge of the Ticket entity.
func (_m *Ticket) QueryTags() *TicketTagQuery {
	return NewTicketClient(_m.config).QueryTags(_m)
}

// QueryRelatedTickets queries the "related_tickets" edge of the Ticket entity.
func (_m *Ticket) QueryRelatedTickets() *TicketQuery {
	return NewTicketClient(_m.config).QueryRelatedTickets(_m)
}

// QueryApprovalRecords queries the "approval_records" edge of the Ticket entity.
func (_m *Ticket) QueryApprovalRecords() *ApprovalRecordQuery {
	return NewTicketClient(_m.config).QueryApprovalRecords(_m)
}

// QueryApprovals queries the "approvals" edge of the Ticket entity.
func (_m *Ticket) QueryApprovals() *TicketApprovalQuery {
	return NewTicketClient(_m.config).QueryApprovals(_m)
}

// QueryWorkflowRecords queries the "workflow_records" edge of the Ticket entity.
func (_m *Ticket) QueryWorkflowRecords() *TicketWorkflowRecordQuery {
	return NewTicketClient(_m.config).QueryWorkflowRecords(_m)
}

// QueryNotifications queries the "notifications" edge of the Ticket entity.
func (_m *Ticket) QueryNotifications() *TicketNotificationQuery {
	return NewTicketClient(_m.config).QueryNotifications(_m)
}

// QueryCcUsers queries the "cc_users" edge of the Ticket entity.
func (_m *Ticket) QueryCcUsers() *TicketCCQuery {
	return NewTicketClient(_m.config).QueryCcUsers(_m)
}

// QuerySLAViolations queries the "sla_violations" edge of the Ticket entity.
func (_m *Ticket) QuerySLAViolations() *SLAViolationQuery {
	return NewTicketClient(_m.config).QuerySLAViolations(_m)
}

// QuerySLAAlertHistory queries the "sla_alert_history" edge of the Ticket entity.
func (_m *Ticket) QuerySLAAlertHistory() *SLAAlertHistoryQuery {
	return NewTicketClient(_m.config).QuerySLAAlertHistory(_m)
}

// QueryRootCauseAnalyses queries the "root_cause_analyses" edge of the Ticket entity.
func (_m *Ticket) QueryRootCauseAnalyses() *RootCauseAnalysisQuery {
	return NewTicketClient(_m.config).QueryRootCauseAnalyses(_m)
}

// QueryFeishuSyncs queries the "feishu_syncs" edge of the Ticket entity.
func (_m *Ticket) QueryFeishuSyncs() *FeishuTicketSyncQuery {
	return NewTicketClient(_m.config).QueryFeishuSyncs(_m)
}

// QueryRequester queries the "requester" edge of the Ticket entity.
func (_m *Ticket) QueryRequester() *UserQuery {
	return NewTicketClient(_m.config).QueryRequester(_m)
}

// QueryAssignee queries the "assignee" edge of the Ticket entity.
func (_m *Ticket) QueryAssignee() *UserQuery {
	return NewTicketClient(_m.config).QueryAssignee(_m)
}

// QueryCategory queries the "category" edge of the Ticket entity.
func (_m *Ticket) QueryCategory() *TicketCategoryQuery {
	return NewTicketClient(_m.config).QueryCategory(_m)
}

// QueryConfiguredType queries the "configured_type" edge of the Ticket entity.
func (_m *Ticket) QueryConfiguredType() *TicketTypeQuery {
	return NewTicketClient(_m.config).QueryConfiguredType(_m)
}

// Update returns a builder for updating this Ticket.
// Note that you need to call Ticket.Unwrap() before calling this method if this Ticket
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ticket) Update() *TicketUpdateOne {
	return NewTicketClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ticket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ticket) Unwrap() *Ticket {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ticket is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ticket) String() string {
	var builder strings.Builder
	builder.WriteString("Ticket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("description_html=")
	builder.WriteString(_m.DescriptionHTML)
	builder.WriteString(", ")
	builder.WriteString("description_format=")
	builder.WriteString(_m.DescriptionFormat)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("ticket_type_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketTypeID))
	builder.WriteString(", ")
	builder.WriteString("ticket_type_code_snapshot=")
	builder.WriteString(_m.TicketTypeCodeSnapshot)
	builder.WriteString(", ")
	builder.WriteString("ticket_type_name_snapshot=")
	builder.WriteString(_m.TicketTypeNameSnapshot)
	builder.WriteString(", ")
	builder.WriteString("form_fields=")
	builder.WriteString(fmt.Sprintf("%v", _m.FormFields))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(_m.Priority)
	builder.WriteString(", ")
	builder.WriteString("ticket_number=")
	builder.WriteString(_m.TicketNumber)
	builder.WriteString(", ")
	builder.WriteString("requester_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequesterID))
	builder.WriteString(", ")
	builder.WriteString("assignee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AssigneeID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("template_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateID))
	builder.WriteString(", ")
	builder.WriteString("category_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CategoryID))
	builder.WriteString(", ")
	builder.WriteString("department_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DepartmentID))
	builder.WriteString(", ")
	builder.WriteString("parent_ticket_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentTicketID))
	builder.WriteString(", ")
	builder.WriteString("sla_definition_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SLADefinitionID))
	builder.WriteString(", ")
	builder.WriteString("sla_response_deadline=")
	builder.WriteString(_m.SLAResponseDeadline.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sla_resolution_deadline=")
	builder.WriteString(_m.SLAResolutionDeadline.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sla_status=")
	builder.WriteString(_m.SLAStatus)
	builder.WriteString(", ")
	builder.WriteString("sla_paused_at=")
	builder.WriteString(_m.SLAPausedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sla_pause_reason=")
	builder.WriteString(_m.SLAPauseReason)
	builder.WriteString(", ")
	builder.WriteString("first_response_at=")
	builder.WriteString(_m.FirstResponseAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("resolved_at=")
	builder.WriteString(_m.ResolvedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("resolution=")
	builder.WriteString(_m.Resolution)
	builder.WriteString(", ")
	builder.WriteString("resolution_category=")
	builder.WriteString(_m.ResolutionCategory)
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rating))
	builder.WriteString(", ")
	builder.WriteString("rating_comment=")
	builder.WriteString(_m.RatingComment)
	builder.WriteString(", ")
	builder.WriteString("rated_at=")
	builder.WriteString(_m.RatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("rated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.RatedBy))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_managed_by_msp=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsManagedByMsp))
	builder.WriteString(", ")
	builder.WriteString("msp_provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MspProviderID))
	builder.WriteString(", ")
	builder.WriteString("managed_by_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManagedByUserID))
	builder.WriteString(", ")
	builder.WriteString("msp_ticket_id=")
	builder.WriteString(_m.MspTicketID)
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Tickets is a parsable slice of Ticket.
type Tickets []*Ticket
