// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/conversation"
	"itsm-backend/ent/toolinvocation"
	"itsm-backend/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ToolInvocationCreate is the builder for creating a ToolInvocation entity.
type ToolInvocationCreate struct {
	config
	mutation *ToolInvocationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ToolInvocationCreate) SetCreatedAt(v time.Time) *ToolInvocationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableCreatedAt(v *time.Time) *ToolInvocationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ToolInvocationCreate) SetTenantID(v int) *ToolInvocationCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *ToolInvocationCreate) SetConversationID(v int) *ToolInvocationCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableConversationID(v *int) *ToolInvocationCreate {
	if v != nil {
		_c.SetConversationID(*v)
	}
	return _c
}

// SetToolName sets the "tool_name" field.
func (_c *ToolInvocationCreate) SetToolName(v string) *ToolInvocationCreate {
	_c.mutation.SetToolName(v)
	return _c
}

// SetArguments sets the "arguments" field.
func (_c *ToolInvocationCreate) SetArguments(v string) *ToolInvocationCreate {
	_c.mutation.SetArguments(v)
	return _c
}

// SetNillableArguments sets the "arguments" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableArguments(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetArguments(*v)
	}
	return _c
}

// SetResult sets the "result" field.
func (_c *ToolInvocationCreate) SetResult(v string) *ToolInvocationCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableResult(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ToolInvocationCreate) SetStatus(v string) *ToolInvocationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableStatus(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *ToolInvocationCreate) SetRequestID(v string) *ToolInvocationCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableRequestID(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetNeedsApproval sets the "needs_approval" field.
func (_c *ToolInvocationCreate) SetNeedsApproval(v bool) *ToolInvocationCreate {
	_c.mutation.SetNeedsApproval(v)
	return _c
}

// SetNillableNeedsApproval sets the "needs_approval" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableNeedsApproval(v *bool) *ToolInvocationCreate {
	if v != nil {
		_c.SetNeedsApproval(*v)
	}
	return _c
}

// SetApprovalState sets the "approval_state" field.
func (_c *ToolInvocationCreate) SetApprovalState(v string) *ToolInvocationCreate {
	_c.mutation.SetApprovalState(v)
	return _c
}

// SetNillableApprovalState sets the "approval_state" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableApprovalState(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetApprovalState(*v)
	}
	return _c
}

// SetApprovalReason sets the "approval_reason" field.
func (_c *ToolInvocationCreate) SetApprovalReason(v string) *ToolInvocationCreate {
	_c.mutation.SetApprovalReason(v)
	return _c
}

// SetNillableApprovalReason sets the "approval_reason" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableApprovalReason(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetApprovalReason(*v)
	}
	return _c
}

// SetApprovedBy sets the "approved_by" field.
func (_c *ToolInvocationCreate) SetApprovedBy(v int) *ToolInvocationCreate {
	_c.mutation.SetApprovedBy(v)
	return _c
}

// SetNillableApprovedBy sets the "approved_by" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableApprovedBy(v *int) *ToolInvocationCreate {
	if v != nil {
		_c.SetApprovedBy(*v)
	}
	return _c
}

// SetApprovedAt sets the "approved_at" field.
func (_c *ToolInvocationCreate) SetApprovedAt(v time.Time) *ToolInvocationCreate {
	_c.mutation.SetApprovedAt(v)
	return _c
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableApprovedAt(v *time.Time) *ToolInvocationCreate {
	if v != nil {
		_c.SetApprovedAt(*v)
	}
	return _c
}

// SetDryRun sets the "dry_run" field.
func (_c *ToolInvocationCreate) SetDryRun(v bool) *ToolInvocationCreate {
	_c.mutation.SetDryRun(v)
	return _c
}

// SetNillableDryRun sets the "dry_run" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableDryRun(v *bool) *ToolInvocationCreate {
	if v != nil {
		_c.SetDryRun(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *ToolInvocationCreate) SetError(v string) *ToolInvocationCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableError(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ToolInvocationCreate) SetUserID(v int) *ToolInvocationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableUserID(v *int) *ToolInvocationCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetPermissionCheck sets the "permission_check" field.
func (_c *ToolInvocationCreate) SetPermissionCheck(v string) *ToolInvocationCreate {
	_c.mutation.SetPermissionCheck(v)
	return _c
}

// SetNillablePermissionCheck sets the "permission_check" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillablePermissionCheck(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetPermissionCheck(*v)
	}
	return _c
}

// SetPermissionReason sets the "permission_reason" field.
func (_c *ToolInvocationCreate) SetPermissionReason(v string) *ToolInvocationCreate {
	_c.mutation.SetPermissionReason(v)
	return _c
}

// SetNillablePermissionReason sets the "permission_reason" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillablePermissionReason(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetPermissionReason(*v)
	}
	return _c
}

// SetRoleSnapshot sets the "role_snapshot" field.
func (_c *ToolInvocationCreate) SetRoleSnapshot(v string) *ToolInvocationCreate {
	_c.mutation.SetRoleSnapshot(v)
	return _c
}

// SetNillableRoleSnapshot sets the "role_snapshot" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableRoleSnapshot(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetRoleSnapshot(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ToolInvocationCreate) SetProvider(v string) *ToolInvocationCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableProvider(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetMcpServerName sets the "mcp_server_name" field.
func (_c *ToolInvocationCreate) SetMcpServerName(v string) *ToolInvocationCreate {
	_c.mutation.SetMcpServerName(v)
	return _c
}

// SetNillableMcpServerName sets the "mcp_server_name" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableMcpServerName(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetMcpServerName(*v)
	}
	return _c
}

// SetMcpRawToolName sets the "mcp_raw_tool_name" field.
func (_c *ToolInvocationCreate) SetMcpRawToolName(v string) *ToolInvocationCreate {
	_c.mutation.SetMcpRawToolName(v)
	return _c
}

// SetNillableMcpRawToolName sets the "mcp_raw_tool_name" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableMcpRawToolName(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetMcpRawToolName(*v)
	}
	return _c
}

// SetMcpCallableName sets the "mcp_callable_name" field.
func (_c *ToolInvocationCreate) SetMcpCallableName(v string) *ToolInvocationCreate {
	_c.mutation.SetMcpCallableName(v)
	return _c
}

// SetNillableMcpCallableName sets the "mcp_callable_name" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableMcpCallableName(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetMcpCallableName(*v)
	}
	return _c
}

// SetArgsRedacted sets the "args_redacted" field.
func (_c *ToolInvocationCreate) SetArgsRedacted(v string) *ToolInvocationCreate {
	_c.mutation.SetArgsRedacted(v)
	return _c
}

// SetNillableArgsRedacted sets the "args_redacted" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableArgsRedacted(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetArgsRedacted(*v)
	}
	return _c
}

// SetOutputSummary sets the "output_summary" field.
func (_c *ToolInvocationCreate) SetOutputSummary(v string) *ToolInvocationCreate {
	_c.mutation.SetOutputSummary(v)
	return _c
}

// SetNillableOutputSummary sets the "output_summary" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableOutputSummary(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetOutputSummary(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *ToolInvocationCreate) SetDurationMs(v int) *ToolInvocationCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableDurationMs(v *int) *ToolInvocationCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *ToolInvocationCreate) SetErrorCode(v string) *ToolInvocationCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableErrorCode(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *ToolInvocationCreate) SetRunID(v int) *ToolInvocationCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableRunID(v *int) *ToolInvocationCreate {
	if v != nil {
		_c.SetRunID(*v)
	}
	return _c
}

// SetStepID sets the "step_id" field.
func (_c *ToolInvocationCreate) SetStepID(v int) *ToolInvocationCreate {
	_c.mutation.SetStepID(v)
	return _c
}

// SetNillableStepID sets the "step_id" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableStepID(v *int) *ToolInvocationCreate {
	if v != nil {
		_c.SetStepID(*v)
	}
	return _c
}

// SetRisk sets the "risk" field.
func (_c *ToolInvocationCreate) SetRisk(v string) *ToolInvocationCreate {
	_c.mutation.SetRisk(v)
	return _c
}

// SetNillableRisk sets the "risk" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableRisk(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetRisk(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *ToolInvocationCreate) SetCategory(v string) *ToolInvocationCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableCategory(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetTargetType sets the "target_type" field.
func (_c *ToolInvocationCreate) SetTargetType(v string) *ToolInvocationCreate {
	_c.mutation.SetTargetType(v)
	return _c
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableTargetType(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetTargetType(*v)
	}
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *ToolInvocationCreate) SetTargetID(v string) *ToolInvocationCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableTargetID(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetTargetID(*v)
	}
	return _c
}

// SetSupportRef sets the "support_ref" field.
func (_c *ToolInvocationCreate) SetSupportRef(v string) *ToolInvocationCreate {
	_c.mutation.SetSupportRef(v)
	return _c
}

// SetNillableSupportRef sets the "support_ref" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableSupportRef(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetSupportRef(*v)
	}
	return _c
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (_c *ToolInvocationCreate) SetIdempotencyKeyHash(v string) *ToolInvocationCreate {
	_c.mutation.SetIdempotencyKeyHash(v)
	return _c
}

// SetNillableIdempotencyKeyHash sets the "idempotency_key_hash" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableIdempotencyKeyHash(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetIdempotencyKeyHash(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ToolInvocationCreate) SetExpiresAt(v time.Time) *ToolInvocationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableExpiresAt(v *time.Time) *ToolInvocationCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetVerifyState sets the "verify_state" field.
func (_c *ToolInvocationCreate) SetVerifyState(v string) *ToolInvocationCreate {
	_c.mutation.SetVerifyState(v)
	return _c
}

// SetNillableVerifyState sets the "verify_state" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableVerifyState(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetVerifyState(*v)
	}
	return _c
}

// SetVerifyNote sets the "verify_note" field.
func (_c *ToolInvocationCreate) SetVerifyNote(v string) *ToolInvocationCreate {
	_c.mutation.SetVerifyNote(v)
	return _c
}

// SetNillableVerifyNote sets the "verify_note" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableVerifyNote(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetVerifyNote(*v)
	}
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *ToolInvocationCreate) SetAttemptCount(v int) *ToolInvocationCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableAttemptCount(v *int) *ToolInvocationCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetLastErrorCode sets the "last_error_code" field.
func (_c *ToolInvocationCreate) SetLastErrorCode(v string) *ToolInvocationCreate {
	_c.mutation.SetLastErrorCode(v)
	return _c
}

// SetNillableLastErrorCode sets the "last_error_code" field if the given value is not nil.
func (_c *ToolInvocationCreate) SetNillableLastErrorCode(v *string) *ToolInvocationCreate {
	if v != nil {
		_c.SetLastErrorCode(*v)
	}
	return _c
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_c *ToolInvocationCreate) SetConversation(v *Conversation) *ToolInvocationCreate {
	return _c.SetConversationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ToolInvocationCreate) SetUser(v *User) *ToolInvocationCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ToolInvocationMutation object of the builder.
func (_c *ToolInvocationCreate) Mutation() *ToolInvocationMutation {
	return _c.mutation
}

// Save creates the ToolInvocation in the database.
func (_c *ToolInvocationCreate) Save(ctx context.Context) (*ToolInvocation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ToolInvocationCreate) SaveX(ctx context.Context) *ToolInvocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ToolInvocationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ToolInvocationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ToolInvocationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := toolinvocation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.Arguments(); !ok {
		v := toolinvocation.DefaultArguments
		_c.mutation.SetArguments(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := toolinvocation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.NeedsApproval(); !ok {
		v := toolinvocation.DefaultNeedsApproval
		_c.mutation.SetNeedsApproval(v)
	}
	if _, ok := _c.mutation.ApprovalState(); !ok {
		v := toolinvocation.DefaultApprovalState
		_c.mutation.SetApprovalState(v)
	}
	if _, ok := _c.mutation.ApprovalReason(); !ok {
		v := toolinvocation.DefaultApprovalReason
		_c.mutation.SetApprovalReason(v)
	}
	if _, ok := _c.mutation.DryRun(); !ok {
		v := toolinvocation.DefaultDryRun
		_c.mutation.SetDryRun(v)
	}
	if _, ok := _c.mutation.PermissionCheck(); !ok {
		v := toolinvocation.DefaultPermissionCheck
		_c.mutation.SetPermissionCheck(v)
	}
	if _, ok := _c.mutation.PermissionReason(); !ok {
		v := toolinvocation.DefaultPermissionReason
		_c.mutation.SetPermissionReason(v)
	}
	if _, ok := _c.mutation.RoleSnapshot(); !ok {
		v := toolinvocation.DefaultRoleSnapshot
		_c.mutation.SetRoleSnapshot(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := toolinvocation.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.McpServerName(); !ok {
		v := toolinvocation.DefaultMcpServerName
		_c.mutation.SetMcpServerName(v)
	}
	if _, ok := _c.mutation.McpRawToolName(); !ok {
		v := toolinvocation.DefaultMcpRawToolName
		_c.mutation.SetMcpRawToolName(v)
	}
	if _, ok := _c.mutation.McpCallableName(); !ok {
		v := toolinvocation.DefaultMcpCallableName
		_c.mutation.SetMcpCallableName(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := toolinvocation.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		v := toolinvocation.DefaultErrorCode
		_c.mutation.SetErrorCode(v)
	}
	if _, ok := _c.mutation.Risk(); !ok {
		v := toolinvocation.DefaultRisk
		_c.mutation.SetRisk(v)
	}
	if _, ok := _c.mutation.Category(); !ok {
		v := toolinvocation.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		v := toolinvocation.DefaultTargetType
		_c.mutation.SetTargetType(v)
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		v := toolinvocation.DefaultTargetID
		_c.mutation.SetTargetID(v)
	}
	if _, ok := _c.mutation.SupportRef(); !ok {
		v := toolinvocation.DefaultSupportRef
		_c.mutation.SetSupportRef(v)
	}
	if _, ok := _c.mutation.VerifyState(); !ok {
		v := toolinvocation.DefaultVerifyState
		_c.mutation.SetVerifyState(v)
	}
	if _, ok := _c.mutation.VerifyNote(); !ok {
		v := toolinvocation.DefaultVerifyNote
		_c.mutation.SetVerifyNote(v)
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := toolinvocation.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
	if _, ok := _c.mutation.LastErrorCode(); !ok {
		v := toolinvocation.DefaultLastErrorCode
		_c.mutation.SetLastErrorCode(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ToolInvocationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ToolInvocation.created_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ToolInvocation.tenant_id"`)}
	}
	if _, ok := _c.mutation.ToolName(); !ok {
		return &ValidationError{Name: "tool_name", err: errors.New(`ent: missing required field "ToolInvocation.tool_name"`)}
	}
	if _, ok := _c.mutation.Arguments(); !ok {
		return &ValidationError{Name: "arguments", err: errors.New(`ent: missing required field "ToolInvocation.arguments"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ToolInvocation.status"`)}
	}
	if _, ok := _c.mutation.NeedsApproval(); !ok {
		return &ValidationError{Name: "needs_approval", err: errors.New(`ent: missing required field "ToolInvocation.needs_approval"`)}
	}
	if _, ok := _c.mutation.ApprovalState(); !ok {
		return &ValidationError{Name: "approval_state", err: errors.New(`ent: missing required field "ToolInvocation.approval_state"`)}
	}
	if _, ok := _c.mutation.ApprovalReason(); !ok {
		return &ValidationError{Name: "approval_reason", err: errors.New(`ent: missing required field "ToolInvocation.approval_reason"`)}
	}
	if _, ok := _c.mutation.DryRun(); !ok {
		return &ValidationError{Name: "dry_run", err: errors.New(`ent: missing required field "ToolInvocation.dry_run"`)}
	}
	if _, ok := _c.mutation.PermissionCheck(); !ok {
		return &ValidationError{Name: "permission_check", err: errors.New(`ent: missing required field "ToolInvocation.permission_check"`)}
	}
	if _, ok := _c.mutation.PermissionReason(); !ok {
		return &ValidationError{Name: "permission_reason", err: errors.New(`ent: missing required field "ToolInvocation.permission_reason"`)}
	}
	if _, ok := _c.mutation.RoleSnapshot(); !ok {
		return &ValidationError{Name: "role_snapshot", err: errors.New(`ent: missing required field "ToolInvocation.role_snapshot"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ToolInvocation.provider"`)}
	}
	if _, ok := _c.mutation.McpServerName(); !ok {
		return &ValidationError{Name: "mcp_server_name", err: errors.New(`ent: missing required field "ToolInvocation.mcp_server_name"`)}
	}
	if _, ok := _c.mutation.McpRawToolName(); !ok {
		return &ValidationError{Name: "mcp_raw_tool_name", err: errors.New(`ent: missing required field "ToolInvocation.mcp_raw_tool_name"`)}
	}
	if _, ok := _c.mutation.McpCallableName(); !ok {
		return &ValidationError{Name: "mcp_callable_name", err: errors.New(`ent: missing required field "ToolInvocation.mcp_callable_name"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "ToolInvocation.duration_ms"`)}
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "ToolInvocation.error_code"`)}
	}
	if _, ok := _c.mutation.Risk(); !ok {
		return &ValidationError{Name: "risk", err: errors.New(`ent: missing required field "ToolInvocation.risk"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "ToolInvocation.category"`)}
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		return &ValidationError{Name: "target_type", err: errors.New(`ent: missing required field "ToolInvocation.target_type"`)}
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "ToolInvocation.target_id"`)}
	}
	if _, ok := _c.mutation.SupportRef(); !ok {
		return &ValidationError{Name: "support_ref", err: errors.New(`ent: missing required field "ToolInvocation.support_ref"`)}
	}
	if _, ok := _c.mutation.VerifyState(); !ok {
		return &ValidationError{Name: "verify_state", err: errors.New(`ent: missing required field "ToolInvocation.verify_state"`)}
	}
	if _, ok := _c.mutation.VerifyNote(); !ok {
		return &ValidationError{Name: "verify_note", err: errors.New(`ent: missing required field "ToolInvocation.verify_note"`)}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "ToolInvocation.attempt_count"`)}
	}
	if _, ok := _c.mutation.LastErrorCode(); !ok {
		return &ValidationError{Name: "last_error_code", err: errors.New(`ent: missing required field "ToolInvocation.last_error_code"`)}
	}
	return nil
}

func (_c *ToolInvocationCreate) sqlSave(ctx context.Context) (*ToolInvocation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ToolInvocationCreate) createSpec() (*ToolInvocation, *sqlgraph.CreateSpec) {
	var (
		_node = &ToolInvocation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(toolinvocation.Table, sqlgraph.NewFieldSpec(toolinvocation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(toolinvocation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(toolinvocation.FieldTenantID, field.TypeInt, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.ToolName(); ok {
		_spec.SetField(toolinvocation.FieldToolName, field.TypeString, value)
		_node.ToolName = value
	}
	if value, ok := _c.mutation.Arguments(); ok {
		_spec.SetField(toolinvocation.FieldArguments, field.TypeString, value)
		_node.Arguments = value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(toolinvocation.FieldResult, field.TypeString, value)
		_node.Result = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(toolinvocation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(toolinvocation.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.NeedsApproval(); ok {
		_spec.SetField(toolinvocation.FieldNeedsApproval, field.TypeBool, value)
		_node.NeedsApproval = value
	}
	if value, ok := _c.mutation.ApprovalState(); ok {
		_spec.SetField(toolinvocation.FieldApprovalState, field.TypeString, value)
		_node.ApprovalState = value
	}
	if value, ok := _c.mutation.ApprovalReason(); ok {
		_spec.SetField(toolinvocation.FieldApprovalReason, field.TypeString, value)
		_node.ApprovalReason = value
	}
	if value, ok := _c.mutation.ApprovedBy(); ok {
		_spec.SetField(toolinvocation.FieldApprovedBy, field.TypeInt, value)
		_node.ApprovedBy = value
	}
	if value, ok := _c.mutation.ApprovedAt(); ok {
		_spec.SetField(toolinvocation.FieldApprovedAt, field.TypeTime, value)
		_node.ApprovedAt = value
	}
	if value, ok := _c.mutation.DryRun(); ok {
		_spec.SetField(toolinvocation.FieldDryRun, field.TypeBool, value)
		_node.DryRun = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(toolinvocation.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	if value, ok := _c.mutation.PermissionCheck(); ok {
		_spec.SetField(toolinvocation.FieldPermissionCheck, field.TypeString, value)
		_node.PermissionCheck = value
	}
	if value, ok := _c.mutation.PermissionReason(); ok {
		_spec.SetField(toolinvocation.FieldPermissionReason, field.TypeString, value)
		_node.PermissionReason = value
	}
	if value, ok := _c.mutation.RoleSnapshot(); ok {
		_spec.SetField(toolinvocation.FieldRoleSnapshot, field.TypeString, value)
		_node.RoleSnapshot = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(toolinvocation.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.McpServerName(); ok {
		_spec.SetField(toolinvocation.FieldMcpServerName, field.TypeString, value)
		_node.McpServerName = value
	}
	if value, ok := _c.mutation.McpRawToolName(); ok {
		_spec.SetField(toolinvocation.FieldMcpRawToolName, field.TypeString, value)
		_node.McpRawToolName = value
	}
	if value, ok := _c.mutation.McpCallableName(); ok {
		_spec.SetField(toolinvocation.FieldMcpCallableName, field.TypeString, value)
		_node.McpCallableName = value
	}
	if value, ok := _c.mutation.ArgsRedacted(); ok {
		_spec.SetField(toolinvocation.FieldArgsRedacted, field.TypeString, value)
		_node.ArgsRedacted = value
	}
	if value, ok := _c.mutation.OutputSummary(); ok {
		_spec.SetField(toolinvocation.FieldOutputSummary, field.TypeString, value)
		_node.OutputSummary = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(toolinvocation.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(toolinvocation.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.RunID(); ok {
		_spec.SetField(toolinvocation.FieldRunID, field.TypeInt, value)
		_node.RunID = value
	}
	if value, ok := _c.mutation.StepID(); ok {
		_spec.SetField(toolinvocation.FieldStepID, field.TypeInt, value)
		_node.StepID = value
	}
	if value, ok := _c.mutation.Risk(); ok {
		_spec.SetField(toolinvocation.FieldRisk, field.TypeString, value)
		_node.Risk = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(toolinvocation.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.TargetType(); ok {
		_spec.SetField(toolinvocation.FieldTargetType, field.TypeString, value)
		_node.TargetType = value
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(toolinvocation.FieldTargetID, field.TypeString, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.SupportRef(); ok {
		_spec.SetField(toolinvocation.FieldSupportRef, field.TypeString, value)
		_node.SupportRef = value
	}
	if value, ok := _c.mutation.IdempotencyKeyHash(); ok {
		_spec.SetField(toolinvocation.FieldIdempotencyKeyHash, field.TypeString, value)
		_node.IdempotencyKeyHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(toolinvocation.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.VerifyState(); ok {
		_spec.SetField(toolinvocation.FieldVerifyState, field.TypeString, value)
		_node.VerifyState = value
	}
	if value, ok := _c.mutation.VerifyNote(); ok {
		_spec.SetField(toolinvocation.FieldVerifyNote, field.TypeString, value)
		_node.VerifyNote = value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(toolinvocation.FieldAttemptCount, field.TypeInt, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.LastErrorCode(); ok {
		_spec.SetField(toolinvocation.FieldLastErrorCode, field.TypeString, value)
		_node.LastErrorCode = value
	}
	if nodes := _c.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   toolinvocation.ConversationTable,
			Columns: []string{toolinvocation.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConversationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   toolinvocation.UserTable,
			Columns: []string{toolinvocation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ToolInvocationCreateBulk is the builder for creating many ToolInvocation entities in bulk.
type ToolInvocationCreateBulk struct {
	config
	err      error
	builders []*ToolInvocationCreate
}

// Save creates the ToolInvocation entities in the database.
func (_c *ToolInvocationCreateBulk) Save(ctx context.Context) ([]*ToolInvocation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ToolInvocation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ToolInvocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ToolInvocationCreateBulk) SaveX(ctx context.Context) []*ToolInvocation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ToolInvocationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ToolInvocationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
