// Code generated by ent, DO NOT EDIT.

package botartifact

import (
	"itsm-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldTenantID, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldOwnerUserID, v))
}

// ConversationID applies equality check predicate on the "conversation_id" field. It's identical to ConversationIDEQ.
func ConversationID(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldConversationID, v))
}

// RunID applies equality check predicate on the "run_id" field. It's identical to RunIDEQ.
func RunID(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldRunID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldKind, v))
}

// ToolName applies equality check predicate on the "tool_name" field. It's identical to ToolNameEQ.
func ToolName(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldToolName, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldTitle, v))
}

// ContentJSON applies equality check predicate on the "content_json" field. It's identical to ContentJSONEQ.
func ContentJSON(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldContentJSON, v))
}

// EvidenceJSON applies equality check predicate on the "evidence_json" field. It's identical to EvidenceJSONEQ.
func EvidenceJSON(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldEvidenceJSON, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLTE(FieldTenantID, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLTE(FieldOwnerUserID, v))
}

// ConversationIDEQ applies the EQ predicate on the "conversation_id" field.
func ConversationIDEQ(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldConversationID, v))
}

// ConversationIDNEQ applies the NEQ predicate on the "conversation_id" field.
func ConversationIDNEQ(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNEQ(FieldConversationID, v))
}

// ConversationIDIn applies the In predicate on the "conversation_id" field.
func ConversationIDIn(vs ...int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIn(FieldConversationID, vs...))
}

// ConversationIDNotIn applies the NotIn predicate on the "conversation_id" field.
func ConversationIDNotIn(vs ...int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotIn(FieldConversationID, vs...))
}

// ConversationIDGT applies the GT predicate on the "conversation_id" field.
func ConversationIDGT(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGT(FieldConversationID, v))
}

// ConversationIDGTE applies the GTE predicate on the "conversation_id" field.
func ConversationIDGTE(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGTE(FieldConversationID, v))
}

// ConversationIDLT applies the LT predicate on the "conversation_id" field.
func ConversationIDLT(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLT(FieldConversationID, v))
}

// ConversationIDLTE applies the LTE predicate on the "conversation_id" field.
func ConversationIDLTE(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLTE(FieldConversationID, v))
}

// ConversationIDIsNil applies the IsNil predicate on the "conversation_id" field.
func ConversationIDIsNil() predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIsNull(FieldConversationID))
}

// ConversationIDNotNil applies the NotNil predicate on the "conversation_id" field.
func ConversationIDNotNil() predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotNull(FieldConversationID))
}

// RunIDEQ applies the EQ predicate on the "run_id" field.
func RunIDEQ(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldRunID, v))
}

// RunIDNEQ applies the NEQ predicate on the "run_id" field.
func RunIDNEQ(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNEQ(FieldRunID, v))
}

// RunIDIn applies the In predicate on the "run_id" field.
func RunIDIn(vs ...int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIn(FieldRunID, vs...))
}

// RunIDNotIn applies the NotIn predicate on the "run_id" field.
func RunIDNotIn(vs ...int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotIn(FieldRunID, vs...))
}

// RunIDGT applies the GT predicate on the "run_id" field.
func RunIDGT(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGT(FieldRunID, v))
}

// RunIDGTE applies the GTE predicate on the "run_id" field.
func RunIDGTE(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGTE(FieldRunID, v))
}

// RunIDLT applies the LT predicate on the "run_id" field.
func RunIDLT(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLT(FieldRunID, v))
}

// RunIDLTE applies the LTE predicate on the "run_id" field.
func RunIDLTE(v int) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLTE(FieldRunID, v))
}

// RunIDIsNil applies the IsNil predicate on the "run_id" field.
func RunIDIsNil() predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIsNull(FieldRunID))
}

// RunIDNotNil applies the NotNil predicate on the "run_id" field.
func RunIDNotNil() predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotNull(FieldRunID))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldContainsFold(FieldKind, v))
}

// ToolNameEQ applies the EQ predicate on the "tool_name" field.
func ToolNameEQ(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldToolName, v))
}

// ToolNameNEQ applies the NEQ predicate on the "tool_name" field.
func ToolNameNEQ(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNEQ(FieldToolName, v))
}

// ToolNameIn applies the In predicate on the "tool_name" field.
func ToolNameIn(vs ...string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIn(FieldToolName, vs...))
}

// ToolNameNotIn applies the NotIn predicate on the "tool_name" field.
func ToolNameNotIn(vs ...string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotIn(FieldToolName, vs...))
}

// ToolNameGT applies the GT predicate on the "tool_name" field.
func ToolNameGT(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGT(FieldToolName, v))
}

// ToolNameGTE applies the GTE predicate on the "tool_name" field.
func ToolNameGTE(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGTE(FieldToolName, v))
}

// ToolNameLT applies the LT predicate on the "tool_name" field.
func ToolNameLT(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLT(FieldToolName, v))
}

// ToolNameLTE applies the LTE predicate on the "tool_name" field.
func ToolNameLTE(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLTE(FieldToolName, v))
}

// ToolNameContains applies the Contains predicate on the "tool_name" field.
func ToolNameContains(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldContains(FieldToolName, v))
}

// ToolNameHasPrefix applies the HasPrefix predicate on the "tool_name" field.
func ToolNameHasPrefix(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldHasPrefix(FieldToolName, v))
}

// ToolNameHasSuffix applies the HasSuffix predicate on the "tool_name" field.
func ToolNameHasSuffix(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldHasSuffix(FieldToolName, v))
}

// ToolNameEqualFold applies the EqualFold predicate on the "tool_name" field.
func ToolNameEqualFold(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEqualFold(FieldToolName, v))
}

// ToolNameContainsFold applies the ContainsFold predicate on the "tool_name" field.
func ToolNameContainsFold(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldContainsFold(FieldToolName, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldContainsFold(FieldTitle, v))
}

// ContentJSONEQ applies the EQ predicate on the "content_json" field.
func ContentJSONEQ(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldContentJSON, v))
}

// ContentJSONNEQ applies the NEQ predicate on the "content_json" field.
func ContentJSONNEQ(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNEQ(FieldContentJSON, v))
}

// ContentJSONIn applies the In predicate on the "content_json" field.
func ContentJSONIn(vs ...string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIn(FieldContentJSON, vs...))
}

// ContentJSONNotIn applies the NotIn predicate on the "content_json" field.
func ContentJSONNotIn(vs ...string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotIn(FieldContentJSON, vs...))
}

// ContentJSONGT applies the GT predicate on the "content_json" field.
func ContentJSONGT(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGT(FieldContentJSON, v))
}

// ContentJSONGTE applies the GTE predicate on the "content_json" field.
func ContentJSONGTE(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGTE(FieldContentJSON, v))
}

// ContentJSONLT applies the LT predicate on the "content_json" field.
func ContentJSONLT(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLT(FieldContentJSON, v))
}

// ContentJSONLTE applies the LTE predicate on the "content_json" field.
func ContentJSONLTE(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLTE(FieldContentJSON, v))
}

// ContentJSONContains applies the Contains predicate on the "content_json" field.
func ContentJSONContains(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldContains(FieldContentJSON, v))
}

// ContentJSONHasPrefix applies the HasPrefix predicate on the "content_json" field.
func ContentJSONHasPrefix(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldHasPrefix(FieldContentJSON, v))
}

// ContentJSONHasSuffix applies the HasSuffix predicate on the "content_json" field.
func ContentJSONHasSuffix(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldHasSuffix(FieldContentJSON, v))
}

// ContentJSONEqualFold applies the EqualFold predicate on the "content_json" field.
func ContentJSONEqualFold(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEqualFold(FieldContentJSON, v))
}

// ContentJSONContainsFold applies the ContainsFold predicate on the "content_json" field.
func ContentJSONContainsFold(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldContainsFold(FieldContentJSON, v))
}

// EvidenceJSONEQ applies the EQ predicate on the "evidence_json" field.
func EvidenceJSONEQ(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldEvidenceJSON, v))
}

// EvidenceJSONNEQ applies the NEQ predicate on the "evidence_json" field.
func EvidenceJSONNEQ(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNEQ(FieldEvidenceJSON, v))
}

// EvidenceJSONIn applies the In predicate on the "evidence_json" field.
func EvidenceJSONIn(vs ...string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIn(FieldEvidenceJSON, vs...))
}

// EvidenceJSONNotIn applies the NotIn predicate on the "evidence_json" field.
func EvidenceJSONNotIn(vs ...string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotIn(FieldEvidenceJSON, vs...))
}

// EvidenceJSONGT applies the GT predicate on the "evidence_json" field.
func EvidenceJSONGT(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGT(FieldEvidenceJSON, v))
}

// EvidenceJSONGTE applies the GTE predicate on the "evidence_json" field.
func EvidenceJSONGTE(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGTE(FieldEvidenceJSON, v))
}

// EvidenceJSONLT applies the LT predicate on the "evidence_json" field.
func EvidenceJSONLT(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLT(FieldEvidenceJSON, v))
}

// EvidenceJSONLTE applies the LTE predicate on the "evidence_json" field.
func EvidenceJSONLTE(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLTE(FieldEvidenceJSON, v))
}

// EvidenceJSONContains applies the Contains predicate on the "evidence_json" field.
func EvidenceJSONContains(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldContains(FieldEvidenceJSON, v))
}

// EvidenceJSONHasPrefix applies the HasPrefix predicate on the "evidence_json" field.
func EvidenceJSONHasPrefix(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldHasPrefix(FieldEvidenceJSON, v))
}

// EvidenceJSONHasSuffix applies the HasSuffix predicate on the "evidence_json" field.
func EvidenceJSONHasSuffix(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldHasSuffix(FieldEvidenceJSON, v))
}

// EvidenceJSONEqualFold applies the EqualFold predicate on the "evidence_json" field.
func EvidenceJSONEqualFold(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEqualFold(FieldEvidenceJSON, v))
}

// EvidenceJSONContainsFold applies the ContainsFold predicate on the "evidence_json" field.
func EvidenceJSONContainsFold(v string) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldContainsFold(FieldEvidenceJSON, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BotArtifact {
	return predicate.BotArtifact(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BotArtifact) predicate.BotArtifact {
	return predicate.BotArtifact(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BotArtifact) predicate.BotArtifact {
	return predicate.BotArtifact(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BotArtifact) predicate.BotArtifact {
	return predicate.BotArtifact(sql.NotPredicates(p))
}
