-- 20260922 建 attachments 通用附件表（expand 阶段，幂等可重跑）。
-- 方案：docs/plan/generic-attachment-richtext-control-plan.md §5.1（P1/BE-1，v1.0 已冻结 DDL）。
-- 与 ticket_attachments 的字段对应：biz_type='ticket' 时 biz_id 即 ticket_id，其余列同名同义
-- （含 file_type 与 mime_type 同值的历史语义），P2 回填可直接 SELECT。
-- 保 ID 平移是硬要求：历史富文本 data-attachment-id 与 /tickets/:id/attachments/:ref URL 都引用旧 ID。
-- RLS 沿用仓库既有表模式（见 20260828_create_alerts.sql / 20260831_ai_analysis_result_expand.sql），
-- 保证 RLS_MODE=enforce 下该表按租户变量可查。
-- 列类型与 BE-2 ent schema 对齐（取证 ent v0.14.6 dialect/sql/schema/postgres.go:122
-- 将 field.Int 映射为 BIGINT；postgres.go:180-196 为自增列加 Identity 属性）：
-- id 用 BIGINT GENERATED BY DEFAULT AS IDENTITY（与 workflow_templates_identity_migration.go
-- 记载的「ent diff 期望 IDENTITY」一致，避免 SERIAL/IDENTITY 属性差异），其余 Int → BIGINT、
-- String → VARCHAR（长度与 schema 的 MaxLen 同源）、Time → TIMESTAMPTZ。

BEGIN;

CREATE TABLE IF NOT EXISTS attachments (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT       NOT NULL,
    biz_type     VARCHAR(64)  NOT NULL,
    biz_id       BIGINT       NOT NULL,
    usage        VARCHAR(32)  NOT NULL DEFAULT 'attachment',  -- attachment | inline_image | comment_attachment
    file_name    VARCHAR(255) NOT NULL,
    file_path    VARCHAR(512) NOT NULL,                       -- 存储 key（服务端生成）
    file_url     VARCHAR(1024),
    file_size    BIGINT       NOT NULL,
    file_type    VARCHAR(128) NOT NULL,                       -- 历史语义：与 mime_type 同值；分类请用 usage/biz_type
    mime_type    VARCHAR(128),
    sha256       VARCHAR(64),
    client_token VARCHAR(64),                                 -- 幂等键（可选；NULL 表示不去重）
    uploaded_by  BIGINT       NOT NULL,
    status       VARCHAR(16)  NOT NULL DEFAULT 'active',      -- active | deleted
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_attachments_biz
    ON attachments (tenant_id, biz_type, biz_id, usage)
    WHERE status = 'active';

CREATE UNIQUE INDEX IF NOT EXISTS uq_attachments_path
    ON attachments (file_path);

-- 幂等去重（client_token 为空的历史/普通上传不受约束）
CREATE UNIQUE INDEX IF NOT EXISTS uq_attachments_client_token
    ON attachments (tenant_id, biz_type, biz_id, client_token)
    WHERE client_token IS NOT NULL;

ALTER TABLE attachments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_attachments ON attachments;
CREATE POLICY tenant_isolation_attachments ON attachments
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::BIGINT)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::BIGINT);

COMMIT;
