-- 20260924 建 llm_provider_configs / llm_user_preferences（多 LLM Provider 支持与可切换方案 BE-1，expand 阶段，幂等可重跑）。
-- 方案：docs/plan/multi-llm-provider-plan.md §3.1.1 / §3.1.2 / §4.2（无菜单/路由迁移）。
-- 列类型与 ent schema 同源（ent v0.14.6 dialect/sql/schema/postgres.go:115-141）：
--   field.Int → BIGINT、field.String(MaxLen) → VARCHAR(MaxLen)、field.Text → TEXT、
--   field.JSON → JSONB、field.Bool → BOOLEAN、field.Time → TIMESTAMPTZ；
--   id 用 BIGINT GENERATED BY DEFAULT AS IDENTITY（与 ent 自增列 diff 属性一致，见 20260922_create_attachments_expand.sql）。
-- 密钥只存密文：encrypted_api_key 为 AES-GCM 密文（AAD=tenant_id:name），禁明文，与 connector_configs 先例一致。
-- 「每租户至多一个默认实例」由部分唯一索引兜底（软删行不占用默认位；ent 不支持部分索引）。
-- RLS 沿用仓库既有表模式（见 20260828_create_alerts.sql / 20260922_create_attachments_expand.sql），
-- 保证 RLS_MODE=enforce 下按 app.current_tenant 可查。

BEGIN;

CREATE TABLE IF NOT EXISTS llm_provider_configs (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT       NOT NULL,
    name              VARCHAR(64)  NOT NULL,                       -- 实例 key（API/请求参数使用）
    display_name      VARCHAR(100) NOT NULL,
    protocol          VARCHAR(32)  NOT NULL,                       -- openai_chat_completions | openai_responses | anthropic_messages | google_gemini
    variant           VARCHAR(32),                                 -- azure | ollama | minimax | NULL(标准实现)
    adapter_options   JSONB,                                       -- 变体专属非敏感参数（禁放密钥）
    model             VARCHAR(100),
    endpoint          VARCHAR(500),                                -- 留空回退内置默认地址
    deployment        VARCHAR(100),                                -- variant=azure 使用
    encrypted_api_key TEXT,                                        -- AES-GCM 密文；无鉴权实例可为空
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    is_default        BOOLEAN      NOT NULL DEFAULT FALSE,
    source            VARCHAR(20)  NOT NULL DEFAULT 'manual',      -- manual | imported
    status            VARCHAR(20)  NOT NULL DEFAULT 'configured',  -- configured | ok | error
    last_error        VARCHAR(2000),
    last_tested_at    TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ                                  -- 软删除
);

-- 索引名与 ent 生成名一致（ent/migrate/schema.go: llmproviderconfig_*）：
-- bootstrap 路径（ITSM_AUTO_MIGRATE → client.Schema.Create）按名字判定已存在并跳过，
-- 避免「迁移建一套 + ent 建一套」的同列重复索引。
CREATE UNIQUE INDEX IF NOT EXISTS llmproviderconfig_tenant_id_name
    ON llm_provider_configs (tenant_id, name);

CREATE INDEX IF NOT EXISTS llmproviderconfig_tenant_id_enabled
    ON llm_provider_configs (tenant_id, enabled);

-- 租户默认唯一：软删/非默认行不受约束
CREATE UNIQUE INDEX IF NOT EXISTS uq_llm_provider_configs_tenant_default
    ON llm_provider_configs (tenant_id)
    WHERE is_default AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS llm_user_preferences (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    tenant_id    BIGINT      NOT NULL,   -- 冗余租户，用于 provider 归属校验
    provider_key VARCHAR(64),            -- 空 = 跟随租户默认
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS llmuserpreference_user_id
    ON llm_user_preferences (user_id);

ALTER TABLE llm_provider_configs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_llm_provider_configs ON llm_provider_configs;
CREATE POLICY tenant_isolation_llm_provider_configs ON llm_provider_configs
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::BIGINT)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::BIGINT);

ALTER TABLE llm_user_preferences ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation_llm_user_preferences ON llm_user_preferences;
CREATE POLICY tenant_isolation_llm_user_preferences ON llm_user_preferences
    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::BIGINT)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::BIGINT);

COMMIT;
