// Code generated by ent, DO NOT EDIT.

package usertenantmembership

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usertenantmembership type in the database.
	Label = "user_tenant_membership"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldAccountKind holds the string denoting the account_kind field in the database.
	FieldAccountKind = "account_kind"
	// FieldSubjectType holds the string denoting the subject_type field in the database.
	FieldSubjectType = "subject_type"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldRoleID holds the string denoting the role_id field in the database.
	FieldRoleID = "role_id"
	// FieldMspRole holds the string denoting the msp_role field in the database.
	FieldMspRole = "msp_role"
	// FieldAllocationID holds the string denoting the allocation_id field in the database.
	FieldAllocationID = "allocation_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIsDefault holds the string denoting the is_default field in the database.
	FieldIsDefault = "is_default"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldInvitedBy holds the string denoting the invited_by field in the database.
	FieldInvitedBy = "invited_by"
	// FieldJoinedAt holds the string denoting the joined_at field in the database.
	FieldJoinedAt = "joined_at"
	// FieldDeassignedAt holds the string denoting the deassigned_at field in the database.
	FieldDeassignedAt = "deassigned_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeOrgs holds the string denoting the orgs edge name in mutations.
	EdgeOrgs = "orgs"
	// Table holds the table name of the usertenantmembership in the database.
	Table = "user_tenant_memberships"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_tenant_memberships"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "user_tenant_memberships"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// OrgsTable is the table that holds the orgs relation/edge.
	OrgsTable = "user_tenant_membership_orgs"
	// OrgsInverseTable is the table name for the UserTenantMembershipOrg entity.
	// It exists in this package in order to avoid circular dependency with the "usertenantmembershiporg" package.
	OrgsInverseTable = "user_tenant_membership_orgs"
	// OrgsColumn is the table column denoting the orgs relation/edge.
	OrgsColumn = "membership_id"
)

// Columns holds all SQL columns for usertenantmembership fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldTenantID,
	FieldAccountKind,
	FieldSubjectType,
	FieldSource,
	FieldRoleID,
	FieldMspRole,
	FieldAllocationID,
	FieldStatus,
	FieldIsDefault,
	FieldExpiresAt,
	FieldInvitedBy,
	FieldJoinedAt,
	FieldDeassignedAt,
	FieldDeletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsDefault holds the default value on creation for the "is_default" field.
	DefaultIsDefault bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// AccountKind defines the type for the "account_kind" enum field.
type AccountKind string

// AccountKindCustomer is the default value of the AccountKind enum.
const DefaultAccountKind = AccountKindCustomer

// AccountKind values.
const (
	AccountKindCustomer AccountKind = "customer"
	AccountKindProvider AccountKind = "provider"
	AccountKindPlatform AccountKind = "platform"
)

func (ak AccountKind) String() string {
	return string(ak)
}

// AccountKindValidator is a validator for the "account_kind" field enum values. It is called by the builders before save.
func AccountKindValidator(ak AccountKind) error {
	switch ak {
	case AccountKindCustomer, AccountKindProvider, AccountKindPlatform:
		return nil
	default:
		return fmt.Errorf("usertenantmembership: invalid enum value for account_kind field: %q", ak)
	}
}

// SubjectType defines the type for the "subject_type" enum field.
type SubjectType string

// SubjectTypeUser is the default value of the SubjectType enum.
const DefaultSubjectType = SubjectTypeUser

// SubjectType values.
const (
	SubjectTypeUser SubjectType = "user"
)

func (st SubjectType) String() string {
	return string(st)
}

// SubjectTypeValidator is a validator for the "subject_type" field enum values. It is called by the builders before save.
func SubjectTypeValidator(st SubjectType) error {
	switch st {
	case SubjectTypeUser:
		return nil
	default:
		return fmt.Errorf("usertenantmembership: invalid enum value for subject_type field: %q", st)
	}
}

// Source defines the type for the "source" enum field.
type Source string

// Source values.
const (
	SourceHome       Source = "home"
	SourceAllocation Source = "allocation"
	SourcePlatform   Source = "platform"
	SourceInvite     Source = "invite"
	SourceMigration  Source = "migration"
)

func (s Source) String() string {
	return string(s)
}

// SourceValidator is a validator for the "source" field enum values. It is called by the builders before save.
func SourceValidator(s Source) error {
	switch s {
	case SourceHome, SourceAllocation, SourcePlatform, SourceInvite, SourceMigration:
		return nil
	default:
		return fmt.Errorf("usertenantmembership: invalid enum value for source field: %q", s)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive    Status = "active"
	StatusSuspended Status = "suspended"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusSuspended:
		return nil
	default:
		return fmt.Errorf("usertenantmembership: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the UserTenantMembership queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByAccountKind orders the results by the account_kind field.
func ByAccountKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountKind, opts...).ToFunc()
}

// BySubjectType orders the results by the subject_type field.
func BySubjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubjectType, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByRoleID orders the results by the role_id field.
func ByRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleID, opts...).ToFunc()
}

// ByMspRole orders the results by the msp_role field.
func ByMspRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMspRole, opts...).ToFunc()
}

// ByAllocationID orders the results by the allocation_id field.
func ByAllocationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllocationID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIsDefault orders the results by the is_default field.
func ByIsDefault(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDefault, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByInvitedBy orders the results by the invited_by field.
func ByInvitedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvitedBy, opts...).ToFunc()
}

// ByJoinedAt orders the results by the joined_at field.
func ByJoinedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinedAt, opts...).ToFunc()
}

// ByDeassignedAt orders the results by the deassigned_at field.
func ByDeassignedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeassignedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrgsCount orders the results by orgs count.
func ByOrgsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrgsStep(), opts...)
	}
}

// ByOrgs orders the results by orgs terms.
func ByOrgs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrgsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newOrgsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrgsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OrgsTable, OrgsColumn),
	)
}
